import * as images from "../../Images";

export const ALL_CHARACTERS = [
  {
    id: 1,
    name: "Ava Robinson",
    type: "Students",
    school: "Ilvermorny",
    house: "?",
    src: images.Ava,
  },
  {
    id: 2,
    name: "Anuhea Kelii",
    type: "Students",
    school: "Ilvermorny",
    house: "?",
    src: images.Anuhea,
  },
  {
    id: 3,
    name: "Azha Pavan",
    type: "Students",
    school: "Ilvermorny",
    house: "?",
    src: images.Azha,
  },
  {
    id: 4,
    name: "Bailey-Anna Balders",
    type: "Students",
    school: "Ilvermorny",
    house: "?",
    src: images.Bailey_Anna,
  },
  {
    id: 5,
    name: "Claire Takahashi",
    type: "Students",
    school: "Ilvermorny",
    house: "?",
    src: images.Claire,
  },
  {
    id: 6,
    name: "Colby Engel",
    type: "Students",
    school: "Ilvermorny",
    house: "?",
    src: images.Colby,
  },
  {
    id: 7,
    name: "Erika Baker",
    type: "Students",
    school: "Ilvermorny",
    house: "?",
    src: images.Erika,
  },
  {
    id: 8,
    name: "Genesis Firth",
    type: "Students",
    school: "Ilvermorny",
    house: "?",
    src: images.Genesis,
  },
  {
    id: 9,
    name: "Harmony",
    type: "Students",
    school: "Ilvermorny",
    house: "?",
    src: images.Harmony,
  },
  {
    id: 10,
    name: "Jeremiah Collier",
    type: "Students",
    school: "Ilvermorny",
    house: "?",
    src: images.Jeremiah,
  },
  {
    id: 11,
    name: "Maddie Gardner",
    type: "Students",
    school: "Ilvermorny",
    house: "?",
    src: images.Maddie,
  },
  {
    id: 12,
    name: "Noah Robinson",
    type: "Students",
    school: "Ilvermorny",
    house: "?",
    src: images.Noah,
  },
  {
    id: 13,
    name: "Olivia Law",
    type: "Students",
    school: "Ilvermorny",
    house: "?",
    src: images.Olivia,
  },
  {
    id: 14,
    name: "Omari Curtis",
    type: "Students",
    school: "Ilvermorny",
    house: "?",
    src: images.Omari,
  },
  {
    id: 15,
    name: "Rome Sanford",
    type: "Students",
    school: "Ilvermorny",
    house: "?",
    src: images.Rome,
  },
  {
    id: 16,
    name: "Seth Claw",
    type: "Students",
    school: "Ilvermorny",
    house: "?",
    src: images.Seth,
  },
  {
    id: 17,
    name: "Shelby MGH",
    type: "Students",
    school: "Ilvermorny",
    house: "?",
    src: images.Shelby,
  },
  {
    id: 18,
    name: "Tony DeLuca",
    type: "Students",
    school: "Ilvermorny",
    house: "?",
    src: images.Tony,
  },
  {
    id: 19,
    name: "Warren Ceredaryk",
    type: "Students",
    school: "Ilvermorny",
    house: "?",
    src: images.Warren,
  },

  {
    id: 20,
    name: "Headmaster Osiris Kisio",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.Kisio,
  },
  {
    id: 21,
    name: "Professor Andrew Siemens",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.Siemens,
  },
  {
    id: 22,
    name: "Professor Korrie Melvin",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.Melvin,
  },
  {
    id: 23,
    name: "Professor Trevor Rogers",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.Rogers,
  },
  {
    id: 24,
    name: "Professor Aciano Nyxi",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.Nyxi,
  },
  {
    id: 25,
    name: "Professor Shantella Jackson",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.Jackson,
  },
  {
    id: 26,
    name: "Professor Amy Loo",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.Loo,
  },
  {
    id: 27,
    name: "Professor Sumaira Bashir",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.Bashir,
  },
  {
    id: 28,
    name: "Professor Calvin Muhoza",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.Muhoza,
  },
  {
    id: 29,
    name: "Professor Sakari Anana",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.Anana,
  },
  {
    id: 30,
    name: "Professor Darby Duncan",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.Duncan,
  },
  {
    id: 31,
    name: "Professor Russell Hart",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.Hart,
  },
  {
    id: 32,
    name: "Professor Noreen Barbuscio",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.Barbuscio,
  },
  {
    id: 33,
    name: "Mr. John Tolman",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.Tolman,
  },
  {
    id: 34,
    name: "Mr. Lloyd McNab",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.McNab,
  },
  {
    id: 35,
    name: "Mr. John Tolman",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.Tolman,
  },
  {
    id: 36,
    name: "Mrs. Wendy Drummond",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.Drummond,
  },
];
