import * as images from "../../Images";

export const ALL_CHARACTERS = [
  // ILVERMORNY STUDENTS (sorted by last name)
  {
    id: 7,
    name: "Erika Baker",
    type: "Student",
    school: "Ilvermorny",
    house: "?",
    src: images.EBaker,
  },
  {
    id: 4,
    name: "Bailey-Anna Balders",
    type: "Student",
    school: "Ilvermorny",
    house: "?",
    src: images.BBalders,
  },
  {
    id: 19,
    name: "Warren Ceredaryk",
    type: "Student",
    school: "Ilvermorny",
    house: "?",
    src: images.WCeredaryk,
  },
  {
    id: 16,
    name: "Seth Claw",
    type: "Student",
    school: "Ilvermorny",
    house: "?",
    src: images.SClaw,
  },
  {
    id: 10,
    name: "Jeremiah Collier",
    type: "Student",
    school: "Ilvermorny",
    house: "?",
    src: images.JCollier,
  },
  {
    id: 14,
    name: "Omari Curtis",
    type: "Student",
    school: "Ilvermorny",
    house: "?",
    src: images.OCurtis,
  },
  {
    id: 18,
    name: "Tony DeLuca",
    type: "Student",
    school: "Ilvermorny",
    house: "?",
    src: images.TDeLuca,
  },
  {
    id: 6,
    name: "Colby Engel",
    type: "Student",
    school: "Ilvermorny",
    house: "?",
    src: images.CEngel,
  },
  {
    id: 8,
    name: "Genesis Firth",
    type: "Student",
    school: "Ilvermorny",
    house: "?",
    src: images.GFirth,
  },
  {
    id: 11,
    name: "Maddie Gardner",
    type: "Student",
    school: "Ilvermorny",
    house: "?",
    src: images.MGardner,
  },
  {
    id: 9,
    name: "Harmony",
    type: "Student",
    school: "Ilvermorny",
    house: "?",
    src: images.Harmony,
  },
  {
    id: 2,
    name: "Anuhea Kelii",
    type: "Student",
    school: "Ilvermorny",
    house: "?",
    src: images.AKelii,
  },
  {
    id: 13,
    name: "Olivia Law",
    type: "Student",
    school: "Ilvermorny",
    house: "?",
    src: images.OLAw,
  },
  {
    id: 17,
    name: "Shelby MGH",
    type: "Student",
    school: "Ilvermorny",
    house: "?",
    src: images.SMGH,
  },
  {
    id: 3,
    name: "Azha Pavan",
    type: "Student",
    school: "Ilvermorny",
    house: "?",
    src: images.APavan,
  },
  {
    id: 1,
    name: "Ava Robinson",
    type: "Student",
    school: "Ilvermorny",
    house: "?",
    src: images.ARobinson,
  },
  {
    id: 12,
    name: "Noah Robinson",
    type: "Student",
    school: "Ilvermorny",
    house: "?",
    src: images.NRobinson,
  },
  {
    id: 15,
    name: "Rome Sanford",
    type: "Student",
    school: "Ilvermorny",
    house: "?",
    src: images.RSanford,
  },
  {
    id: 5,
    name: "Claire Takahashi",
    type: "Student",
    school: "Ilvermorny",
    house: "?",
    src: images.CTakahashi,
  },

  // ILVERMORNY FACULTY (sorted by last name)
  {
    id: 29,
    name: "Professor Sakari Anana",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.SAnana,
  },
  {
    id: 32,
    name: "Professor Noreen Barbuscio",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.NBarbuscio,
  },
  {
    id: 27,
    name: "Professor Sumaira Bashir",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.SBashir,
  },
  {
    id: 36,
    name: "Mrs. Wendy Drummond",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.WDrummond,
  },
  {
    id: 30,
    name: "Professor Darby Duncan",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.DDuncan,
  },
  {
    id: 31,
    name: "Professor Russell Hart",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.RHart,
  },
  {
    id: 25,
    name: "Professor Shantella Jackson",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.SJackson,
  },
  {
    id: 20,
    name: "Headmaster Osiris Kisio",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.OKisio,
  },
  {
    id: 26,
    name: "Professor Amy Loo",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.ALoo,
  },
  {
    id: 34,
    name: "Mr. Lloyd McNab",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.LMcNab,
  },
  {
    id: 22,
    name: "Professor Korrie Melvin",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.KMelvin,
  },
  {
    id: 28,
    name: "Professor Calvin Muhoza",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.CMuhoza,
  },
  {
    id: 24,
    name: "Professor Aciano Nyxi",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.ANyxi,
  },
  {
    id: 23,
    name: "Professor Trevor Rogers",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.TRogers,
  },
  {
    id: 21,
    name: "Professor Andrew Siemens",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.ASiemens,
  },
  {
    id: 33,
    name: "Mr. John Tolman",
    type: "Faculty",
    school: "Ilvermorny",
    house: "?",
    src: images.JTolman,
  },

  // HOGWARTS STUDENTS (sorted by last name)
  {
    id: 88,
    name: "Hamish Bulstrode",
    type: "Student",
    school: "Hogwarts",
    house: "?",
    src: images.HBulstrode,
  },
  {
    id: 87,
    name: "Graham Carrow",
    type: "Student",
    school: "Hogwarts",
    house: "?",
    src: images.GCarrow,
  },
  {
    id: 89,
    name: "Jeanette Fawley",
    type: "Student",
    school: "Hogwarts",
    house: "?",
    src: images.JFawley,
  },
  {
    id: 93,
    name: "Sadhbh Kelly",
    type: "Student",
    school: "Hogwarts",
    house: "?",
    src: images.SKelly,
  },
  {
    id: 94,
    name: "Veronica Khatib",
    type: "Student",
    school: "Hogwarts",
    house: "?",
    src: images.VKhatib,
  },
  {
    id: 92,
    name: "Robbie Macmillan",
    type: "Student",
    school: "Hogwarts",
    house: "?",
    src: images.RMacmillen,
  },
  {
    id: 91,
    name: "Lucius Malfoy",
    type: "Student",
    school: "Hogwarts",
    house: "?",
    src: images.LMalfoy,
  },
  {
    id: 90,
    name: "Josie Pratt",
    type: "Student",
    school: "Hogwarts",
    house: "?",
    src: images.JPratt,
  },
  {
    id: 86,
    name: "Gilda-Gideon Prewett",
    type: "Student",
    school: "Hogwarts",
    house: "?",
    src: images.GPrewett,
  },
  {
    id: 95,
    name: "William Zobell",
    type: "Student",
    school: "Hogwarts",
    house: "?",
    src: images.WZobell,
  },

  // HOGWARTS FACULTY (sorted by last name)
  {
    id: 50,
    name: "Professor Beery",
    type: "Faculty",
    school: "Hogwarts",
    house: "?",
    src: images.Beery,
  },
  {
    id: 51,
    name: "Professor Binns",
    type: "Faculty",
    school: "Hogwarts",
    house: "?",
    src: images.Binns,
  },
  {
    id: 52,
    name: "Professor Cox",
    type: "Faculty",
    school: "Hogwarts",
    house: "?",
    src: images.Cox,
  },
  {
    id: 53,
    name: "Professor Crouch",
    type: "Faculty",
    school: "Hogwarts",
    house: "?",
    src: images.Crouch,
  },
  {
    id: 54,
    name: "Professor Dumbledore",
    type: "Faculty",
    school: "Hogwarts",
    house: "?",
    src: images.Dumbledore,
  },
  {
    id: 47,
    name: "Professor Hagrid",
    type: "Faculty",
    school: "Hogwarts",
    house: "?",
    src: images.Hagrid,
  },
  {
    id: 37,
    name: "Professor Hasegawa",
    type: "Faculty",
    school: "Hogwarts",
    house: "?",
    src: images.Hasegawa,
  },
  {
    id: 48,
    name: "Professor Hooch",
    type: "Faculty",
    school: "Hogwarts",
    house: "?",
    src: images.Hooch,
  },
  {
    id: 38,
    name: "Professor Janvier",
    type: "Faculty",
    school: "Hogwarts",
    house: "?",
    src: images.Janvier,
  },
  {
    id: 39,
    name: "Professor Klein",
    type: "Faculty",
    school: "Hogwarts",
    house: "?",
    src: images.Klein,
  },
  {
    id: 40,
    name: "Professor Lorien",
    type: "Faculty",
    school: "Hogwarts",
    house: "?",
    src: images.Lorien,
  },
  {
    id: 41,
    name: "Professor Mackenzie",
    type: "Faculty",
    school: "Hogwarts",
    house: "?",
    src: images.Mackenzie,
  },
  {
    id: 42,
    name: "Professor McGonagall",
    type: "Faculty",
    school: "Hogwarts",
    house: "?",
    src: images.McGonagall,
  },
  {
    id: 49,
    name: "Professor Pomphrey",
    type: "Faculty",
    school: "Hogwarts",
    house: "?",
    src: images.Pomphrey,
  },
  {
    id: 43,
    name: "Professor Riddle",
    type: "Faculty",
    school: "Hogwarts",
    house: "?",
    src: images.Riddle,
  },
  {
    id: 44,
    name: "Professor Shacklebolt",
    type: "Faculty",
    school: "Hogwarts",
    house: "?",
    src: images.Shacklebolt,
  },
  {
    id: 45,
    name: "Professor Slughorn",
    type: "Faculty",
    school: "Hogwarts",
    house: "?",
    src: images.Slughorn,
  },
  {
    id: 46,
    name: "Professor Tripe",
    type: "Faculty",
    school: "Hogwarts",
    house: "?",
    src: images.Tripe,
  },
];
