export const styles = {};

export const createCharacterGalleryStyles = (theme) => ({
  container: {
    maxWidth: "1400px",
    margin: "0 auto",
    padding: "2rem",
    backgroundColor: theme.background,
    minHeight: "100vh",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "2rem",
    padding: "2rem",
    backgroundColor: theme.surface,
    borderRadius: "1rem",
    border: `2px solid ${theme.border}`,
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
  },
  headerLeft: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
  },
  headerRight: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
  },
  title: {
    fontSize: "2rem",
    fontWeight: "bold",
    color: theme.text,
    margin: 0,
    marginBottom: "0.5rem",
  },
  subtitle: {
    fontSize: "1rem",
    color: theme.textSecondary,
    margin: 0,
  },
  toggleAllButton: {
    padding: "0.75rem 1.5rem",
    backgroundColor: theme.primary,
    color: theme.surface,
    border: "none",
    borderRadius: "0.5rem",
    fontSize: "0.875rem",
    fontWeight: "500",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  statsBar: {
    display: "flex",
    gap: "2rem",
    marginBottom: "2rem",
    padding: "1rem 2rem",
    backgroundColor: theme.surface,
    borderRadius: "0.5rem",
    border: `1px solid ${theme.border}`,
    justifyContent: "center",
  },
  statItem: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    color: theme.text,
    fontSize: "0.875rem",
    fontWeight: "500",
  },
  typeContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "1.5rem",
  },
  typeSection: {
    backgroundColor: theme.surface,
    borderRadius: "1rem",
    border: `1px solid ${theme.border}`,
    overflow: "hidden",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
  },
  typeHeader: {
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "1.5rem 2rem",
    backgroundColor: theme.surface,
    border: "none",
    borderBottom: `1px solid ${theme.border}`,
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  typeHeaderLeft: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
  },
  typeHeaderRight: {
    display: "flex",
    alignItems: "center",
  },
  typeTitle: {
    fontSize: "1.5rem",
    fontWeight: "600",
    color: theme.text,
    margin: 0,
  },
  characterCount: {
    fontSize: "0.875rem",
    color: theme.textSecondary,
    backgroundColor: theme.background,
    padding: "0.25rem 0.75rem",
    borderRadius: "9999px",
    border: `1px solid ${theme.border}`,
  },
  charactersGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(350px, 1fr))",
    gap: "1.5rem",
    padding: "2rem",
  },
  characterCard: {
    backgroundColor: theme.surface,
    borderRadius: "1rem",
    border: `1px solid ${theme.border}`,
    overflow: "hidden",
    transition: "all 0.3s ease",
    cursor: "pointer",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
  },
  characterCardHover: {
    transform: "translateY(-4px)",
    boxShadow: "0 8px 16px rgba(0, 0, 0, 0.15)",
    borderColor: theme.primary,
  },
  imageContainer: {
    position: "relative",
    height: "300px",
    overflow: "hidden",
  },
  characterImage: {
    width: "100%",
    height: "300px",
    objectFit: "contain",
    transition: "transform 0.3s ease",
  },
  imagePlaceholder: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.background,
    border: `2px dashed ${theme.border}`,
  },
  placeholderText: {
    marginTop: "0.5rem",
    color: theme.textSecondary,
    fontSize: "0.875rem",
  },
  statusBadge: {
    position: "absolute",
    top: "1rem",
    right: "1rem",
    padding: "0.375rem 0.75rem",
    borderRadius: "9999px",
    fontSize: "0.75rem",
    fontWeight: "600",
    border: "1px solid",
    backdropFilter: "blur(8px)",
  },
  houseBadge: {
    position: "absolute",
    top: "1rem",
    left: "1rem",
    padding: "0.375rem 0.75rem",
    borderRadius: "9999px",
    fontSize: "0.75rem",
    fontWeight: "600",
    border: "1px solid",
    backdropFilter: "blur(8px)",
  },
  characterInfo: {
    padding: "1.5rem",
  },
  characterName: {
    fontSize: "1.375rem",
    fontWeight: "bold",
    color: theme.text,
    margin: 0,
    marginBottom: "0.75rem",
  },
  characterDescription: {
    fontSize: "0.875rem",
    color: theme.textSecondary,
    lineHeight: "1.5",
    margin: 0,
    marginBottom: "1rem",
  },
  specialtiesContainer: {
    marginTop: "1rem",
  },
  specialtiesHeader: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    marginBottom: "0.75rem",
  },
  specialtiesLabel: {
    fontSize: "0.875rem",
    fontWeight: "500",
    color: theme.text,
  },
  specialtiesList: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.5rem",
  },
  specialtyTag: {
    padding: "0.25rem 0.75rem",
    borderRadius: "9999px",
    fontSize: "0.75rem",
    fontWeight: "500",
    border: `1px solid currentColor`,
  },
});
export default styles;
