// ==================== APP STYLES ====================
export const createAppStyles = (theme) => ({
  appContainer: {
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    backgroundColor: theme.background,
    color: theme.text,
    minHeight: "100vh",
    transition: "background-color 0.3s ease, color 0.3s ease",
  },
  appHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "1rem",
    backgroundColor: theme.headerBackground || theme.surface,
    borderBottom: `1px solid ${theme.border}`,
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
  },
  tabNavigation: {
    display: "flex",
    gap: "0.5rem",
  },
  tabButton: {
    padding: "0.5rem 1rem",
    border: `1px solid ${theme.border}`,
    borderRadius: "0.25rem",
    backgroundColor: theme.surface,
    color: theme.text,
    cursor: "pointer",
    transition: "all 0.2s",
    fontWeight: "500",
  },
  tabButtonActive: {
    backgroundColor: theme.primary,
    color: theme.surface,
    borderColor: theme.primary,
  },
  tabButtonHover: {
    backgroundColor: theme.background,
    borderColor: theme.primary,
  },
  authSection: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
  },
  userInfo: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    position: "relative",
  },
  userAvatar: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    border: `2px solid ${theme.primary}`,
  },
  username: {
    fontWeight: "500",
    color: theme.text,
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  editButton: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "2px",
    borderRadius: "3px",
    color: theme.textSecondary,
    transition: "color 0.2s",
  },
  editButtonHover: {
    color: theme.primary,
    backgroundColor: theme.background,
  },
  usernameEditor: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  usernameInput: {
    padding: "4px 8px",
    border: `1px solid ${theme.border}`,
    borderRadius: "4px",
    fontSize: "14px",
    width: "120px",
    backgroundColor: theme.surface,
    color: theme.text,
  },
  saveButton: {
    background: theme.success || "#10B981",
    color: "white",
    border: "none",
    borderRadius: "3px",
    padding: "4px 6px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
  },
  cancelButton: {
    background: theme.error || "#EF4444",
    color: "white",
    border: "none",
    borderRadius: "3px",
    padding: "4px 6px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
  },
  themeButton: {
    padding: "0.5rem",
    backgroundColor: theme.surface,
    border: `1px solid ${theme.border}`,
    borderRadius: "0.25rem",
    cursor: "pointer",
    transition: "all 0.2s",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  themeButtonHover: {
    backgroundColor: theme.background,
    borderColor: theme.primary,
  },
  tabContent: {
    flex: 1,
    backgroundColor: theme.background,
  },
  homePage: {
    padding: "2rem",
    backgroundColor: theme.background,
  },
  featureGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: "1.5rem",
    marginBottom: "2rem",
  },
  featureCard: {
    padding: "1.5rem",
    border: `1px solid ${theme.border}`,
    borderRadius: "0.5rem",
    backgroundColor: theme.cardBackground || theme.surface,
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
    color: theme.text,
    cursor: "pointer",
    transition: "all 0.3s ease",
    position: "relative",
  },
  loadingSpinner: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100vh",
    fontSize: "1.2rem",
    color: theme.textSecondary,
    backgroundColor: theme.background,
  },
});

// ==================== CHARACTER SHEET STYLES ====================
const createCharacterSheetStyles = (theme) => ({
  container: {
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "20px",
    backgroundColor: theme.background,
    minHeight: "100vh",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  headerCard: {
    backgroundColor: theme.surface,
    borderRadius: "12px",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    marginBottom: "24px",
    padding: "24px",
    border: `2px solid ${theme.border}`,
  },
  headerFlex: {
    display: "flex",
    alignItems: "flex-start",
    gap: "20px",
    marginBottom: "20px",
  },
  avatar: {
    width: "60px",
    height: "60px",
    backgroundColor: theme.primary + "20",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: `3px solid ${theme.primary}`,
  },
  characterName: {
    fontSize: "28px",
    fontWeight: "bold",
    color: theme.text,
    margin: "0 0 12px 0",
  },
  infoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "8px",
  },
  infoItem: {
    fontSize: "14px",
    color: theme.text,
  },
  label: {
    fontWeight: "600",
    color: theme.primary,
  },
  combatStats: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "16px",
    marginTop: "20px",
  },
  statCard: {
    backgroundColor: theme.background,
    border: `2px solid ${theme.border}`,
    borderRadius: "12px",
    padding: "16px",
    textAlign: "center",
    transition: "all 0.2s ease",
    cursor: "pointer",
  },
  statCardRed: {
    borderColor: "#ef4444",
  },
  statCardBlue: {
    borderColor: "#3b82f6",
  },
  statCardGreen: {
    borderColor: "#10b981",
  },
  statCardGreenHover: {
    // eslint-disable-next-line
    backgroundColor: "#10b981" + "10",
    transform: "translateY(-2px)",
    boxShadow: "0 4px 12px rgba(16, 185, 129, 0.2)",
  },
  statValue: {
    fontSize: "24px",
    fontWeight: "bold",
    marginBottom: "4px",
  },
  statValueRed: {
    color: "#ef4444",
  },
  statValueBlue: {
    color: "#3b82f6",
  },
  statValueGreen: {
    color: "#10b981",
  },
  statLabel: {
    fontSize: "12px",
    fontWeight: "500",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  statLabelRed: {
    color: "#ef4444",
  },
  statLabelBlue: {
    color: "#3b82f6",
  },
  statLabelGreen: {
    color: "#10b981",
  },
  instructionsCard: {
    backgroundColor: theme.surface,
    borderRadius: "12px",
    padding: "20px",
    margin: "24px 0",
    border: `2px solid ${theme.border}`,
  },
  instructionsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))",
    gap: "12px",
    marginBottom: "16px",
  },
  instructionItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "14px",
    color: theme.text,
  },
  warning: {
    backgroundColor: "#fef3c7",
    border: "1px solid #f59e0b",
    color: "#92400e",
    padding: "12px",
    borderRadius: "8px",
    fontSize: "14px",
    textAlign: "center",
  },
  errorContainer: {
    textAlign: "center",
    padding: "40px",
    backgroundColor: theme.surface,
    borderRadius: "12px",
    border: `2px solid ${theme.border}`,
    margin: "20px",
  },
  loadingContainer: {
    textAlign: "center",
    padding: "40px",
    color: theme.textSecondary,
  },
});

// ==================== ABILITY SCORES STYLES ====================
export const createAbilityScoresStyles = (theme) => ({
  abilityCard: {
    backgroundColor: theme.surface,
    borderRadius: "12px",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    marginBottom: "24px",
    padding: "20px",
    border: `2px solid ${theme.border}`,
  },
  abilityTitle: {
    fontSize: "20px",
    fontWeight: "bold",
    color: theme.text,
    marginBottom: "16px",
    textAlign: "center",
  },
  abilityGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(120px, 1fr))",
    gap: "12px",
  },
  abilityItem: {
    backgroundColor: theme.background,
    border: `2px solid ${theme.border}`,
    borderRadius: "8px",
    padding: "12px",
    textAlign: "center",
    transition: "all 0.2s ease",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "4px",
  },
  abilityName: {
    fontSize: "12px",
    fontWeight: "500",
    color: theme.textSecondary,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  abilityModifier: {
    fontSize: "16px",
    fontWeight: "bold",
    color: theme.primary,
  },
  abilityScore: {
    fontSize: "20px",
    fontWeight: "bold",
    color: theme.text,
  },
});

// ==================== SKILLS STYLES ====================
export const createSkillsStyles = (theme) => ({
  skillsCard: {
    backgroundColor: theme.surface,
    borderRadius: "12px",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    marginBottom: "24px",
    border: `2px solid ${theme.border}`,
    overflow: "hidden",
  },
  skillsTitle: {
    fontSize: "20px",
    fontWeight: "bold",
    color: theme.text,
    margin: "0",
    padding: "20px 20px 0 20px",
    textAlign: "center",
  },
  skillsTable: {
    width: "100%",
    borderCollapse: "collapse",
  },
  skillsHeaderRow: {
    backgroundColor: theme.background,
  },
  skillsHeaderCell: {
    padding: "12px 16px",
    textAlign: "left",
    fontSize: "12px",
    fontWeight: "600",
    color: theme.textSecondary,
    textTransform: "uppercase",
    borderBottom: `2px solid ${theme.border}`,
    cursor: "pointer",
    transition: "all 0.2s ease",
    userSelect: "none",
  },
  skillsHeaderCellLast: {
    padding: "12px 16px",
    textAlign: "center",
    fontSize: "12px",
    fontWeight: "600",
    color: theme.textSecondary,
    textTransform: "uppercase",
    borderBottom: `2px solid ${theme.border}`,
    cursor: "pointer",
    transition: "all 0.2s ease",
    userSelect: "none",
  },
  skillsHeaderCellHover: {
    backgroundColor: theme.primary + "10",
    color: theme.primary,
  },
  skillsHeaderCellActive: {
    backgroundColor: theme.primary + "20",
    color: theme.primary,
  },
  sortableHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "4px",
  },
  skillRow: {
    borderBottom: `1px solid ${theme.border}`,
    transition: "all 0.2s ease",
  },
  skillRowHover: {
    backgroundColor: theme.background,
  },
  skillCell: {
    padding: "12px 16px",
    fontSize: "14px",
    color: theme.text,
  },
  skillCellLast: {
    padding: "12px 16px",
    fontSize: "14px",
    color: theme.text,
    textAlign: "center",
  },
  proficiencyCircle: {
    width: "16px",
    height: "16px",
    borderRadius: "50%",
    border: `2px solid ${theme.textSecondary}`,
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  proficiencyCircleFilled: {
    backgroundColor: theme.text,
    borderColor: theme.text,
  },
  abilityMod: {
    fontSize: "12px",
    color: theme.textSecondary,
    fontWeight: "500",
  },
  skillNameButton: {
    background: "none",
    border: "none",
    color: theme.text,
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "500",
    padding: "0",
    textAlign: "left",
    transition: "color 0.2s ease",
  },
  skillNameButtonProficient: {
    fontWeight: "600",
    color: theme.primary,
  },
  skillNameButtonHover: {
    color: theme.primary,
  },
  bonusValue: {
    fontSize: "14px",
    fontWeight: "600",
    color: theme.text,
  },
});

// ==================== CHARACTER CREATION STYLES ====================
// Complete createCharacterCreationStyles function with all missing styles
export const createCharacterCreationStyles = (theme) => ({
  container: {
    padding: "20px",
    maxWidth: "1200px",
    margin: "0 auto",
    backgroundColor: theme.background,
    minHeight: "100vh",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  header: {
    backgroundColor: theme.surface,
    padding: "25px",
    borderRadius: "12px",
    border: `2px solid ${theme.border}`,
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    marginBottom: "20px",
  },
  title: {
    margin: 0,
    fontSize: "2.5rem",
    color: theme.text,
    textShadow: "2px 2px 4px rgba(0,0,0,0.1)",
  },
  userAvatarContainer: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    marginTop: "12px",
  },
  userAvatar: {
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    border: `2px solid ${theme.primary}`,
  },
  welcomeText: {
    fontSize: "18px",
    color: theme.textSecondary,
    fontWeight: "500",
  },
  authContainer: {
    textAlign: "center",
    padding: "40px",
    backgroundColor: theme.surface,
    borderRadius: "12px",
    border: `2px solid ${theme.border}`,
  },
  authHeader: {
    color: theme.text,
    marginBottom: "16px",
  },
  authText: {
    color: theme.textSecondary,
  },
  errorContainer: {
    backgroundColor: "#fee2e2",
    border: "1px solid #fecaca",
    color: "#dc2626",
    padding: "12px",
    borderRadius: "8px",
    margin: "16px 0",
    fontSize: "14px",
  },
  tabContainer: {
    display: "flex",
    gap: "8px",
    marginBottom: "20px",
    borderBottom: `2px solid ${theme.border}`,
  },
  tab: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 20px",
    backgroundColor: theme.background,
    border: "none",
    borderRadius: "8px 8px 0 0",
    fontSize: "16px",
    fontWeight: "500",
    color: theme.textSecondary,
    cursor: "pointer",
    transition: "all 0.2s ease",
    marginBottom: "-2px",
  },
  activeTab: {
    backgroundColor: theme.surface,
    color: theme.text,
    borderBottom: `2px solid ${theme.primary}`,
  },
  tabContent: {
    backgroundColor: theme.background,
  },
  panel: {
    backgroundColor: theme.surface,
    padding: "25px",
    borderRadius: "12px",
    border: `2px solid ${theme.border}`,
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
  },
  sectionHeader: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    fontSize: "24px",
    fontWeight: "bold",
    color: theme.text,
    marginBottom: "20px",
    borderBottom: `2px solid ${theme.border}`,
    paddingBottom: "12px",
  },
  fieldContainer: {
    marginBottom: "20px",
  },
  label: {
    display: "block",
    fontWeight: "bold",
    marginBottom: "5px",
    color: theme.text,
    fontSize: "16px",
  },
  input: {
    width: "100%",
    padding: "10px",
    borderRadius: "6px",
    border: `2px solid ${theme.border}`,
    fontSize: "16px",
    backgroundColor: theme.surface,
    color: theme.text,
    transition: "border-color 0.2s ease",
  },
  select: {
    width: "100%",
    padding: "10px",
    borderRadius: "6px",
    border: `2px solid ${theme.border}`,
    fontSize: "16px",
    backgroundColor: theme.surface,
    color: theme.text,
    transition: "border-color 0.2s ease",
  },
  helpText: {
    fontSize: "14px",
    color: theme.textSecondary,
    marginTop: "8px",
    fontStyle: "italic",
  },
  button: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "10px 16px",
    border: "none",
    borderRadius: "6px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
    color: "white",
  },
  saveButton: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "16px 32px",
    border: "none",
    borderRadius: "8px",
    fontSize: "18px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
    width: "100%",
    justifyContent: "center",
    marginTop: "20px",
    color: "white",
  },
  newCharacterButton: {
    backgroundColor: theme.success || "#10B981",
    color: "white",
    border: "none",
    padding: "12px 24px",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    transition: "all 0.2s ease",
  },
  createNewButtonInSaved: {
    backgroundColor: theme.primary,
    color: "white",
    border: "none",
    padding: "12px 20px",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    transition: "all 0.2s ease",
  },
  savedCharactersHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "20px",
  },
  charactersContainer: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(350px, 1fr))",
    gap: "20px",
  },
  characterCard: {
    backgroundColor: theme.background,
    border: `2px solid ${theme.border}`,
    borderRadius: "12px",
    padding: "20px",
    transition: "all 0.2s ease",
  },
  characterHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "12px",
  },
  characterName: {
    fontSize: "20px",
    fontWeight: "bold",
    alignSelf: "center",
    color: theme.text,
    marginBottom: "8px",
  },
  characterInfo: {
    display: "flex",
    justifyContent: "center",
  },
  characterDetails: {
    fontSize: "14px",
    color: theme.text,
    lineHeight: "1.5",
  },
  characterActions: {
    display: "flex",
    gap: "8px",
  },
  actionButton: {
    padding: "8px",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    color: "white",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.2s ease",
  },
  heritage: {
    color: theme.primary,
    fontWeight: "500",
    marginBottom: "4px",
  },
  feats: {
    fontSize: "13px",
    color: theme.textSecondary,
    marginTop: "8px",
    paddingTop: "8px",
    borderTop: `1px solid ${theme.border}`,
  },
  skills: {
    fontSize: "13px",
    color: theme.textSecondary,
    marginTop: "8px",
  },
  emptyCharacters: {
    textAlign: "center",
    padding: "40px",
    color: theme.textSecondary,
    fontSize: "18px",
    backgroundColor: theme.background,
    borderRadius: "12px",
    border: `2px dashed ${theme.border}`,
  },
  characterLimitWarning: {
    backgroundColor: "#fef3c7",
    border: "1px solid #f59e0b",
    color: "#92400e",
    padding: "16px",
    borderRadius: "8px",
    textAlign: "center",
    fontSize: "16px",
    fontWeight: "600",
    marginTop: "20px",
  },
  characterLimitWarningText: {
    fontSize: "14px",
    fontWeight: "400",
    marginTop: "8px",
  },

  // === SKILLS SECTION STYLES ===
  skillsHeader: {
    fontSize: "20px",
    fontWeight: "bold",
    color: theme.text,
    marginBottom: "8px",
    margin: 0,
  },
  skillsPlaceholder: {
    padding: "20px",
    backgroundColor: theme.background,
    border: `2px dashed ${theme.border}`,
    borderRadius: "8px",
    textAlign: "center",
    color: theme.textSecondary,
    fontSize: "14px",
    fontStyle: "italic",
  },
  skillsContainer: {
    backgroundColor: theme.background,
    border: `2px solid ${theme.border}`,
    borderRadius: "8px",
    padding: "16px",
  },
  skillsSubheader: {
    fontSize: "16px",
    fontWeight: "600",
    color: theme.text,
    marginBottom: "12px",
    margin: "0 0 12px 0",
  },
  skillsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "12px",
    marginBottom: "12px",
  },
  skillOptionBase: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px",
    borderRadius: "8px",
    transition: "all 0.2s ease",
  },
  skillCheckbox: {
    width: "16px",
    height: "16px",
    accentColor: theme.success,
  },
  skillsComplete: {
    backgroundColor: theme.success + "20",
    color: theme.success,
    padding: "12px",
    borderRadius: "6px",
    textAlign: "center",
    fontSize: "14px",
    fontWeight: "600",
    marginTop: "12px",
  },

  // === LEVEL 1 CHOICE STYLES ===
  level1ChoiceContainer: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
    marginTop: "12px",
  },
  level1ChoiceLabel: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "16px",
    backgroundColor: theme.background,
    border: `2px solid ${theme.border}`,
    borderRadius: "12px",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  level1ChoiceLabelSelected: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "16px",
    backgroundColor: theme.primary + "20",
    border: `2px solid ${theme.primary}`,
    borderRadius: "12px",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  level1ChoiceRadio: {
    width: "18px",
    height: "18px",
    accentColor: theme.primary,
  },
  level1ChoiceText: {
    fontSize: "16px",
    fontWeight: "600",
    color: theme.text,
  },
  level1ChoiceTextSelected: {
    fontSize: "16px",
    fontWeight: "600",
    color: theme.primary,
  },

  // === LEVEL AND HP GRID STYLES ===
  levelHpGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    gap: "16px",
    alignItems: "end",
    marginBottom: "20px",
  },
  levelContainer: {
    display: "flex",
    flexDirection: "column",
  },
  hpFieldContainer: {
    display: "flex",
    flexDirection: "column",
  },
  hpValueContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "44px",
  },
  hpDisplay: {
    fontSize: "20px",
    fontWeight: "bold",
    color: theme.text,
    textAlign: "center",
    padding: "10px",
    backgroundColor: theme.background,
    border: `2px solid ${theme.border}`,
    borderRadius: "6px",
    minWidth: "60px",
  },
  hpRollDisplay: {
    fontSize: "20px",
    fontWeight: "bold",
    color: "#10B981",
    textAlign: "center",
    padding: "10px",
    // eslint-disable-next-line
    backgroundColor: "#10B981" + "20",
    border: "2px solid #10B981",
    borderRadius: "6px",
    minWidth: "60px",
  },
  hpManualInput: {
    textAlign: "center",
    fontSize: "18px",
    fontWeight: "bold",
    width: "100%",
    padding: "10px",
    border: `2px solid ${theme.primary}`,
    borderRadius: "6px",
    backgroundColor: theme.surface,
    color: theme.text,
  },
  hpControlsContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
    minHeight: "44px",
  },
  hpControlsInline: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    justifyContent: "center",
  },
  hpToggle: {
    position: "relative",
    width: "46px",
    height: "24px",
    borderRadius: "12px",
    border: "2px solid",
    cursor: "pointer",
    transition: "all 0.3s ease",
  },
  hpToggleKnob: {
    position: "absolute",
    top: "2px",
    width: "18px",
    height: "18px",
    backgroundColor: "white",
    borderRadius: "50%",
    transition: "left 0.3s ease",
    boxShadow: "0 2px 4px rgba(0,0,0,0.2)",
  },

  // === MAGIC MODIFIERS STYLES ===
  magicModifiersGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "16px",
    marginTop: "12px",
  },
  magicModifierItem: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  magicModifierLabel: {
    fontSize: "14px",
    fontWeight: "600",
    color: theme.text,
  },
  magicModifierInput: {
    textAlign: "center",
    fontSize: "16px",
    fontWeight: "bold",
    width: "100%",
    padding: "8px",
    border: `2px solid ${theme.border}`,
    borderRadius: "6px",
    backgroundColor: theme.surface,
    color: theme.text,
    transition: "border-color 0.2s ease",
  },
});

// ==================== ABILITY SCORE PICKER STYLES ====================
export const createAbilityScorePickerStyles = (theme) => ({
  fieldContainer: {
    marginBottom: "20px",
  },
  abilityScoresHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "12px",
  },
  abilityScoresTitle: {
    fontSize: "20px",
    fontWeight: "bold",
    color: theme.text,
    margin: 0,
  },
  buttonGroup: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
  },
  button: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "10px 16px",
    border: "none",
    borderRadius: "6px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
    color: "white",
  },
  helpText: {
    fontSize: "14px",
    color: theme.textSecondary,
    marginBottom: "12px",
    fontStyle: "italic",
  },
  availableStats: {
    backgroundColor: theme.background,
    border: `2px solid ${theme.border}`,
    borderRadius: "8px",
    padding: "16px",
    marginBottom: "16px",
  },
  availableStatsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "12px",
  },
  availableStatsLabel: {
    fontSize: "14px",
    fontWeight: "600",
    color: theme.text,
  },
  availableStatsTotal: {
    fontSize: "14px",
    fontWeight: "600",
    color: theme.textSecondary,
  },
  completeIndicator: {
    color: theme.success || "#10B981",
    marginLeft: "8px",
  },
  statsContainer: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
  },
  statBadge: {
    backgroundColor: theme.primary + "20",
    color: theme.primary,
    padding: "6px 12px",
    borderRadius: "20px",
    fontSize: "14px",
    fontWeight: "600",
    border: `1px solid ${theme.primary}`,
  },
  allAssignedText: {
    color: theme.success || "#10B981",
    fontWeight: "600",
    fontSize: "14px",
  },
  abilityGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
    gap: "16px",
  },
  abilityCard: {
    backgroundColor: theme.surface,
    border: `2px solid ${theme.border}`,
    borderRadius: "12px",
    padding: "16px",
    textAlign: "center",
    transition: "all 0.2s ease",
  },
  abilityName: {
    fontSize: "14px",
    fontWeight: "600",
    color: theme.text,
    marginBottom: "8px",
    textTransform: "capitalize",
  },
  abilityModifier: {
    fontSize: "18px",
    fontWeight: "bold",
    color: theme.primary,
    marginBottom: "8px",
  },
  abilityModifierEmpty: {
    fontSize: "18px",
    fontWeight: "bold",
    color: theme.textSecondary,
    marginBottom: "8px",
  },
  abilityScoreContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
  },
  abilityScore: {
    fontSize: "24px",
    fontWeight: "bold",
    color: theme.text,
  },
  input: {
    textAlign: "center",
    fontSize: "18px",
    fontWeight: "bold",
    width: "60px",
    padding: "4px",
    border: `2px solid ${theme.border}`,
    borderRadius: "6px",
    backgroundColor: theme.surface,
    color: theme.text,
  },
  assignSelect: {
    padding: "8px 12px",
    border: `2px solid ${theme.border}`,
    borderRadius: "6px",
    backgroundColor: theme.surface,
    color: theme.text,
    fontSize: "14px",
    width: "100%",
  },
  trashButton: {
    backgroundColor: "#ef4444",
    color: "white",
    border: "none",
    borderRadius: "4px",
    padding: "4px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.2s ease",
  },
});

// ==================== SPELLBOOK STYLES ====================
export const createSpellBookStyles = (theme) => ({
  searchInputContainer: {
    position: "relative",
    display: "flex",
    alignItems: "center",
  },
  searchIcon: {
    position: "absolute",
    left: "12px",
    zIndex: 1,
  },
  searchInput: {
    width: "100%",
    padding: "12px 12px 12px 44px",
    paddingRight: "44px",
    border: `2px solid ${theme.border}`,
    borderRadius: "8px",
    fontSize: "16px",
    backgroundColor: theme.background,
    color: theme.text,
    outline: "none",
    transition: "border-color 0.2s ease",
  },
  searchClearButton: {
    position: "absolute",
    right: "12px",
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "4px",
    borderRadius: "4px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "background-color 0.2s ease",
  },
  searchResultsHint: {
    color: theme.textSecondary,
    opacity: 0.8,
  },
  noResultsContainer: {
    textAlign: "center",
    padding: "60px 20px",
    backgroundColor: theme.surface,
    borderRadius: "12px",
    border: `2px solid ${theme.border}`,
    margin: "20px",
  },
  noResultsIcon: {
    fontSize: "48px",
    marginBottom: "16px",
  },
  noResultsTitle: {
    fontSize: "24px",
    fontWeight: "600",
    color: theme.text,
    marginBottom: "12px",
  },
  noResultsMessage: {
    fontSize: "16px",
    color: theme.textSecondary,
    marginBottom: "20px",
    lineHeight: "1.5",
  },

  subjectCard: {
    backgroundColor: theme.surface,
    borderRadius: "16px",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    border: `2px solid ${theme.border}`,
    overflow: "hidden",
    transition: "all 0.2s ease",
  },
  subjectHeader: {
    padding: "20px",
    borderBottom: `2px solid ${theme.border}`,
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  subjectTitleContainer: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    marginBottom: "8px",
  },
  subjectTitle: {
    fontSize: "24px",
    fontWeight: "bold",
    margin: 0,
    color: theme.text,
  },
  subjectDescription: {
    fontSize: "14px",
    color: theme.textSecondary,
    marginBottom: "16px",
  },
  subjectStats: {
    display: "flex",
    gap: "24px",
  },
  subjectStatItem: {
    textAlign: "center",
  },
  subjectStatNumber: {
    display: "block",
    fontSize: "24px",
    fontWeight: "bold",
  },
  subjectStatLabel: {
    display: "block",
    fontSize: "12px",
    color: theme.textSecondary,
    textTransform: "uppercase",
    marginTop: "4px",
  },
  subjectContent: {
    backgroundColor: theme.background,
  },
  sectionContainer: {
    margin: "0",
  },
  sectionButton: {
    width: "100%",
    padding: "16px 20px",
    border: `2px solid transparent`,
    borderRadius: "0",
    cursor: "pointer",
    transition: "all 0.2s ease",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: "16px",
    fontWeight: "600",
  },
  sectionButtonHover: {
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.1)",
  },
  sectionLeft: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  sectionRight: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  sectionProgress: {
    width: "100px",
    height: "6px",
    backgroundColor: "rgba(255, 255, 255, 0.3)",
    borderRadius: "3px",
    overflow: "hidden",
  },
  sectionProgressFill: {
    height: "100%",
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    borderRadius: "3px",
    transition: "width 0.3s ease",
  },
  table: {
    width: "100%",
    backgroundColor: theme.surface,
    borderCollapse: "collapse",
  },
  tableHeader: {
    backgroundColor: theme.background,
  },
  tableHeaderCell: {
    padding: "12px 16px",
    textAlign: "left",
    fontSize: "12px",
    fontWeight: "600",
    color: theme.textSecondary,
    textTransform: "uppercase",
    borderBottom: `2px solid ${theme.border}`,
  },
  tableHeaderCellCenter: {
    padding: "12px 16px",
    textAlign: "center",
    fontSize: "12px",
    fontWeight: "600",
    color: theme.textSecondary,
    textTransform: "uppercase",
    borderBottom: `2px solid ${theme.border}`,
  },
  tableRow: {
    borderBottom: `1px solid ${theme.border}`,
    transition: "all 0.2s ease",
  },
  tableRowMastered: {
    backgroundColor: "#f0fdf4",
  },
  tableRowHover: {
    backgroundColor: theme.background,
  },
  tableCell: {
    padding: "12px 16px",
    fontSize: "14px",
    color: theme.text,
    verticalAlign: "top",
  },
  spellNameContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  spellName: {
    fontSize: "14px",
    fontWeight: "500",
    color: theme.text,
  },
  spellNameMastered: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#059669",
  },
  masteredBadge: {
    fontSize: "10px",
    fontWeight: "600",
    padding: "2px 6px",
    borderRadius: "10px",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    alignSelf: "flex-start",
  },
  attemptsContainer: {
    display: "flex",
    gap: "12px",
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    fontSize: "12px",
    color: theme.textSecondary,
  },
  checkbox: {
    width: "16px",
    height: "16px",
  },
  checkboxText: {
    fontSize: "12px",
    fontWeight: "500",
  },
  attemptButton: {
    backgroundColor: "#3b82f6",
    color: "white",
    border: "none",
    borderRadius: "6px",
    padding: "6px 12px",
    fontSize: "12px",
    fontWeight: "500",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "4px",
    transition: "all 0.2s ease",
  },
  attemptButtonDisabled: {
    backgroundColor: "#9ca3af",
    cursor: "not-allowed",
  },
  searchContainer: {
    margin: "0 20px 24px 20px",
    padding: "20px",
    backgroundColor: theme.surface,
    borderRadius: "12px",
    border: `2px solid ${theme.border}`,
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
  },
  searchResults: {
    fontSize: "14px",
    color: theme.textSecondary,
    fontStyle: "italic",
  },
  searchSuggestions: {
    textAlign: "left",
    display: "inline-block",
    margin: "0 0 24px 0",
    padding: "0 0 0 20px",
    listStyle: "disc",
    color: theme.textSecondary,
  },

  clearSearchButton: {
    padding: "12px 24px",
    backgroundColor: theme.primary,
    color: theme.surface,
    border: "none",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "500",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  statsContainer: {
    display: "flex",
    justifyContent: "center",
    gap: "24px",
    margin: "0 20px 24px 20px",
    padding: "16px",
    backgroundColor: theme.surface,
    borderRadius: "12px",
    border: `2px solid ${theme.border}`,
    flexWrap: "wrap",
  },

  statItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "14px",
    fontWeight: "500",
    color: theme.text,
  },

  statDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
  },

  // Subjects Grid
  subjectsGrid: {
    display: "grid",
    gap: "20px",
    margin: "0 20px",
  },
});

// ==================== CHARACTER SELECTOR STYLES ====================
// ==================== DEFENSIVE CHARACTER SELECTOR STYLES ====================
// Replace your existing createCharacterSelectorStyles function with this one

export const searchStyles = (theme) => ({
  // Search Container
  searchContainer: {
    margin: "0 20px 24px 20px",
    padding: "20px",
    backgroundColor: theme.surface,
    borderRadius: "12px",
    border: `2px solid ${theme.border}`,
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
  },

  // Search Input Container
  searchInputContainer: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    marginBottom: "8px",
  },

  // Search Icon
  searchIcon: {
    position: "absolute",
    left: "12px",
    zIndex: 1,
    pointerEvents: "none",
  },

  // Search Input
  searchInput: {
    width: "100%",
    padding: "12px 12px 12px 44px",
    paddingRight: "44px",
    fontSize: "16px",
    border: `2px solid ${theme.border}`,
    borderRadius: "8px",
    backgroundColor: theme.background,
    color: theme.text,
    outline: "none",
    transition: "all 0.2s ease",
    fontFamily: "inherit",
  },

  // Search Clear Button
  searchClearButton: {
    position: "absolute",
    right: "8px",
    padding: "4px",
    border: "none",
    background: "none",
    cursor: "pointer",
    borderRadius: "4px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "background-color 0.2s ease",
  },

  // Search Results Info
  searchResults: {
    fontSize: "14px",
    color: theme.textSecondary,
    fontStyle: "italic",
  },

  // Search Results Hint
  searchResultsHint: {
    color: theme.textSecondary,
    opacity: 0.8,
  },

  // No Results Container
  noResultsContainer: {
    textAlign: "center",
    padding: "60px 20px",
    margin: "20px",
    backgroundColor: theme.surface,
    borderRadius: "12px",
    border: `2px solid ${theme.border}`,
  },

  // No Results Icon
  noResultsIcon: {
    fontSize: "48px",
    marginBottom: "16px",
    opacity: 0.5,
  },

  // No Results Title
  noResultsTitle: {
    fontSize: "24px",
    fontWeight: "600",
    color: theme.text,
    marginBottom: "12px",
    margin: "0 0 12px 0",
  },

  // No Results Message
  noResultsMessage: {
    fontSize: "16px",
    color: theme.textSecondary,
    marginBottom: "20px",
    lineHeight: "1.5",
  },

  // Search Suggestions List
  searchSuggestions: {
    textAlign: "left",
    display: "inline-block",
    margin: "0 0 24px 0",
    padding: "0",
    listStyle: "none",
  },

  // Clear Search Button
  clearSearchButton: {
    padding: "12px 24px",
    backgroundColor: theme.primary,
    color: theme.surface,
    border: "none",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "500",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
});

export const createCharacterSelectorStyles = (theme) => {
  // Create a fallback theme if theme is undefined
  const safeTheme = theme || {
    surface: "#ffffff",
    background: "#f8fafc",
    text: "#1f2937",
    textSecondary: "#6b7280",
    primary: "#6366f1",
    secondary: "#8b5cf6",
    success: "#10b981",
    warning: "#f59e0b",
    error: "#ef4444",
    border: "#e5e7eb",
  };

  return {
    container: {
      padding: "20px",
      backgroundColor: safeTheme.surface,
      borderBottom: `2px solid ${safeTheme.border}`,
      marginBottom: "20px",
      boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
    },
    innerContainer: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      gap: "20px",
      maxWidth: "1200px",
      margin: "0 auto",
    },
    selectorRow: {
      display: "flex",
      alignItems: "center",
      gap: "15px",
      flexWrap: "wrap",
    },
    label: {
      fontSize: "16px",
      fontWeight: "600",
      color: safeTheme.text,
    },
    select: {
      padding: "8px 12px",
      fontSize: "16px",
      border: `2px solid ${safeTheme.border}`,
      borderRadius: "8px",
      backgroundColor: safeTheme.surface,
      color: safeTheme.text,
      minWidth: "200px",
    },
    singleCharacterDisplay: {
      padding: "8px 12px",
      fontSize: "16px",
      backgroundColor: safeTheme.primary + "20",
      border: `2px solid ${safeTheme.primary}`,
      borderRadius: "8px",
      color: safeTheme.text,
      fontWeight: "500",
      minWidth: "200px",
      textAlign: "center",
    },
    noCharactersDisplay: {
      padding: "8px 12px",
      fontSize: "16px",
      border: `2px solid ${safeTheme.border}`,
      borderRadius: "8px",
      backgroundColor: safeTheme.background,
      color: safeTheme.textSecondary,
      minWidth: "200px",
      textAlign: "center",
    },
    warningMessage: {
      backgroundColor: (safeTheme.warning || "#F59E0B") + "20",
      color: safeTheme.warning || "#F59E0B",
      border: `1px solid ${safeTheme.warning || "#F59E0B"}`,
      padding: "12px 20px",
      borderRadius: "8px",
      fontSize: "16px",
      fontWeight: "500",
      textAlign: "center",
    },
    errorMessage: {
      backgroundColor: (safeTheme.error || "#EF4444") + "20",
      border: `1px solid ${safeTheme.error || "#EF4444"}`,
      color: safeTheme.error || "#EF4444",
      padding: "12px",
      borderRadius: "8px",
      margin: "16px 0",
      fontSize: "14px",
      maxWidth: "1200px",
      marginLeft: "auto",
      marginRight: "auto",
      textAlign: "center",
    },
  };
};

// ==================== POTIONS STYLES ====================
export const createPotionsStyles = (theme) => ({
  container: {
    maxWidth: "1400px",
    margin: "0 auto",
    padding: "20px",
    backgroundColor: theme.background,
    minHeight: "100vh",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  title: {
    fontSize: "32px",
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: "24px",
    color: theme.text,
    textShadow: "2px 2px 4px rgba(0,0,0,0.1)",
  },
  themeControls: {
    display: "flex",
    gap: "16px",
    justifyContent: "center",
    marginBottom: "24px",
    flexWrap: "wrap",
  },
  themeControlGroup: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  themeLabel: {
    fontSize: "14px",
    fontWeight: "600",
    color: theme.text,
  },
  themeSelect: {
    padding: "8px 12px",
    border: `2px solid ${theme.border}`,
    borderRadius: "6px",
    backgroundColor: theme.surface,
    color: theme.text,
    fontSize: "14px",
  },
  controlsContainer: {
    display: "flex",
    justifyContent: "center",
    marginBottom: "24px",
  },
  card: {
    backgroundColor: theme.surface,
    borderRadius: "12px",
    padding: "20px",
    marginBottom: "20px",
    border: `2px solid ${theme.border}`,
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
  },
  cardTitle: {
    fontSize: "20px",
    fontWeight: "bold",
    color: theme.text,
    marginBottom: "16px",
    margin: 0,
  },
  proficiencyGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: "20px",
  },
  proficiencySection: {
    backgroundColor: theme.background,
    padding: "16px",
    borderRadius: "8px",
    border: `1px solid ${theme.border}`,
  },
  proficiencyTitle: {
    fontSize: "16px",
    fontWeight: "600",
    color: theme.text,
    marginBottom: "12px",
  },
  inputGroup: {
    marginBottom: "12px",
  },
  inputLabel: {
    display: "block",
    fontSize: "14px",
    fontWeight: "500",
    color: theme.text,
    marginBottom: "4px",
  },
  select: {
    width: "100%",
    padding: "8px 12px",
    border: `2px solid ${theme.border}`,
    borderRadius: "6px",
    backgroundColor: theme.surface,
    color: theme.text,
    fontSize: "14px",
  },
  checkboxGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "14px",
    color: theme.text,
    cursor: "pointer",
  },
  maxQualityInfo: {
    marginTop: "12px",
    padding: "8px 12px",
    backgroundColor: theme.primary + "20",
    borderRadius: "6px",
    fontSize: "14px",
    color: theme.text,
    fontWeight: "500",
  },
  searchContainer: {
    display: "flex",
    gap: "12px",
    alignItems: "center",
    flexWrap: "wrap",
  },
  searchInputContainer: {
    position: "relative",
    flex: 1,
    minWidth: "200px",
  },
  searchIcon: {
    position: "absolute",
    left: "12px",
    top: "50%",
    transform: "translateY(-50%)",
    color: theme.textSecondary,
  },
  searchInput: {
    width: "100%",
    padding: "10px 12px 10px 40px",
    border: `2px solid ${theme.border}`,
    borderRadius: "8px",
    backgroundColor: theme.surface,
    color: theme.text,
    fontSize: "16px",
  },
  mainGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 400px",
    gap: "20px",
  },
  potionList: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    maxHeight: "600px",
    overflowY: "auto",
    padding: "4px",
  },
  potionItem: {
    padding: "16px",
    border: `2px solid ${theme.border}`,
    borderRadius: "8px",
    cursor: "pointer",
    transition: "all 0.2s ease",
    backgroundColor: theme.background,
  },
  potionItemSelected: {
    borderColor: theme.primary,
    backgroundColor: theme.primary + "10",
  },
  potionItemHover: {
    borderColor: theme.primary + "80",
    backgroundColor: theme.surface,
  },
  potionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "8px",
  },
  potionName: {
    fontSize: "16px",
    fontWeight: "600",
    color: theme.text,
    margin: 0,
  },
  potionMeta: {
    display: "flex",
    gap: "8px",
    alignItems: "center",
  },
  potionYear: {
    fontSize: "12px",
    color: theme.textSecondary,
    fontWeight: "500",
  },
  rarityBadge: {
    fontSize: "10px",
    fontWeight: "600",
    padding: "2px 6px",
    borderRadius: "10px",
    textTransform: "uppercase",
    color: "white",
  },
  rarityColors: {
    common: "#6B7280",
    uncommon: "#10B981",
    rare: "#3B82F6",
    "very rare": "#8B5CF6",
    legendary: "#F59E0B",
  },
  potionDescription: {
    fontSize: "14px",
    color: theme.textSecondary,
    lineHeight: "1.4",
    margin: 0,
  },
  brewingInterface: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  selectedPotionCard: {
    backgroundColor: theme.primary + "10",
    border: `2px solid ${theme.primary}`,
    borderRadius: "12px",
    padding: "20px",
  },
  selectedPotionTitle: {
    fontSize: "20px",
    fontWeight: "bold",
    color: theme.text,
    marginBottom: "8px",
    margin: 0,
  },
  selectedPotionDescription: {
    fontSize: "14px",
    color: theme.textSecondary,
    lineHeight: "1.5",
    margin: 0,
  },
  brewButton: {
    backgroundColor: theme.primary,
    color: "white",
    border: "none",
    borderRadius: "8px",
    padding: "16px 24px",
    fontSize: "18px",
    fontWeight: "600",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "12px",
    transition: "all 0.2s ease",
    width: "100%",
  },
  brewButtonDisabled: {
    backgroundColor: theme.textSecondary,
    cursor: "not-allowed",
  },
  resultCard: {
    backgroundColor: theme.surface,
    border: `2px solid ${theme.border}`,
    borderRadius: "12px",
    padding: "20px",
  },
  resultTitle: {
    fontSize: "18px",
    fontWeight: "600",
    color: theme.text,
    marginBottom: "16px",
    margin: 0,
  },
  resultGrid: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  resultRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  resultLabel: {
    fontSize: "14px",
    fontWeight: "500",
    color: theme.textSecondary,
  },
  resultValue: {
    fontSize: "14px",
    fontWeight: "600",
    color: theme.text,
  },
  diceResult: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  diceValue: {
    fontSize: "14px",
    fontWeight: "600",
    color: theme.text,
  },
  qualityResult: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "14px",
    fontWeight: "600",
    textTransform: "capitalize",
  },
  qualityRuined: {
    color: "#EF4444",
  },
  qualityFlawed: {
    color: "#F59E0B",
  },
  qualityNormal: {
    color: "#10B981",
  },
  qualityExceptional: {
    color: "#3B82F6",
  },
  qualitySuperior: {
    color: "#8B5CF6",
  },
  resultTimestamp: {
    fontSize: "12px",
    color: theme.textSecondary,
    fontStyle: "italic",
    textAlign: "center",
    marginTop: "8px",
  },
  referenceGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: "20px",
    marginTop: "24px",
  },
  referenceTable: {
    width: "100%",
    borderCollapse: "collapse",
  },
  referenceTableHeader: {
    display: "grid",
    gridTemplateColumns: "1fr repeat(4, 0.8fr)",
    gap: "8px",
    padding: "12px",
    backgroundColor: theme.background,
    fontWeight: "600",
    fontSize: "14px",
    color: theme.text,
    borderBottom: `2px solid ${theme.border}`,
  },
  referenceTableRow: {
    display: "grid",
    gridTemplateColumns: "1fr repeat(4, 0.8fr)",
    gap: "8px",
    padding: "8px 12px",
    borderBottom: `1px solid ${theme.border}`,
    fontSize: "14px",
    color: theme.text,
  },
  referenceTableRowHeader: {
    fontWeight: "600",
    textTransform: "capitalize",
  },
  ingredientEffectsList: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  ingredientEffectRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "8px 12px",
    backgroundColor: theme.background,
    borderRadius: "6px",
    fontSize: "14px",
  },
  ingredientEffectLabel: {
    fontWeight: "600",
    textTransform: "capitalize",
    color: theme.text,
  },
  ingredientEffectValue: {
    fontWeight: "500",
    color: theme.text,
  },
  ingredientEffectHarder: {
    color: "#EF4444",
  },
  ingredientEffectEasier: {
    color: "#10B981",
  },
  button: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "10px 16px",
    border: "none",
    borderRadius: "6px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
    color: "white",
  },
  primaryButton: {
    backgroundColor: theme.primary,
  },
});

// ==================== FEAT STYLES (COMMON) ====================
export const createFeatStyles = (theme) => ({
  fieldContainer: {
    marginBottom: "20px",
  },
  skillsHeader: {
    fontSize: "20px",
    fontWeight: "bold",
    color: theme.text,
    marginBottom: "8px",
    margin: 0,
  },
  featFilterContainer: {
    position: "relative",
    marginBottom: "16px",
  },
  featFilterInput: {
    width: "100%",
    padding: "12px 40px 12px 16px",
    borderRadius: "8px",
    border: `2px solid ${theme.warning || "#F59E0B"}`,
    fontSize: "16px",
    backgroundColor: theme.surface,
    color: theme.text,
    boxShadow:
      "inset 0 2px 6px rgba(245,158,11,0.2), 0 2px 4px rgba(0,0,0,0.1)",
    transition: "all 0.3s ease",
  },
  featFilterClearButton: {
    position: "absolute",
    right: "12px",
    top: "50%",
    transform: "translateY(-50%)",
    width: "24px",
    height: "24px",
    borderRadius: "50%",
    backgroundColor: "#FBBF24",
    color: "white",
    border: "none",
    fontSize: "16px",
    fontWeight: "bold",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 2px 4px rgba(0,0,0,0.2)",
    transition: "all 0.2s ease",
  },
  featFilterResults: {
    fontSize: "12px",
    color: theme.textSecondary,
    marginTop: "4px",
    fontStyle: "italic",
  },
  featsContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    maxHeight: "400px",
    overflowY: "auto",
    padding: "4px",
  },
  featCard: {
    backgroundColor: theme.background,
    border: `2px solid ${theme.border}`,
    borderRadius: "12px",
    padding: "16px",
    transition: "all 0.2s ease",
  },
  featCardSelected: {
    backgroundColor: "#F0FDF4",
    border: "2px solid #10B981",
  },
  featHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "8px",
  },
  featLabelClickable: {
    display: "flex",
    alignItems: "center",
    cursor: "pointer",
    fontSize: "16px",
    fontWeight: "600",
  },
  featName: {
    color: theme.text,
  },
  featNameSelected: {
    color: "#059669",
  },
  expandButton: {
    backgroundColor: theme.background,
    border: `1px solid ${theme.border}`,
    borderRadius: "4px",
    padding: "4px 8px",
    cursor: "pointer",
    fontSize: "12px",
    color: theme.textSecondary,
    transition: "all 0.2s ease",
  },
  featPreview: {
    fontSize: "14px",
    color: theme.textSecondary,
    lineHeight: "1.4",
    fontStyle: "italic",
  },
  featPreviewSelected: {
    fontSize: "14px",
    color: "#047857",
    lineHeight: "1.4",
    fontStyle: "italic",
  },
  featDescription: {
    marginTop: "12px",
    fontSize: "14px",
    color: theme.text,
    lineHeight: "1.5",
    backgroundColor: theme.surface,
    padding: "12px",
    borderRadius: "8px",
    border: `1px solid ${theme.border}`,
  },
  featDescriptionSelected: {
    marginTop: "12px",
    fontSize: "14px",
    color: "#1F2937",
    lineHeight: "1.5",
    backgroundColor: "#F0FDF4",
    padding: "12px",
    borderRadius: "8px",
    border: "1px solid #D1FAE5",
  },
  noFeatsFound: {
    textAlign: "center",
    padding: "40px 20px",
    color: theme.textSecondary,
    fontSize: "16px",
    backgroundColor: theme.surface,
    borderRadius: "12px",
    border: `2px dashed ${theme.border}`,
  },
  helpText: {
    fontSize: "14px",
    color: theme.textSecondary,
    marginTop: "12px",
    fontStyle: "italic",
  },
});

// ==================== INVENTORY STYLES ====================
export const createInventoryStyles = (theme) => ({
  container: {
    maxWidth: "1800px",
    margin: "0 auto",
    padding: "20px",
    backgroundColor: theme.background,
    minHeight: "100vh",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  mainLayout: {
    display: "grid",
    gridTemplateColumns: "350px 1fr",
    gap: "24px",
    maxWidth: "1600px",
    margin: "0 auto",
  },
  bankContainer: {
    backgroundColor: theme.surface,
    borderRadius: "12px",
    padding: "20px",
    border: `2px solid ${theme.border}`,
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    height: "fit-content",
    position: "sticky",
    top: "20px",
  },
  inventorySection: {
    minWidth: 0,
  },
  header: {
    backgroundColor: theme.surface,
    borderRadius: "12px",
    padding: "24px",
    marginBottom: "24px",
    border: `2px solid ${theme.border}`,
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
  },
  title: {
    fontSize: "28px",
    fontWeight: "bold",
    color: theme.text,
    margin: "0 0 8px 0",
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  subtitle: {
    fontSize: "16px",
    color: theme.textSecondary,
    margin: 0,
  },
  errorMessage: {
    backgroundColor: (theme.error || "#EF4444") + "20",
    border: `1px solid ${theme.error || "#EF4444"}`,
    color: theme.error || "#EF4444",
    padding: "12px",
    borderRadius: "8px",
    marginBottom: "16px",
    fontSize: "14px",
  },
  loadingMessage: {
    backgroundColor: (theme.primary || "#6366F1") + "20",
    border: `1px solid ${theme.primary || "#6366F1"}`,
    color: theme.primary || "#6366F1",
    padding: "12px",
    borderRadius: "8px",
    marginBottom: "16px",
    fontSize: "14px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  controls: {
    display: "flex",
    gap: "12px",
    alignItems: "center",
    marginBottom: "24px",
    flexWrap: "wrap",
  },
  addButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 20px",
    backgroundColor: theme.primary,
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
    fontFamily: "inherit",
  },
  searchContainer: {
    position: "relative",
    flex: "1",
    minWidth: "250px",
  },
  searchInput: {
    width: "100%",
    paddingLeft: "40px",
    paddingRight: "16px",
    paddingTop: "12px",
    paddingBottom: "12px",
    border: `2px solid ${theme.border}`,
    borderRadius: "8px",
    backgroundColor: theme.surface,
    color: theme.text,
    fontSize: "16px",
    fontFamily: "inherit",
  },
  searchIcon: {
    position: "absolute",
    left: "12px",
    top: "50%",
    transform: "translateY(-50%)",
    color: theme.textSecondary,
  },
  formCard: {
    backgroundColor: theme.surface,
    borderRadius: "12px",
    padding: "24px",
    marginBottom: "24px",
    border: `2px solid ${theme.border}`,
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
  },
  formTitle: {
    fontSize: "20px",
    fontWeight: "600",
    color: theme.text,
    marginBottom: "20px",
    margin: "0 0 20px 0",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
    marginBottom: "16px",
  },
  formField: {
    display: "flex",
    flexDirection: "column",
  },
  formFieldFull: {
    gridColumn: "1 / -1",
  },
  checkboxField: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    gridColumn: "1 / -1",
    marginTop: "8px",
  },
  label: {
    fontSize: "14px",
    fontWeight: "600",
    color: theme.text,
    marginBottom: "8px",
  },
  checkboxLabel: {
    fontSize: "14px",
    fontWeight: "500",
    color: theme.text,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  input: {
    padding: "12px",
    border: `2px solid ${theme.border}`,
    borderRadius: "8px",
    backgroundColor: theme.surface,
    color: theme.text,
    fontSize: "16px",
    fontFamily: "inherit",
  },
  checkbox: {
    width: "18px",
    height: "18px",
    accentColor: theme.primary,
    cursor: "pointer",
  },
  select: {
    padding: "12px",
    border: `2px solid ${theme.border}`,
    borderRadius: "8px",
    backgroundColor: theme.surface,
    color: theme.text,
    fontSize: "16px",
    fontFamily: "inherit",
  },
  textarea: {
    padding: "12px",
    border: `2px solid ${theme.border}`,
    borderRadius: "8px",
    backgroundColor: theme.surface,
    color: theme.text,
    fontSize: "16px",
    height: "80px",
    resize: "vertical",
    fontFamily: "inherit",
  },
  formActions: {
    display: "flex",
    gap: "12px",
  },
  saveButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 24px",
    backgroundColor: theme.success || "#10B981",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    flex: "1",
    justifyContent: "center",
    fontFamily: "inherit",
  },
  cancelButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 24px",
    backgroundColor: theme.textSecondary,
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    fontFamily: "inherit",
  },
  itemsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))",
    gap: "16px",
  },
  itemCard: {
    backgroundColor: theme.surface,
    borderRadius: "12px",
    padding: "20px",
    border: `2px solid ${theme.border}`,
    transition: "all 0.2s ease",
    position: "relative",
  },
  itemHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "12px",
  },
  itemName: {
    fontSize: "18px",
    fontWeight: "600",
    color: theme.text,
    margin: "0 0 4px 0",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexWrap: "wrap",
  },
  quantityBadge: {
    fontSize: "12px",
    fontWeight: "600",
    padding: "4px 8px",
    backgroundColor: theme.background,
    color: theme.text,
    borderRadius: "12px",
    border: `1px solid ${theme.border}`,
  },
  attunementBadge: {
    fontSize: "12px",
    fontWeight: "600",
    padding: "4px 8px",
    backgroundColor: theme.warning || "#F59E0B",
    color: "white",
    borderRadius: "12px",
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  itemActions: {
    display: "flex",
    gap: "8px",
  },
  actionButton: {
    padding: "8px",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.2s ease",
  },
  editButton: {
    backgroundColor: theme.accent || "#3B82F6",
    color: "white",
  },
  deleteButton: {
    backgroundColor: theme.error || "#EF4444",
    color: "white",
  },
  itemDescription: {
    fontSize: "14px",
    color: theme.textSecondary,
    marginBottom: "12px",
    lineHeight: "1.4",
  },
  itemMeta: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: "14px",
    color: theme.text,
    gap: "8px",
    flexWrap: "wrap",
  },
  emptyState: {
    textAlign: "center",
    padding: "60px 20px",
    backgroundColor: theme.surface,
    borderRadius: "12px",
    border: `2px solid ${theme.border}`,
  },
  emptyIcon: {
    marginBottom: "16px",
    opacity: 0.5,
  },
  emptyText: {
    fontSize: "18px",
    color: theme.textSecondary,
    margin: 0,
  },
  categoryHeader: {
    fontSize: "18px",
    fontWeight: "600",
    color: theme.text,
    marginBottom: "16px",
    padding: "12px 16px",
    backgroundColor: theme.surface,
    borderRadius: "8px",
    border: `1px solid ${theme.border}`,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  categoryStats: {
    fontSize: "14px",
    color: theme.textSecondary,
    fontWeight: "normal",
  },
  statsCard: {
    backgroundColor: theme.surface,
    padding: "16px",
    borderRadius: "8px",
    border: `1px solid ${theme.border}`,
    marginBottom: "16px",
  },
  statsRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: "14px",
    color: theme.text,
    marginBottom: "8px",
  },
  statsRowLast: {
    marginBottom: 0,
  },
});

// ==================== NOTES STYLES ====================
export const createCharacterNotesStyles = (theme) => ({
  // === MAIN CONTAINER ===
  container: {
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "20px",
  },

  // === HEADER SECTION ===
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "20px",
    padding: "20px",
    backgroundColor: theme.surface,
    borderRadius: "12px",
    border: `2px solid ${theme.border}`,
    boxShadow: "0 2px 4px rgba(0,0,0,0.05)",
  },
  headerContent: {
    display: "flex",
    flexDirection: "column",
  },
  title: {
    margin: "0 0 8px 0",
    fontSize: "28px",
    color: theme.text,
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  subtitle: {
    margin: "0",
    color: theme.textSecondary,
    fontSize: "16px",
  },
  headerActions: {
    display: "flex",
    gap: "12px",
    alignItems: "center",
  },
  newEntryButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 20px",
    backgroundColor: theme.primary,
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },

  // === NO CHARACTER SELECTED STATE ===
  noCharacterContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "60px 20px",
    backgroundColor: "#fef2f2",
    border: "2px solid #fecaca",
    borderRadius: "12px",
    margin: "20px",
    maxWidth: "600px",
    marginLeft: "auto",
    marginRight: "auto",
  },
  noCharacterIcon: {
    marginBottom: "16px",
  },
  noCharacterTitle: {
    color: "#dc2626",
    margin: "0 0 8px 0",
    fontSize: "24px",
  },
  noCharacterText: {
    color: "#dc2626",
    margin: "0",
    textAlign: "center",
  },

  // === NEW ENTRY FORM ===
  newEntryForm: {
    backgroundColor: theme.surface,
    padding: "20px",
    borderRadius: "12px",
    border: `2px solid ${theme.border}`,
    marginBottom: "20px",
    boxShadow: "0 2px 4px rgba(0,0,0,0.05)",
  },
  newEntryTitle: {
    margin: "0 0 12px 0",
    fontSize: "18px",
    color: theme.text,
  },
  newEntryInput: {
    width: "100%",
    padding: "12px",
    border: `1px solid ${theme.border}`,
    borderRadius: "8px",
    fontSize: "16px",
    outline: "none",
    backgroundColor: theme.background,
    color: theme.text,
    marginBottom: "16px",
  },
  templateButtons: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
    marginBottom: "16px",
  },
  templateButton: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "8px 12px",
    backgroundColor: theme.background,
    border: `1px solid ${theme.border}`,
    borderRadius: "6px",
    fontSize: "14px",
    cursor: "pointer",
    color: theme.text,
    transition: "all 0.2s ease",
  },
  formActions: {
    display: "flex",
    gap: "8px",
  },
  cancelButton: {
    padding: "8px 16px",
    backgroundColor: theme.background,
    border: `1px solid ${theme.border}`,
    borderRadius: "6px",
    cursor: "pointer",
    color: theme.text,
  },

  // === EDIT FORM ===
  editForm: {
    backgroundColor: theme.surface,
    borderRadius: "12px",
    border: `2px solid ${theme.border}`,
    boxShadow: "0 2px 4px rgba(0,0,0,0.05)",
    overflow: "hidden",
  },
  editHeader: {
    padding: "16px 20px",
    borderBottom: `1px solid ${theme.border}`,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  editTitleInput: {
    flex: 1,
    padding: "8px 12px",
    border: `1px solid ${theme.border}`,
    borderRadius: "6px",
    fontSize: "18px",
    fontWeight: "600",
    marginRight: "12px",
    backgroundColor: theme.background,
    color: theme.text,
  },
  editActions: {
    display: "flex",
    gap: "8px",
  },
  saveButton: {
    padding: "8px 16px",
    backgroundColor: theme.success + "20",
    border: `1px solid ${theme.success}`,
    borderRadius: "6px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    color: theme.success,
    fontSize: "14px",
    fontWeight: "600",
    gap: "6px",
  },
  editCancelButton: {
    padding: "8px 16px",
    backgroundColor: theme.background,
    border: `1px solid ${theme.border}`,
    borderRadius: "6px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    fontSize: "14px",
    fontWeight: "600",
    gap: "6px",
    color: theme.text,
  },
  templateSection: {
    padding: "16px 20px",
    borderBottom: `1px solid ${theme.border}`,
    backgroundColor: theme.background,
  },
  templateSectionTitle: {
    margin: "0 0 12px 0",
    fontSize: "14px",
    color: theme.text,
    fontWeight: "600",
  },
  editorContainer: {
    padding: "20px",
  },
  editorLoading: {
    height: "500px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.background,
    borderRadius: "8px",
    color: theme.textSecondary,
  },

  // === ENTRY CARDS ===
  entriesGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(400px, 1fr))",
    gap: "20px",
  },
  entryCard: {
    backgroundColor: theme.surface,
    borderRadius: "12px",
    border: `2px solid ${theme.border}`,
    boxShadow: "0 2px 4px rgba(0,0,0,0.05)",
    overflow: "hidden",
    transition: "all 0.2s ease",
  },
  entryHeader: {
    padding: "16px 20px",
    borderBottom: `1px solid ${theme.border}`,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  entryTitleSection: {
    flex: 1,
  },
  entryTitle: {
    margin: "0 0 4px 0",
    fontSize: "18px",
    color: theme.text,
    fontWeight: "600",
  },
  entryDate: {
    margin: "0",
    fontSize: "12px",
    color: theme.textSecondary,
  },
  entryActions: {
    display: "flex",
    gap: "8px",
    marginLeft: "12px",
  },
  editEntryButton: {
    padding: "6px",
    backgroundColor: theme.background,
    border: `1px solid ${theme.border}`,
    borderRadius: "4px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    color: theme.text,
    transition: "all 0.2s ease",
  },
  deleteEntryButton: {
    padding: "6px",
    backgroundColor: "#fef2f2",
    border: "1px solid #fecaca",
    borderRadius: "4px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    color: "#dc2626",
    transition: "all 0.2s ease",
  },
  entryContent: {
    padding: "20px",
  },

  // === LOADING AND EMPTY STATES ===
  loadingContainer: {
    padding: "60px 20px",
    textAlign: "center",
    color: theme.textSecondary,
    fontSize: "16px",
    backgroundColor: theme.surface,
    borderRadius: "12px",
    border: `2px solid ${theme.border}`,
  },
  emptyContainer: {
    padding: "60px 20px",
    textAlign: "center",
    color: theme.textSecondary,
    fontSize: "16px",
    backgroundColor: theme.surface,
    borderRadius: "12px",
    border: `2px solid ${theme.border}`,
  },

  // === IMPORT/EXPORT SECTION ===
  importExportSection: {
    backgroundColor: theme.surface,
    padding: "16px 20px",
    borderRadius: "12px",
    border: `2px solid ${theme.border}`,
    marginTop: "20px",
    boxShadow: "0 2px 4px rgba(0,0,0,0.05)",
  },
  importExportActions: {
    display: "flex",
    gap: "8px",
    alignItems: "center",
  },
  exportButton: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "8px 12px",
    backgroundColor: theme.success + "20",
    border: `1px solid ${theme.success}`,
    borderRadius: "6px",
    fontSize: "14px",
    cursor: "pointer",
    color: theme.success,
  },
  importLabel: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "8px 12px",
    backgroundColor: theme.primary + "20",
    border: `1px solid ${theme.primary}`,
    borderRadius: "6px",
    fontSize: "14px",
    cursor: "pointer",
    color: theme.primary,
  },
  hiddenFileInput: {
    display: "none",
  },

  // === HOVER EFFECTS ===
  templateButtonHover: {
    backgroundColor: theme.primary + "10",
    borderColor: theme.primary,
  },
  editEntryButtonHover: {
    backgroundColor: theme.primary + "20",
    borderColor: theme.primary,
  },
  deleteEntryButtonHover: {
    backgroundColor: "#fee2e2",
    borderColor: "#dc2626",
  },
  newEntryButtonHover: {
    backgroundColor: theme.secondary,
    transform: "translateY(-1px)",
    boxShadow: `0 4px 12px ${theme.primary}40`,
  },
});

export const createCharacterGalleryStyles = (theme) => ({
  container: {
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "20px",
    backgroundColor: theme.background,
    minHeight: "100vh",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "24px",
    padding: "24px",
    backgroundColor: theme.surface,
    borderRadius: "12px",
    border: `2px solid ${theme.border}`,
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
  },
  headerLeft: {
    display: "flex",
    alignItems: "flex-start",
    gap: "16px",
  },
  title: {
    fontSize: "28px",
    fontWeight: "bold",
    color: theme.text,
    margin: "0 0 8px 0",
  },
  subtitle: {
    fontSize: "16px",
    color: theme.textSecondary,
    margin: 0,
    lineHeight: "1.5",
  },
  headerRight: {
    display: "flex",
    alignItems: "center",
  },
  toggleAllButton: {
    padding: "12px 20px",
    backgroundColor: theme.primary,
    color: theme.surface,
    border: "none",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  statsBar: {
    display: "flex",
    justifyContent: "center",
    gap: "32px",
    marginBottom: "24px",
    padding: "16px",
    backgroundColor: theme.surface,
    borderRadius: "8px",
    border: `1px solid ${theme.border}`,
  },
  statItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "14px",
    fontWeight: "500",
    color: theme.text,
  },
  schoolContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  schoolSection: {
    backgroundColor: theme.surface,
    borderRadius: "12px",
    border: `2px solid ${theme.border}`,
    overflow: "hidden",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
  },
  schoolHeader: {
    width: "100%",
    padding: "20px",
    border: "none",
    background: "none",
    cursor: "pointer",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    transition: "all 0.2s ease",
    borderBottom: `1px solid ${theme.border}`,
  },
  schoolHeaderLeft: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
  },
  schoolTitle: {
    fontSize: "24px",
    fontWeight: "bold",
    color: theme.text,
    margin: 0,
  },
  schoolCount: {
    fontSize: "14px",
    color: theme.textSecondary,
    fontWeight: "normal",
  },
  schoolHeaderRight: {
    display: "flex",
    alignItems: "center",
  },
  schoolContent: {
    padding: "0 0 20px 0",
  },
  typeSection: {
    marginBottom: "12px",
  },
  typeHeader: {
    width: "calc(100% - 40px)",
    padding: "16px",
    border: `1px solid ${theme.border}`,
    borderRadius: "8px",
    background: "none",
    cursor: "pointer",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    transition: "all 0.2s ease",
    margin: "0 20px",
  },
  typeHeaderLeft: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  typeTitle: {
    fontSize: "18px",
    fontWeight: "600",
    color: theme.text,
    margin: 0,
  },
  characterCount: {
    fontSize: "12px",
    color: theme.textSecondary,
    fontWeight: "normal",
  },
  typeHeaderRight: {
    display: "flex",
    alignItems: "center",
  },
  charactersGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))",
    gap: "16px",
    padding: "16px 20px",
  },
  characterCard: {
    backgroundColor: theme.surface,
    borderRadius: "12px",
    border: `1px solid ${theme.border}`,
    overflow: "hidden",
    transition: "all 0.2s ease",
    cursor: "pointer",
  },
  characterCardHover: {
    transform: "translateY(-4px)",
    boxShadow: "0 8px 25px rgba(0, 0, 0, 0.15)",
    borderColor: theme.primary,
  },
  imageContainer: {
    position: "relative",
    height: "300px",
    width: "300px",
    overflow: "hidden",
  },
  characterImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  imagePlaceholder: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.background,
    color: theme.textSecondary,
  },
  placeholderText: {
    fontSize: "12px",
    marginTop: "8px",
  },
  houseBadge: {
    position: "absolute",
    top: "12px",
    right: "12px",
    padding: "4px 8px",
    borderRadius: "12px",
    fontSize: "10px",
    fontWeight: "600",
    border: "1px solid",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  characterInfo: {
    padding: "16px",
  },
  characterName: {
    fontSize: "16px",
    fontWeight: "600",
    color: theme.text,
    margin: "0 0 8px 0",
    lineHeight: "1.3",
  },
});
export const createDowntimeStyles = (theme) => ({
  container: {
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "20px",
    fontFamily: "Arial, sans-serif",
    fontSize: "12px",
    backgroundColor: theme.background,
    color: theme.text,
    minHeight: "100vh",
  },
  sheet: {
    backgroundColor: theme.surface,
    border: `2px solid ${theme.border}`,
    borderRadius: "8px",
    overflow: "hidden",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
  },
  headerSection: {
    display: "grid",
    gridTemplateColumns: "2fr 2fr",
    borderBottom: `2px solid ${theme.border}`,
  },
  nameSection: {
    padding: "12px",
    borderRight: `2px solid ${theme.border}`,
  },
  gradesSection: {
    padding: "12px",
    textAlign: "center",
    fontWeight: "bold",
    fontSize: "14px",
    backgroundColor: theme.primary + "20",
    borderBottom: `2px solid ${theme.border}`,
    color: theme.text,
  },
  yearSemesterSection: {
    display: "grid",
    gridTemplateColumns: "2fr 1fr",
    borderBottom: `2px solid ${theme.border}`,
  },
  typeSection: {
    padding: "12px",
  },
  semesterSection: {
    padding: "12px",
  },
  subjectsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    borderBottom: `2px solid ${theme.border}`,
  },
  subjectColumn: {
    borderRight: `2px solid ${theme.border}`,
    "&:last-child": {
      borderRight: "none",
    },
  },
  subjectItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "8px 12px",
    borderBottom: `1px solid ${theme.border}`,
  },
  activitiesSection: {
    borderBottom: `2px solid ${theme.border}`,
  },
  activityRow: {
    display: "grid",
    gridTemplateColumns: "60px 1fr",
    alignItems: "center",
    padding: "12px",
    borderBottom: `1px solid ${theme.border}`,
    gap: "8px",
  },
  relationshipRow: {
    display: "grid",
    gridTemplateColumns: "50px 1fr auto auto",
    alignItems: "center",
    padding: "12px",
    borderBottom: `1px solid ${theme.border}`,
    gap: "8px",
    backgroundColor: theme.background,
  },
  relationshipInput: {
    border: `1px solid ${theme.border}`,
    borderRadius: "4px",
    padding: "4px 8px",
    alignItems: "left",
    fontSize: "12px",
    width: "100%",
    backgroundColor: theme.surface,
    color: theme.text,
  },
  activityHeader: {
    backgroundColor: theme.primary + "20",
    fontWeight: "bold",
    padding: "12px",
    borderBottom: `2px solid ${theme.border}`,
    color: theme.text,
  },
  input: {
    border: `1px solid ${theme.border}`,
    borderRadius: "4px",
    padding: "4px 8px",
    fontSize: "12px",
    width: "100%",
    backgroundColor: theme.surface,
    color: theme.text,
  },
  select: {
    border: `1px solid ${theme.border}`,
    borderRadius: "4px",
    padding: "4px 8px",
    fontSize: "12px",
    width: "100%",
    backgroundColor: theme.surface,
    color: theme.text,
    cursor: "pointer",
  },
  gradeInput: {
    border: `1px solid ${theme.border}`,
    borderRadius: "4px",
    padding: "2px 6px",
    fontSize: "11px",
    width: "40px",
    textAlign: "center",
    backgroundColor: theme.surface,
    color: theme.text,
  },
  checkbox: {
    margin: "0 4px",
    accentColor: theme.primary,
  },
  checkboxRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexWrap: "wrap",
  },
  successCheckboxes: {
    display: "flex",
    gap: "4px",
  },
  magicSchoolSection: {
    padding: "16px",
    backgroundColor: theme.background,
  },
  sectionTitle: {
    fontWeight: "bold",
    fontSize: "14px",
    marginBottom: "8px",
    color: theme.text,
  },
  radioGroup: {
    display: "flex",
    justifyContent: "space-between",
    gap: "16px",
    marginTop: "12px",
  },
  magicSchoolItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "8px",
  },
  exportButton: {
    backgroundColor: theme.success || "#28a745",
    color: "white",
    border: "none",
    borderRadius: "6px",
    padding: "12px 24px",
    fontSize: "14px",
    fontWeight: "bold",
    cursor: "pointer",
    marginBottom: "16px",
    transition: "background-color 0.2s ease",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
  },
  exportButtonHover: {
    backgroundColor: theme.primary,
  },
});

// ==================== EXPORT ALL STYLES ====================
export const getAllStyles = (theme) => ({
  app: createAppStyles(theme),
  characterSheet: createCharacterSheetStyles(theme),
  abilityScores: createAbilityScoresStyles(theme),
  skills: createSkillsStyles(theme),
  characterCreation: createCharacterCreationStyles(theme),
  abilityScorePicker: createAbilityScorePickerStyles(theme),
  spellBook: createSpellBookStyles(theme),
  characterSelector: createCharacterSelectorStyles(theme),
  characterNotes: createCharacterNotesStyles(theme),
  potions: createPotionsStyles(theme),
  feats: createFeatStyles(theme),
});

// Individual style exports for components that prefer specific functions
export {
  createAppStyles as createThemedStyles,
  createCharacterSheetStyles as getCharacterSheetStyles,
  createAbilityScoresStyles as getAbilityScoresStyles,
  createSkillsStyles as getSkillsStyles,
  createCharacterCreationStyles as getStyles,
  createAbilityScorePickerStyles as getAbilityScorePickerStyles,
  createSpellBookStyles as createThemedSpellBookStyles,
  createCharacterSelectorStyles as getCharacterSelectorStyles,
  createCharacterNotesStyles as getCharacterNotesStyles,
  createPotionsStyles as createThemedPotionStyles,
  createFeatStyles as getFeatStyles,
  createInventoryStyles as getInventoryStyles,
  createCharacterGalleryStyles as getCharacterGalleryStyles,
  createDowntimeStyles as getDowntimeStyles,
};
