export const DEFAULT_CHARACTER = {
  name: "",
  imageUrl: "",
  level: 1,
  schoolYear: "First",
  castingStyle: "",
  ability_scores: {
    strength: 8,
    dexterity: 8,
    constitution: 8,
    intelligence: 8,
    wisdom: 8,
    charisma: 8,
  },
  background: "",
  house: "",
  heritage: "",
  hit_points: 0,
  current_hit_points: 0,
  current_hit_dice: 1,
  current_hit_points: 0,
  discord_user_id: "",
  feat_choices: {},
  game_session: "",
  asi_choices: {},
  house_choices: {},
  houseChoices: {},
  heritage_choices: {},
  feat_choices: {},
  subclass_choices: {},
  toolProficiencies: [],
  metamagic: [],

  level1ChoiceType: "",
  name: "",
  notes: "",
  schoolYear: "1",
  selectedFeat: "",
  selectedInnateHeritage: "",
  discord_user_id: "",
  created_at: "",
  updated_at: "",
};

export const ABILITY_SCORES = [
  "strength",
  "dexterity",
  "constitution",
  "intelligence",
  "wisdom",
  "charisma",
];

export const CASTING_STYLES = [
  "Academics",
  "Alchemy",
  "Artisan",
  "Primal",
  "Innate",
];

export const SCHOOL_YEARS = [
  "First",
  "Second",
  "Third",
  "Fourth",
  "Fifth",
  "Sixth",
  "Seventh",
];
