// NPC relationship data keyed by character name.
// Levels 1–4 are available to any player who reaches them.
// Level 5 is romance-only: unlocked after 4 successful attempts if the player
// has chosen to pursue a romance with this NPC.

export const NPC_DATA = {
  // ---------------------------------------------------------------------------
  // ILVERMORNY — Classmates
  // ---------------------------------------------------------------------------

  "Erika Baker": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Bailey-Anna Balders": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Warren Cheredaryk": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Seth Claw": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Jeremiah Collier": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Omari Curtis": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Tony DeLuca": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Colby Engel": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Genesis Firth": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Maddie Gardner": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  Harmony: {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Anuhea Kelii": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Olivia Law": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Shelby MGH": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Azha Pavan": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Ava Robinson": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Noah Robinson": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Rome Sanford": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Claire Takahashi": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },

  // ---------------------------------------------------------------------------
  // ILVERMORNY — Underclassmen
  // ---------------------------------------------------------------------------

  "Gordy Baker": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Mitch Cheredaryk": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Celia Claw": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Keyla Collier": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Messiah Firth": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Johnny Gardner": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  Heather: {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Willow Vanderhoeven": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },

  // ---------------------------------------------------------------------------
  // ILVERMORNY — Upperclassmen
  // ---------------------------------------------------------------------------

  "Brad Baker": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Declan Baker": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Florence Baker": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Ian Baker": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Tanner Baker": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Ingrid Cheredaryk": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Kamayla Collier": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Antoine Curtis": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Araminta D'Valliste": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Cason Gardner": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Emily Gardner": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Jesse Gardner": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Maggie Gardner": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Marley Gardner": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Jade Halford": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  Patience: {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Rio Sanford": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Panuk Tuktu": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  Valor: {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },

  // ---------------------------------------------------------------------------
  // ILVERMORNY — Faculty (no romance option)
  // ---------------------------------------------------------------------------

  "Professor Sakari Anana": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Noreen Barbuscio": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Sumaira Bashir": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Mrs. Valentina Carrera": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Mrs. Wendy Drummond": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Darby Duncan": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Russell Hart": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Shantella Jackson": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Headmaster Osiris Kisio": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Amy Loo": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Mr. Lloyd McNab": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Korrie Melvin": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Calvin Muhoza": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Aciano Nyxi": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Trevor Rogers": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Andrew Siemens": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Mr. John Tolman": { 1: {}, 2: {}, 3: {}, 4: {} },

  // ---------------------------------------------------------------------------
  // HOGWARTS — Classmates
  // ---------------------------------------------------------------------------

  "Alyssa Abbott": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Eldon Barclay": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Andromeda Black": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Derek Blishwick": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Dorothy Brown": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Hamish Bulstrode": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Eleanor Burke": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Graham Carrow": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Calliope Crabbe": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Connor Duncan": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Jeanette Fawley": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Sadhbh Kelly": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Veronica Khatib": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Christopher Kim": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Francesca Macdougal": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Robbie Macmillan": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Lucius Malfoy": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Elizabeth Moody": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Cillian O'Brien": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Josie Pratt": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Fabian Prewett": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Gilda-Gideon Prewett": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Brenda Rosier": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Desmond Yaxley": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "William Zobell": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },

  // ---------------------------------------------------------------------------
  // HOGWARTS — Underclassmen
  // ---------------------------------------------------------------------------

  "Narcissa Black": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Eileen Brown": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Dominic Crabbe": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Errol Crabbe": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Fionna Crabbe": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Gretchen Crabbe": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Catherine Kim": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Jeannine Paxton": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Peter Yaxley": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },

  // ---------------------------------------------------------------------------
  // HOGWARTS — Upperclassmen
  // ---------------------------------------------------------------------------

  "Bellatrix Black": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Harlow Brown": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Sinclair Carrow": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Abraham Crabbe": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Bertrand Crabbe": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Joanne Fawley": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Axel Greer": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Blathnaid Kelly": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Niamh Kelly": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Orflaith Kelly": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Molly Prewett": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Rita Skeeter": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Arthur Weasley": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Ilona Yaxley": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },

  // ---------------------------------------------------------------------------
  // HOGWARTS — Faculty (no romance option)
  // ---------------------------------------------------------------------------

  "Professor Beery": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Binns": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Cox": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Crouch": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Headmaster Dumbledore": { 1: {}, 2: {}, 3: {}, 4: {} },
  Hagrid: { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Hasegawa": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Madam Hooch": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Janvier": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Klein": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Lorien": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Mackenzie": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor McGonagall": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Madam Pomphrey": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Riddle": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Shacklebolt": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Slughorn": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Tripe": { 1: {}, 2: {}, 3: {}, 4: {} },

  // ---------------------------------------------------------------------------
  // JAGUARAS — Competitors
  // ---------------------------------------------------------------------------

  "Antü Melillán": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Astrid Nordström": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Cairo Halim": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Caonabo Guaitiao": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Emma Walker": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Eniola Babajide": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Ito Chihiro": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Ixchel Balam": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Jackson Bennett": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Louise Hexsmith": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Nerio Albany": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Pierre Parkinson": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },
  "Pyotr Abramov": {
    1: {},
    2: {},
    3: {},
    4: {},
    5: { romanceOnly: true },
  },

  // ---------------------------------------------------------------------------
  // JAGUARAS — Faculty (no romance option)
  // ---------------------------------------------------------------------------

  "Headmistress Ana Costa": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Larissa Almeida": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Shanice Allen": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Santiago Espinosa": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Shari Augustine": { 1: {}, 2: {}, 3: {}, 4: {} },
  "Professor Wilner Toussaint": { 1: {}, 2: {}, 3: {}, 4: {} },
};
