export const styles = {
  container: {
    maxWidth: "112rem",
    margin: "0 auto",
    padding: "1.5rem",
    background: "linear-gradient(135deg, #6366F1 0%, #8B5CF6 100%)",
    borderRadius: "0.75rem",
    boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
    border: "2px solid #E5E7EB",
    color: "#1F2937",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  title: {
    fontSize: "1.875rem",
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: "1.5rem",
    fontFamily: "serif",
    color: "#1F2937",
  },
  themeControls: {
    marginBottom: "1.5rem",
    display: "flex",
    flexWrap: "wrap",
    gap: "1rem",
    justifyContent: "center",
  },
  themeControlGroup: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  themeLabel: {
    fontSize: "0.875rem",
    fontWeight: "500",
    color: "#1F2937",
  },
  themeSelect: {
    padding: "0.25rem 0.75rem",
    borderRadius: "0.375rem",
    border: "1px solid #D1D5DB",
    backgroundColor: "#FFFFFF",
    color: "#1F2937",
    fontSize: "0.875rem",
    cursor: "pointer",
    outline: "none",
    transition: "all 0.2s",
  },
  card: {
    padding: "1rem",
    borderRadius: "0.5rem",
    boxShadow: "inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)",
    border: "1px solid #E5E7EB",
    backgroundColor: "#FFFFFF",
    marginBottom: "1.5rem",
  },
  cardTitle: {
    fontSize: "1.125rem",
    fontWeight: "600",
    marginBottom: "0.75rem",
    color: "#1F2937",
  },
  controlsContainer: {
    display: "flex",
    gap: "1rem",
    marginBottom: "1.5rem",
  },
  button: {
    padding: "0.5rem 1rem",
    borderRadius: "0.375rem",
    transition: "all 0.2s",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    fontWeight: "500",
    cursor: "pointer",
    border: "none",
    outline: "none",
  },
  primaryButton: {
    backgroundColor: "#6366F1",
    color: "#FFFFFF",
  },
  primaryButtonHover: {
    backgroundColor: "#4F46E5",
  },
  successButton: {
    backgroundColor: "#10B981",
    color: "#FFFFFF",
  },
  dangerButton: {
    backgroundColor: "#EF4444",
    color: "#FFFFFF",
  },
  secondaryButton: {
    backgroundColor: "#6B7280",
    color: "#FFFFFF",
  },
  proficiencyGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: "1.5rem",
  },
  proficiencySection: {
    marginBottom: "1rem",
  },
  proficiencyTitle: {
    fontWeight: "500",
    marginBottom: "0.75rem",
    color: "#6B7280",
  },
  inputGroup: {
    marginBottom: "0.75rem",
  },
  inputLabel: {
    display: "block",
    fontSize: "0.875rem",
    fontWeight: "500",
    marginBottom: "0.25rem",
    color: "#6B7280",
  },
  select: {
    width: "100%",
    padding: "0.5rem 0.75rem",
    border: "1px solid #D1D5DB",
    borderRadius: "0.375rem",
    backgroundColor: "#FFFFFF",
    color: "#1F2937",
    fontSize: "0.875rem",
    outline: "none",
    transition: "all 0.2s",
  },
  checkboxGroup: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    fontSize: "0.875rem",
    color: "#6B7280",
    cursor: "pointer",
  },
  maxQualityInfo: {
    marginTop: "0.75rem",
    padding: "0.5rem",
    borderRadius: "0.375rem",
    fontSize: "0.875rem",
    backgroundColor: "#F3F4F6",
    color: "#6B7280",
  },
  searchContainer: {
    display: "flex",
    gap: "1rem",
    marginBottom: "1rem",
  },
  searchInputContainer: {
    flex: 1,
    position: "relative",
  },
  searchIcon: {
    position: "absolute",
    left: "0.75rem",
    top: "50%",
    transform: "translateY(-50%)",
    color: "#6B7280",
  },
  searchInput: {
    width: "100%",
    paddingLeft: "2.5rem",
    paddingRight: "1rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    border: "1px solid #D1D5DB",
    borderRadius: "0.375rem",
    backgroundColor: "#FFFFFF",
    color: "#1F2937",
    outline: "none",
    transition: "all 0.2s",
  },
  mainGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(500px, 1fr))",
    gap: "1.5rem",
  },
  potionList: {
    maxHeight: "24rem",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  },
  potionItem: {
    padding: "0.75rem",
    borderRadius: "0.5rem",
    border: "2px solid #E5E7EB",
    cursor: "pointer",
    transition: "all 0.2s",
    backgroundColor: "transparent",
  },
  potionItemSelected: {
    borderColor: "#6366F1",
    backgroundColor: "#F3F4F6",
  },
  potionItemHover: {
    borderColor: "#D1D5DB",
    backgroundColor: "#F9FAFB",
  },
  potionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "0.5rem",
  },
  potionName: {
    fontWeight: "600",
    color: "#1F2937",
    fontSize: "1rem",
  },
  potionMeta: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  potionYear: {
    fontSize: "0.75rem",
    color: "#6B7280",
  },
  rarityBadge: {
    fontSize: "0.75rem",
    padding: "0.125rem 0.5rem",
    borderRadius: "0.375rem",
    color: "#FFFFFF",
    fontWeight: "500",
  },
  potionDescription: {
    fontSize: "0.875rem",
    color: "#6B7280",
    lineHeight: "1.4",
  },
  brewingInterface: {
    display: "flex",
    flexDirection: "column",
    gap: "1.5rem",
  },
  selectedPotionCard: {
    padding: "1rem",
    borderRadius: "0.5rem",
    boxShadow: "inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)",
    background: "linear-gradient(135deg, #6366F1 0%, #8B5CF6 100%)",
    color: "#FFFFFF",
  },
  selectedPotionTitle: {
    fontSize: "1.25rem",
    fontWeight: "600",
    marginBottom: "0.5rem",
  },
  selectedPotionDescription: {
    fontSize: "0.875rem",
    marginBottom: "0.75rem",
    opacity: 0.9,
  },
  dcGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "0.5rem",
    fontSize: "0.75rem",
  },
  dcItem: {
    padding: "0.5rem",
    borderRadius: "0.375rem",
    textAlign: "center",
  },
  dcItemAchievable: {
    backgroundColor: "rgba(0, 0, 0, 0.3)",
  },
  dcItemUnachievable: {
    backgroundColor: "#6B7280",
    opacity: 0.5,
  },
  dcQuality: {
    fontWeight: "500",
    textTransform: "capitalize",
    marginBottom: "0.25rem",
  },
  brewButton: {
    width: "100%",
    padding: "1rem 1.5rem",
    borderRadius: "0.5rem",
    transition: "all 0.2s",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.75rem",
    fontWeight: "600",
    fontSize: "1.125rem",
    color: "#FFFFFF",
    border: "none",
    cursor: "pointer",
    background: "linear-gradient(135deg, #6366F1 0%, #8B5CF6 100%)",
  },
  brewButtonDisabled: {
    opacity: 0.5,
    cursor: "not-allowed",
  },
  resultCard: {
    padding: "1rem",
    borderRadius: "0.5rem",
    boxShadow: "inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)",
    border: "1px solid #E5E7EB",
    backgroundColor: "#FFFFFF",
  },
  resultTitle: {
    fontSize: "1.125rem",
    fontWeight: "600",
    marginBottom: "0.75rem",
    color: "#1F2937",
  },
  resultGrid: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
  },
  resultRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  resultLabel: {
    fontWeight: "500",
    color: "#1F2937",
  },
  resultValue: {
    color: "#6B7280",
  },
  diceResult: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  diceValue: {
    fontSize: "1.25rem",
    fontWeight: "bold",
    color: "#1F2937",
  },
  qualityResult: {
    fontWeight: "bold",
    textTransform: "capitalize",
    display: "flex",
    alignItems: "center",
    gap: "0.25rem",
  },
  qualitySuperior: {
    color: "#8B5CF6",
  },
  qualityExceptional: {
    color: "#3B82F6",
  },
  qualityNormal: {
    color: "#10B981",
  },
  qualityFlawed: {
    color: "#F59E0B",
  },
  qualityRuined: {
    color: "#EF4444",
  },
  resultTimestamp: {
    fontSize: "0.75rem",
    textAlign: "center",
    paddingTop: "0.5rem",
    borderTop: "1px solid #E5E7EB",
    color: "#6B7280",
  },
  referenceGrid: {
    marginTop: "1.5rem",
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(400px, 1fr))",
    gap: "1.5rem",
  },
  referenceTable: {
    fontSize: "0.75rem",
  },
  referenceTableHeader: {
    display: "grid",
    gridTemplateColumns: "2fr repeat(4, 1fr)",
    gap: "0.25rem",
    marginBottom: "0.5rem",
    fontWeight: "bold",
    color: "#1F2937",
  },
  referenceTableRow: {
    display: "grid",
    gridTemplateColumns: "2fr repeat(4, 1fr)",
    gap: "0.25rem",
    marginBottom: "0.25rem",
    color: "#6B7280",
  },
  referenceTableRowHeader: {
    textTransform: "capitalize",
    fontWeight: "500",
  },
  ingredientEffectsList: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    fontSize: "0.875rem",
  },
  ingredientEffectRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  ingredientEffectLabel: {
    fontWeight: "500",
    color: "#1F2937",
  },
  ingredientEffectValue: {
    color: "#6B7280",
  },
  ingredientEffectEasier: {
    color: "#10B981",
  },
  ingredientEffectHarder: {
    color: "#EF4444",
  },
};

export const createThemedPotionStyles = (theme) => ({
  container: {
    maxWidth: "112rem",
    margin: "0 auto",
    padding: "1.5rem",
    background:
      theme.gradient ||
      `linear-gradient(135deg, ${theme.primary} 0%, ${theme.secondary} 100%)`,
    borderRadius: "0.75rem",
    boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
    border: `2px solid ${theme.border}`,
    color: theme.text,
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    transition: "all 0.3s ease",
  },
  title: {
    fontSize: "1.875rem",
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: "1.5rem",
    fontFamily: "serif",
    color: theme.text,
  },
  themeControls: {
    marginBottom: "1.5rem",
    display: "flex",
    flexWrap: "wrap",
    gap: "1rem",
    justifyContent: "center",
  },
  themeControlGroup: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  themeLabel: {
    fontSize: "0.875rem",
    fontWeight: "500",
    color: theme.text,
  },
  themeSelect: {
    padding: "0.25rem 0.75rem",
    borderRadius: "0.375rem",
    border: `1px solid ${theme.border}`,
    backgroundColor: theme.surface,
    color: theme.text,
    fontSize: "0.875rem",
    cursor: "pointer",
    outline: "none",
    transition: "all 0.2s",
  },
  card: {
    padding: "1rem",
    borderRadius: "0.5rem",
    boxShadow: "inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)",
    border: `1px solid ${theme.border}`,
    backgroundColor: theme.surface,
    marginBottom: "1.5rem",
    transition: "all 0.3s ease",
  },
  cardTitle: {
    fontSize: "1.125rem",
    fontWeight: "600",
    marginBottom: "0.75rem",
    color: theme.text,
  },
  controlsContainer: {
    display: "flex",
    gap: "1rem",
    marginBottom: "1.5rem",
  },
  button: {
    padding: "0.5rem 1rem",
    borderRadius: "0.375rem",
    transition: "all 0.2s",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    fontWeight: "500",
    cursor: "pointer",
    border: "none",
    outline: "none",
  },
  primaryButton: {
    backgroundColor: theme.primary,
    color: "#FFFFFF",
  },
  primaryButtonHover: {
    backgroundColor: theme.secondary,
  },
  successButton: {
    backgroundColor: "#10B981",
    color: "#FFFFFF",
  },
  dangerButton: {
    backgroundColor: "#EF4444",
    color: "#FFFFFF",
  },
  secondaryButton: {
    backgroundColor: "#6B7280",
    color: "#FFFFFF",
  },
  proficiencyGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: "1.5rem",
  },
  proficiencySection: {
    marginBottom: "1rem",
  },
  proficiencyTitle: {
    fontWeight: "500",
    marginBottom: "0.75rem",
    color: theme.textSecondary,
  },
  inputGroup: {
    marginBottom: "0.75rem",
  },
  inputLabel: {
    display: "block",
    fontSize: "0.875rem",
    fontWeight: "500",
    marginBottom: "0.25rem",
    color: theme.textSecondary,
  },
  select: {
    width: "100%",
    padding: "0.5rem 0.75rem",
    border: `1px solid ${theme.border}`,
    borderRadius: "0.375rem",
    backgroundColor: theme.surface,
    color: theme.text,
    fontSize: "0.875rem",
    outline: "none",
    transition: "all 0.2s",
  },
  checkboxGroup: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    fontSize: "0.875rem",
    color: theme.textSecondary,
    cursor: "pointer",
  },
  maxQualityInfo: {
    marginTop: "0.75rem",
    padding: "0.5rem",
    borderRadius: "0.375rem",
    fontSize: "0.875rem",
    backgroundColor: theme.background,
    color: theme.textSecondary,
  },
  searchContainer: {
    display: "flex",
    gap: "1rem",
    marginBottom: "1rem",
  },
  searchInputContainer: {
    flex: 1,
    position: "relative",
  },
  searchIcon: {
    position: "absolute",
    left: "0.75rem",
    top: "50%",
    transform: "translateY(-50%)",
    color: theme.textSecondary,
  },
  searchInput: {
    width: "100%",
    paddingLeft: "2.5rem",
    paddingRight: "1rem",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    border: `1px solid ${theme.border}`,
    borderRadius: "0.375rem",
    backgroundColor: theme.surface,
    color: theme.text,
    outline: "none",
    transition: "all 0.2s",
  },
  mainGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(500px, 1fr))",
    gap: "1.5rem",
  },
  potionList: {
    maxHeight: "24rem",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  },
  potionItem: {
    padding: "0.75rem",
    borderRadius: "0.5rem",
    border: `2px solid ${theme.border}`,
    cursor: "pointer",
    transition: "all 0.2s",
    backgroundColor: "transparent",
  },
  potionItemSelected: {
    borderColor: theme.primary,
    backgroundColor: theme.background,
  },
  potionItemHover: {
    borderColor: theme.textSecondary,
    backgroundColor: theme.background,
  },
  potionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "0.5rem",
  },
  potionName: {
    fontWeight: "600",
    color: theme.text,
    fontSize: "1rem",
  },
  potionMeta: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  potionYear: {
    fontSize: "0.75rem",
    color: theme.textSecondary,
  },
  rarityBadge: {
    fontSize: "0.75rem",
    padding: "0.125rem 0.5rem",
    borderRadius: "0.375rem",
    color: "#FFFFFF",
    fontWeight: "500",
  },
  potionDescription: {
    fontSize: "0.875rem",
    color: theme.textSecondary,
    lineHeight: "1.4",
  },
  brewingInterface: {
    display: "flex",
    flexDirection: "column",
    gap: "1.5rem",
  },
  selectedPotionCard: {
    padding: "1rem",
    borderRadius: "0.5rem",
    boxShadow: "inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)",
    background:
      theme.gradient ||
      `linear-gradient(135deg, ${theme.primary} 0%, ${theme.secondary} 100%)`,
    color: "#FFFFFF",
  },
  selectedPotionTitle: {
    fontSize: "1.25rem",
    fontWeight: "600",
    marginBottom: "0.5rem",
  },
  selectedPotionDescription: {
    fontSize: "0.875rem",
    marginBottom: "0.75rem",
    opacity: 0.9,
  },
  dcGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "0.5rem",
    fontSize: "0.75rem",
  },
  dcItem: {
    padding: "0.5rem",
    borderRadius: "0.375rem",
    textAlign: "center",
  },
  dcItemAchievable: {
    backgroundColor: "rgba(0, 0, 0, 0.3)",
  },
  dcItemUnachievable: {
    backgroundColor: "#6B7280",
    opacity: 0.5,
  },
  dcQuality: {
    fontWeight: "500",
    textTransform: "capitalize",
    marginBottom: "0.25rem",
  },
  brewButton: {
    width: "100%",
    padding: "1rem 1.5rem",
    borderRadius: "0.5rem",
    transition: "all 0.2s",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.75rem",
    fontWeight: "600",
    fontSize: "1.125rem",
    color: "#FFFFFF",
    border: "none",
    cursor: "pointer",
    background:
      theme.gradient ||
      `linear-gradient(135deg, ${theme.primary} 0%, ${theme.secondary} 100%)`,
  },
  brewButtonDisabled: {
    opacity: 0.5,
    cursor: "not-allowed",
  },
  resultCard: {
    padding: "1rem",
    borderRadius: "0.5rem",
    boxShadow: "inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)",
    border: `1px solid ${theme.border}`,
    backgroundColor: theme.surface,
  },
  resultTitle: {
    fontSize: "1.125rem",
    fontWeight: "600",
    marginBottom: "0.75rem",
    color: theme.text,
  },
  resultGrid: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
  },
  resultRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  resultLabel: {
    fontWeight: "500",
    color: theme.text,
  },
  resultValue: {
    color: theme.textSecondary,
  },
  diceResult: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  diceValue: {
    fontSize: "1.25rem",
    fontWeight: "bold",
    color: theme.text,
  },
  qualityResult: {
    fontWeight: "bold",
    textTransform: "capitalize",
    display: "flex",
    alignItems: "center",
    gap: "0.25rem",
  },
  qualitySuperior: {
    color: "#8B5CF6",
  },
  qualityExceptional: {
    color: "#3B82F6",
  },
  qualityNormal: {
    color: "#10B981",
  },
  qualityFlawed: {
    color: "#F59E0B",
  },
  qualityRuined: {
    color: "#EF4444",
  },
  resultTimestamp: {
    fontSize: "0.75rem",
    textAlign: "center",
    paddingTop: "0.5rem",
    borderTop: `1px solid ${theme.border}`,
    color: theme.textSecondary,
  },
  referenceGrid: {
    marginTop: "1.5rem",
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(400px, 1fr))",
    gap: "1.5rem",
  },
  referenceTable: {
    fontSize: "0.75rem",
  },
  referenceTableHeader: {
    display: "grid",
    gridTemplateColumns: "2fr repeat(4, 1fr)",
    gap: "0.25rem",
    marginBottom: "0.5rem",
    fontWeight: "bold",
    color: theme.text,
  },
  referenceTableRow: {
    display: "grid",
    gridTemplateColumns: "2fr repeat(4, 1fr)",
    gap: "0.25rem",
    marginBottom: "0.25rem",
    color: theme.textSecondary,
  },
  referenceTableRowHeader: {
    textTransform: "capitalize",
    fontWeight: "500",
  },
  ingredientEffectsList: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    fontSize: "0.875rem",
  },
  ingredientEffectRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  ingredientEffectLabel: {
    fontWeight: "500",
    color: theme.text,
  },
  ingredientEffectValue: {
    color: theme.textSecondary,
  },
  ingredientEffectEasier: {
    color: "#10B981",
  },
  ingredientEffectHarder: {
    color: "#EF4444",
  },
  rarityColors: {
    common: "#6B7280", // Gray
    uncommon: "#10B981", // Green
    rare: "#3B82F6", // Blue
    "very rare": "#8B5CF6", // Purple
    legendary: "#F59E0B", // Orange
  },
});

export default styles;
