// src/App/style.js - Updated with Theme Support
// Original static styles (for backward compatibility)
export const styles = {
  appContainer: {
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  appHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "1rem",
    backgroundColor: "#f8f9fa",
    borderBottom: "1px solid #dee2e6",
  },
  tabNavigation: {
    display: "flex",
    gap: "0.5rem",
  },
  tabButton: {
    padding: "0.5rem 1rem",
    border: "1px solid #dee2e6",
    borderRadius: "0.25rem",
    backgroundColor: "#fff",
    color: "#495057",
    cursor: "pointer",
    transition: "all 0.2s",
    fontWeight: "500",
  },
  tabButtonActive: {
    backgroundColor: "#007bff",
    color: "#fff",
    borderColor: "#007bff",
  },
  tabButtonHover: {
    backgroundColor: "#e9ecef",
    borderColor: "#adb5bd",
  },
  authSection: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
  },
  userInfo: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    position: "relative",
  },
  userAvatar: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    border: "2px solid #007bff",
  },
  username: {
    fontWeight: "500",
    color: "#333",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  editButton: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "2px",
    borderRadius: "3px",
    color: "#6c757d",
    transition: "color 0.2s",
  },
  editButtonHover: {
    color: "#007bff",
    backgroundColor: "#f8f9fa",
  },
  usernameEditor: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  usernameInput: {
    padding: "4px 8px",
    border: "1px solid #dee2e6",
    borderRadius: "4px",
    fontSize: "14px",
    width: "120px",
  },
  saveButton: {
    background: "#28a745",
    color: "white",
    border: "none",
    borderRadius: "3px",
    padding: "4px 6px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
  },
  cancelButton: {
    background: "#dc3545",
    color: "white",
    border: "none",
    borderRadius: "3px",
    padding: "4px 6px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
  },
  authButton: {
    padding: "0.5rem 1rem",
    border: "none",
    borderRadius: "0.25rem",
    fontWeight: "500",
    cursor: "pointer",
    transition: "background-color 0.2s",
    minWidth: "80px",
  },
  authButtonDisabled: {
    opacity: 0.6,
    cursor: "not-allowed",
  },
  signinButton: {
    backgroundColor: "#5865f2",
    color: "white",
  },
  signinButtonHover: {
    backgroundColor: "#4752c4",
  },
  signoutButton: {
    backgroundColor: "#dc3545",
    color: "white",
  },
  signoutButtonHover: {
    backgroundColor: "#c82333",
  },
  authRequired: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "2rem",
    textAlign: "center",
    minHeight: "300px",
  },
  authRequiredH2: {
    color: "#495057",
    marginBottom: "1rem",
  },
  authRequiredP: {
    color: "#6c757d",
  },
  loadingSpinner: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100vh",
    fontSize: "1.2rem",
    color: "#6c757d",
  },
  tabContent: {
    flex: 1,
  },
  homePage: {
    padding: "2rem",
  },
  heroSection: {
    textAlign: "center",
    marginBottom: "3rem",
    color: "#eee",
  },
  featureGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
  },
  featureCard: {
    padding: "1.5rem",
    border: "1px solid #dee2e6",
    borderRadius: "0.5rem",
    backgroundColor: "#fff",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
    color: "#000",
    cursor: "pointer",
    transition: "all 0.3s ease",
    position: "relative",
    margin: "8px",
  },
  featureCardHover: {
    transform: "translateY(-2px)",
    boxShadow: "0 4px 12px rgba(0,0,0,0.15)",
    borderColor: "#007bff",
  },
  cardButton: {
    marginTop: "1rem",
    padding: "0.75rem 1rem",
    backgroundColor: "#007bff",
    color: "white",
    borderRadius: "0.25rem",
    textAlign: "center",
    fontWeight: "500",
    fontSize: "14px",
    transition: "background-color 0.2s",
  },
  errorMessage: {
    color: "#dc3545",
    fontSize: "12px",
    marginTop: "4px",
  },
  discordName: {
    fontSize: "12px",
    color: "#6c757d",
    fontStyle: "italic",
  },
};

// New themed styles function
export const createThemedStyles = (theme) => ({
  appContainer: {
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    backgroundColor: theme.background,
    color: theme.text,
    minHeight: "100vh",
    transition: "background-color 0.3s ease, color 0.3s ease",
  },
  appHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "1rem",
    backgroundColor: theme.headerBackground || theme.primary,
    borderBottom: `1px solid ${theme.border}`,
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
    color: theme.surface,
  },
  tabNavigation: {
    display: "flex",
    gap: "0.5rem",
  },
  tabButton: {
    padding: "0.5rem 1rem",
    border: `1px solid ${theme.border}`,
    borderRadius: "0.25rem",
    backgroundColor: theme.surface,
    color: theme.text,
    cursor: "pointer",
    transition: "all 0.2s",
    fontWeight: "500",
  },
  tabButtonActive: {
    backgroundColor: theme.primary,
    color: theme.surface,
    borderColor: theme.primary,
  },
  tabButtonHover: {
    backgroundColor: theme.background,
    borderColor: theme.primary,
  },
  authSection: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
  },
  userInfo: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    position: "relative",
  },
  userAvatar: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    border: `2px solid ${theme.accent}`,
  },
  username: {
    fontWeight: "500",
    color: theme.surface,
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  editButton: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "2px",
    borderRadius: "3px",
    color: theme.surface,
    opacity: 0.8,
    transition: "all 0.2s",
  },
  editButtonHover: {
    color: theme.surface,
    backgroundColor: "rgba(255,255,255,0.1)",
    opacity: 1,
  },
  usernameEditor: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  usernameInput: {
    padding: "4px 8px",
    border: `1px solid ${theme.border}`,
    borderRadius: "4px",
    fontSize: "14px",
    width: "120px",
    backgroundColor: theme.surface,
    color: theme.text,
  },
  saveButton: {
    background: theme.success,
    color: "white",
    border: "none",
    borderRadius: "3px",
    padding: "4px 6px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
  },
  cancelButton: {
    background: theme.error,
    color: "white",
    border: "none",
    borderRadius: "3px",
    padding: "4px 6px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
  },
  authButton: {
    padding: "0.5rem 1rem",
    border: "none",
    borderRadius: "0.25rem",
    fontWeight: "500",
    cursor: "pointer",
    transition: "background-color 0.2s",
    minWidth: "80px",
  },
  authButtonDisabled: {
    opacity: 0.6,
    cursor: "not-allowed",
  },
  signinButton: {
    backgroundColor: theme.text,
    color: "white",
  },
  signinButtonHover: {
    backgroundColor: "#4752c4",
  },
  signoutButton: {
    backgroundColor: theme.error,
    color: "white",
  },
  signoutButtonHover: {
    backgroundColor: "#c82333",
  },
  authRequired: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "2rem",
    textAlign: "center",
    minHeight: "300px",
    backgroundColor: theme.surface,
    borderRadius: "12px",
    border: `2px solid ${theme.border}`,
    margin: "20px",
  },
  authRequiredH2: {
    color: theme.text,
    marginBottom: "1rem",
  },
  authRequiredP: {
    color: theme.textSecondary,
  },
  loadingSpinner: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100vh",
    fontSize: "1.2rem",
    color: theme.textSecondary,
    backgroundColor: theme.background,
  },
  tabContent: {
    flex: 1,
    backgroundColor: theme.background,
  },
  homePage: {
    padding: "2rem",
    backgroundColor: theme.background,
  },
  heroSection: {
    textAlign: "center",
    marginBottom: "3rem",
    color: theme.text,
  },
  featureGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: "1.5rem",
    marginBottom: "2rem",
  },
  featureCard: {
    padding: "1.5rem",
    border: `1px solid ${theme.border}`,
    borderRadius: "0.5rem",
    backgroundColor: theme.cardBackground,
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
    color: theme.text,
    cursor: "pointer",
    transition: "all 0.3s ease",
    position: "relative",
    margin: "8px",
  },
  featureCardHover: {
    transform: "translateY(-2px)",
    boxShadow: "0 4px 12px rgba(0,0,0,0.15)",
    borderColor: theme.primary,
  },
  cardButton: {
    marginTop: "1rem",
    padding: "0.75rem 1rem",
    backgroundColor: theme.primary,
    color: theme.surface,
    borderRadius: "0.25rem",
    textAlign: "center",
    fontWeight: "500",
    fontSize: "14px",
    transition: "background-color 0.2s",
    border: "none",
    cursor: "pointer",
    width: "100%",
  },
  errorMessage: {
    color: theme.error,
    fontSize: "12px",
    marginTop: "4px",
  },
  discordName: {
    fontSize: "12px",
    color: theme.textSecondary,
    fontStyle: "italic",
  },
  // Additional theme-specific styles
  themeButton: {
    padding: "0.5rem",
    backgroundColor: theme.surface,
    border: `1px solid ${theme.border}`,
    borderRadius: "0.25rem",
    cursor: "pointer",
    transition: "all 0.2s",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginRight: "1rem",
  },
  themeButtonHover: {
    backgroundColor: theme.background,
    borderColor: theme.primary,
  },
});
