export const styles = {
  characterSection: {
    backgroundColor: "white",
    borderRadius: "0.5rem",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    border: "1px solid #e5e7eb",
    padding: "1.5rem",
    marginBottom: "2rem",
  },
  characterHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "1rem",
  },
  characterSelect: {
    padding: "0.5rem 1rem",
    borderRadius: "0.375rem",
    border: "1px solid #d1d5db",
    fontSize: "1rem",
    minWidth: "200px",
  },
  characterButton: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    padding: "0.5rem 1rem",
    backgroundColor: "#3b82f6",
    color: "white",
    border: "none",
    borderRadius: "0.375rem",
    fontSize: "0.875rem",
    cursor: "pointer",
    transition: "background-color 0.2s",
  },
  characterForm: {
    display: "flex",
    gap: "1rem",
    alignItems: "center",
    marginTop: "1rem",
    padding: "1rem",
    backgroundColor: "#f9fafb",
    borderRadius: "0.375rem",
  },
  characterInput: {
    padding: "0.5rem",
    borderRadius: "0.375rem",
    border: "1px solid #d1d5db",
    fontSize: "1rem",
    minWidth: "200px",
  },
  statsContainer: {
    display: "flex",
    justifyContent: "center",
    gap: "2rem",
    fontSize: "0.875rem",
    flexWrap: "wrap",
    marginBottom: "2rem",
    padding: "1.5rem",
    backgroundColor: "white",
    borderRadius: "0.5rem",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    border: "1px solid #e5e7eb",
  },
  statItem: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  statDot: {
    width: "0.75rem",
    height: "0.75rem",
    borderRadius: "50%",
  },
  subjectsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(600px, max-content))",
    gap: "2rem",
    marginBottom: "2rem",
    alignItems: "start",
  },
  subjectCard: {
    backgroundColor: "white",
    borderRadius: "1rem",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    border: "1px solid #e5e7eb",
    overflow: "hidden",
    transition: "all 0.2s ease",
  },
  subjectHeader: {
    padding: "1.5rem",
    borderBottom: "1px solid #e5e7eb",
  },
  subjectTitleContainer: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
    marginBottom: "0.5rem",
  },
  subjectTitle: {
    fontSize: "1.5rem",
    fontWeight: "bold",
    margin: 0,
  },
  subjectDescription: {
    fontSize: "0.875rem",
    color: "#6b7280",
    marginBottom: "1rem",
  },
  subjectStats: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "1rem",
    fontSize: "0.875rem",
  },
  subjectStatItem: {
    textAlign: "center",
    padding: "0.75rem",
    backgroundColor: "#f9fafb",
    borderRadius: "0.5rem",
  },
  subjectStatNumber: {
    fontSize: "1.25rem",
    fontWeight: "bold",
    display: "block",
  },
  subjectStatLabel: {
    color: "#6b7280",
    fontSize: "0.75rem",
  },
  subjectContent: {
    padding: "1.5rem",
  },
  progressCard: {
    backgroundColor: "white",
    borderRadius: "0.5rem",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    border: "1px solid #e5e7eb",
    padding: "1.5rem",
    marginBottom: "2rem",
  },
  progressTitle: {
    fontSize: "1.25rem",
    fontWeight: "600",
    color: "#374151",
    marginBottom: "1rem",
  },
  progressBar: {
    width: "100%",
    backgroundColor: "#e5e7eb",
    borderRadius: "9999px",
    height: "1rem",
    marginBottom: "1rem",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    background: "linear-gradient(90deg, #3b82f6 0%, #10b981 100%)",
    borderRadius: "9999px",
    transition: "width 0.5s ease",
  },
  progressStats: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: "0.875rem",
    color: "#6b7280",
  },
  sectionContainer: {
    marginBottom: "1rem",
  },
  sectionButton: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "1rem",
    borderRadius: "0.5rem",
    border: "2px solid",
    cursor: "pointer",
    transition: "all 0.2s ease",
    fontSize: "1rem",
    fontWeight: "600",
  },
  sectionButtonHover: {
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
  },
  sectionLeft: {
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
  },
  sectionRight: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
  },
  sectionProgress: {
    width: "4rem",
    backgroundColor: "rgba(255, 255, 255, 0.5)",
    borderRadius: "9999px",
    height: "0.5rem",
    overflow: "hidden",
  },
  sectionProgressFill: {
    height: "100%",
    backgroundColor: "currentColor",
    borderRadius: "9999px",
    transition: "width 0.3s ease",
  },
  table: {
    width: "100%",
    backgroundColor: "white",
    borderRadius: "0.5rem",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    border: "1px solid #e5e7eb",
    marginTop: "0.5rem",
    overflow: "hidden",
  },
  tableHeader: {
    backgroundColor: "#f9fafb",
  },
  tableHeaderCell: {
    padding: "0.75rem 1rem",
    textAlign: "left",
    fontSize: "0.75rem",
    fontWeight: "500",
    color: "#6b7280",
    textTransform: "uppercase",
    borderBottom: "1px solid #e5e7eb",
  },
  tableHeaderCellCenter: {
    padding: "0.75rem 1rem",
    textAlign: "center",
    fontSize: "0.75rem",
    fontWeight: "500",
    color: "#6b7280",
    textTransform: "uppercase",
    borderBottom: "1px solid #e5e7eb",
  },
  tableRow: {
    borderBottom: "1px solid #f3f4f6",
    transition: "background-color 0.2s ease",
  },
  tableRowHover: {
    backgroundColor: "#f9fafb",
  },
  tableRowMastered: {
    backgroundColor: "#fefce8",
  },
  tableCell: {
    padding: "0.75rem 1rem",
    fontSize: "0.875rem",
    color: "#6b7280",
  },
  spellNameContainer: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  spellName: {
    fontWeight: "500",
    color: "#374151",
  },
  spellNameMastered: {
    fontWeight: "500",
    color: "#92400e",
  },
  masteredBadge: {
    padding: "0.25rem 0.5rem",
    backgroundColor: "#fcd34d",
    color: "#92400e",
    fontSize: "0.75rem",
    borderRadius: "9999px",
    fontWeight: "600",
  },
  attemptsContainer: {
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
  },
  attemptButton: {
    display: "flex",
    alignItems: "center",
    gap: "0.25rem",
    padding: "0.375rem 0.75rem",
    backgroundColor: "#3b82f6",
    color: "white",
    border: "none",
    borderRadius: "0.375rem",
    fontSize: "0.75rem",
    fontWeight: "500",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  attemptButtonHover: {
    backgroundColor: "#2563eb",
    transform: "translateY(-1px)",
  },
  attemptButtonDisabled: {
    backgroundColor: "#9ca3af",
    cursor: "not-allowed",
    transform: "none",
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    cursor: "pointer",
  },
  checkbox: {
    width: "1rem",
    height: "1rem",
    borderRadius: "0.25rem",
  },
  checkboxText: {
    fontSize: "0.875rem",
    color: "#6b7280",
  },
  legendCard: {
    backgroundColor: "white",
    borderRadius: "0.5rem",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    border: "1px solid #e5e7eb",
    padding: "1.5rem",
  },
  legendTitle: {
    fontSize: "1.125rem",
    fontWeight: "600",
    color: "#374151",
    marginBottom: "1rem",
  },
  legendGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))",
    gap: "1rem",
    fontSize: "0.875rem",
  },
  legendItem: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
};
