export const spellsData = {
  Charms: {
    icon: "Wand2",
    color: "#3b82f6",
    description: "Utility and enhancement magic",
    levels: {
      Cantrips: [
        "Accio",
        "Alohomora",
        "Capto",
        "Carpe Retractum",
        "Cistem Aperio",
        "Colloportus",
        "Colovaria",
        "Defodio",
        "Duro",
        "Finestra",
        "Flagrate",
        "Glisseo",
        "Illegibilus",
        "Impervius",
        "Lumos/Nox",
        "Molliare",
        "Pereo",
        "Periculum/Verdimillious",
        "Scourgify",
        "Sonorus/Quietus",
        "Spongify",
        "Tergeo",
        "Wingardium Leviosa",
      ],
      "1st Level": [
        "Arresto Momentum",
        "Diffindo R",
        "Exhilaro R",
        "Glacius R",
        "Locomotor R",
        "Mobilicorpus R",
        "Perfusorius R",
        "Protego",
        "Reducio R",
        "Rictusempra",
        "Riddikulus",
        "Vigilatus R",
        "Abscondi R",
        "Diminuendo",
        "Engorgio R",
        "Expelliarmus",
        "Finite Incantatem",
        "Fumos",
        "Geminio R",
        "Immobulus",
        "Muffliato*",
        "Partis Temporus",
        "Pellucidi Pellis",
        "Protego Maxima",
        "Reparo R",
        "Silencio R",
        "Stupefy",
      ],
      "3rd Level": [
        "Deprimo R",
        "Depulso",
        "Dissonus Ululatus",
        "Expecto Patronum R",
        "Fianto Duri",
        "Fortissimum",
        "Herbivicus",
        "Lumos Maxima R",
        "Novum Spirare R",
        "Repello Inimicum",
      ],
      "4th Level": ["Capacious Extremis*", "Confundo R", "Repello Muggletum R"],
      "5th Level": [
        "Cave Inimicum",
        "Ne Ustio",
        "Obliviate*",
        "Piertotum Locomotor*",
        "Salvio Hexia",
      ],
      "6th Level": ["Protego Totalum*"],
      "9th Level": ["Fidelius Mysteria Celare*"],
    },
  },
  "Jinxes, Hexes & Curses": {
    icon: "Zap",
    color: "#dc2626",
    description: "Offensive and mischievous magic",
    levels: {
      Cantrips: [
        "Bombarda",
        "Cantis",
        "Devicto",
        "Furnunculus",
        "Genu Recurvatum",
        "Infirma Cerebra",
        "Locomotor Wibbly",
      ],
      "1st Level": [
        "Colloshoo",
        "Densaugeo",
        "Digitus Wibbly",
        "Flipendo",
        "Locomotor Mortis",
        "Mimblewimble",
        "Petrificus Totalus",
      ],
      "2nd Level": [
        "Arania Exumai",
        "Oppugno",
        "Relashio",
        "Slugulus Eructo",
        "Tarantallegra",
        "Ventus R",
      ],
      "3rd Level": [
        "Confringo",
        "Conjunctivia",
        "Expulso",
        "Impedimenta",
        "Langlock*",
      ],
      "4th Level": [
        "Levicorpus/Liberacorpus",
        "Muco Volatilis",
        "Reducto",
        "Sectumsempra*",
      ],
      "5th Level": ["Imperio", "Nullum Effugium*", "Omnifracto*"],
      "7th Level": ["Azreth", "Crucio"],
      "8th Level": ["Avada Kedavra"],
    },
  },
  Transfigurations: {
    icon: "BookOpen",
    color: "#10b981",
    description: "Transformation and alteration magic",
    levels: {
      Cantrips: [
        "Aguamenti",
        "Crinus Muto",
        "Epoximise",
        "Incendio Glacia",
        "Orchideous",
        "Vera Verto",
      ],
      "1st Level": [
        "Inanimatus Conjurus R",
        "Incendio R",
        "Nebulus",
        "Obscuro R",
        "Sagittario",
      ],
      "2nd Level": ["Incarcerous R", "Orbis*", "Reparifarge*", "Serpensortia"],
      "3rd Level": ["Avis", "Evanesco", "Ignis Laquis*", "Melofors"],
      "4th Level": ["Ebublio R", "Lapifors*"],
      "5th Level": ["Draconifors", "Transmogrify"],
      "6th Level": ["Ignis Furore"],
    },
  },
  Elemental: {
    icon: "Zap",
    color: "#f59e0b",
    description: "Mastery over the elements",
    levels: {
      Cantrips: ["Incendio Ruptis*"],
      "1st Level": ["Diffindo Glacia*", "Intonuit Fluctus*"],
      "3rd Level": ["Fulgur*", "Respersio*"],
      "4th Level": ["Glacius Maxima*"],
      "8th Level": ["Tempestus*"],
      "9th Level": ["Fulgur Maxima*"],
    },
  },
  Valiant: {
    icon: "Shield",
    color: "#8b5cf6",
    description: "Combat and valor magic",
    levels: {
      Cantrips: ["Magno*"],
      "1st Level": [
        "Clario*",
        "Ignis Ictus*",
        "Irus Ictus*",
        "Pererro*",
        "Tonitrus Ictus*",
      ],
      "2nd Level": ["Notam Ictus*"],
      "3rd Level": ["Inanus Ictus*"],
      "4th Level": ["Titubo Ictus*"],
      "5th Level": ["Clario Maxima*"],
    },
  },
  Divinations: {
    icon: "Eye",
    color: "#ec4899",
    description: "Sight beyond sight and knowledge magic",
    levels: {
      Cantrips: ["Mumblio*", "Point Me", "Prior Incantato"],
      "1st Level": [
        "Linguarium R",
        "Luxus Manus R",
        "Martem*",
        "Motus Revelio",
        "Specialis Revelio",
        "Venenum Revelio R",
      ],
      "2nd Level": [
        "Absconditus Revelio",
        "Facultatem*",
        "Inanimatus Revelio",
        "Secundio",
      ],
      "3rd Level": [
        "Annotatem",
        "Legilimens*",
        "Linguarium Maxima",
        "Mumblio Maxima*",
        "Revelio",
      ],
      "4th Level": [
        "Appare Vestigium R",
        "Creatura Revelio",
        "Homenum Revelio",
        "Oculus Speculatem",
      ],
      "5th Level": ["Annotatem Maxima*", "Augurium R", "Mumblio Totalum R*"],
      "6th Level": ["Invenire Viam*", "Verum Aspectum"],
      "9th Level": ["Providentum*"],
    },
  },
  Healing: {
    icon: "Heart",
    color: "#ef4444",
    description: "Restoration and medical magic",
    levels: {
      Cantrips: ["Anapneo*", "Rennervate"],
      "1st Level": ["Episkey", "Ferula", "Reparifors"],
      "2nd Level": ["Adversus Interitus R*"],
      "3rd Level": ["Aculeo Sanentur*", "Animatem*", "Intus Sunt R*"],
      "4th Level": ["Brackium Emendo"],
      "5th Level": ["Pervivo*"],
      "6th Level": ["Vulnera Sanentur*"],
      "7th Level": [],
    },
  },
  Magizoo: {
    icon: "PawPrint",
    color: "#059669",
    description: "Beast and creature magic",
    levels: {
      Cantrips: ["Insectum*"],
      "1st Level": ["Beastia Vinculum*", "Beastia Amicatum*"],
      "2nd Level": ["Beastia Nuntium R*", "Beastia Sensibus R*"],
      "3rd Level": ["Obtestor*"],
      "4th Level": ["Imperio Creatura*", "Engorgio Insectum*"],
      "5th Level": ["Insectum Maxima*"],
      "6th Level": ["Natura Incantatem R*"],
      "7th Level": ["Draconiverto*"],
      "8th Level": ["Animato Maxima*"],
    },
  },
  Grim: {
    icon: "Skull",
    color: "#1f2937",
    description: "Dark and fear magic",
    levels: {
      Cantrips: ["Ignis Lunalis*", "Fraudemo*"],
      "1st Level": ["Formidulosus*"],
      "2nd Level": ["Exspiravit*"],
      "3rd Level": ["Fraudemo Maxima*", "Timor"],
      "4th Level": ["Relicuum R*"],
      "6th Level": ["Oculus Malus*"],
      "9th Level": ["Menus Eruptus*"],
    },
  },
};
