export const getStyles = (theme) => ({
  container: {
    padding: "20px",
    maxWidth: "1200px",
    margin: "0 auto",
  },
  hpControlsHeader: {
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "center",
    gap: "12px",
    padding: "12px 16px",
    backgroundColor: theme.surface,
    border: `2px solid ${theme.border}`,
    borderRadius: "8px",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.05)",
  },
  hpContainer: {
    marginTop: "8px",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: "15px",
    marginBottom: "30px",
    borderBottom: `3px solid ${theme.primary}`,
    paddingBottom: "15px",
  },
  title: {
    margin: 0,
    fontSize: "2.5rem",
    color: theme.text,
    textShadow: "2px 2px 4px rgba(0,0,0,0.1)",
  },
  mainGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "30px",
  },
  panel: {
    backgroundColor: theme.surface,
    padding: "25px",
    borderRadius: "12px",
    border: `2px solid ${theme.border}`,
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
  },
  sectionHeader: {
    color: theme.text,
    marginBottom: "20px",
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  fieldContainer: {
    marginBottom: "20px",
  },
  label: {
    display: "block",
    fontWeight: "bold",
    marginBottom: "5px",
    color: theme.text,
  },
  input: {
    width: "100%",
    padding: "10px",
    borderRadius: "6px",
    border: `2px solid ${theme.border}`,
    fontSize: "16px",
    backgroundColor: theme.surface,
    color: theme.text,
  },
  select: {
    width: "100%",
    padding: "10px",
    borderRadius: "6px",
    border: `2px solid ${theme.border}`,
    fontSize: "16px",
    backgroundColor: theme.surface,
    color: theme.text,
  },
  hpCalculation: {
    fontSize: "11px",
    color: theme.textSecondary,
    marginTop: "4px",
    fontStyle: "italic",
    textAlign: "center",
  },
  skillsHeader: {
    color: theme.text,
    marginBottom: "15px",
  },
  skillsPlaceholder: {
    width: "450px",
    height: "42px",
    border: `2px solid ${theme.warning}40`,
    borderRadius: "6px",
    padding: "8px",
    backgroundColor: theme.warning + "20",
    textAlign: "center",
    color: theme.warning,
    fontStyle: "italic",
  },
  HPPlaceholder: {
    border: `2px solid ${theme.warning}40`,
    borderRadius: "6px",
    padding: "15px",
    width: "80px",
    backgroundColor: theme.warning + "20",
    textAlign: "center",
    color: theme.warning,
    fontStyle: "italic",
  },
  skillsContainer: {
    border: `2px solid ${theme.border}`,
    borderRadius: "6px",
    padding: "15px",
    backgroundColor: theme.surface,
  },
  skillsSubheader: {
    color: theme.textSecondary,
    fontSize: "14px",
    fontWeight: "bold",
    marginBottom: "12px",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  skillsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "10px",
  },
  skillOptionBase: {
    display: "flex",
    alignItems: "center",
    padding: "8px",
    borderRadius: "4px",
    backgroundColor: theme.surface,
  },
  skillCheckbox: {
    marginRight: "8px",
  },
  skillsComplete: {
    marginTop: "10px",
    padding: "8px",
    backgroundColor: theme.success + "20",
    borderRadius: "4px",
    border: `1px solid ${theme.success}`,
    color: theme.success,
    fontSize: "12px",
    fontWeight: "bold",
    textAlign: "center",
  },
  helpText: {
    fontSize: "12px",
    color: theme.textSecondary,
    marginTop: "8px",
    fontStyle: "italic",
  },
  abilityScoresHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "15px",
  },
  abilityScoresTitle: {
    color: theme.text,
    margin: 0,
  },
  button: {
    display: "flex",
    alignItems: "center",
    gap: "5px",
    padding: "8px 12px",
    color: "white",
    border: "none",
    borderRadius: "6px",
    fontSize: "14px",
    cursor: "pointer",
    fontWeight: "600",
    transition: "all 0.2s ease",
  },
  buttonGroup: {
    display: "flex",
    gap: "8px",
  },
  availableStats: {
    marginBottom: "15px",
    padding: "10px",
    borderRadius: "6px",
    border: `2px solid ${theme.warning}40`,
    backgroundColor: theme.warning + "20",
  },
  availableStatsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "8px",
  },
  availableStatsLabel: {
    fontWeight: "bold",
    border: `2px solid ${theme.warning}40`,
    borderRadius: "6px",
    padding: "15px",
    backgroundColor: theme.warning + "20",
    textAlign: "center",
    color: theme.warning,
    fontStyle: "italic",
  },
  availableStatsTotal: {
    fontWeight: "bold",
    color: theme.warning,
    fontSize: "16px",
  },
  completeIndicator: {
    color: theme.success,
    marginLeft: "10px",
  },
  statsContainer: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
  },
  statBadge: {
    padding: "4px 8px",
    backgroundColor: theme.warning,
    color: "white",
    borderRadius: "4px",
    fontSize: "14px",
    fontWeight: "bold",
  },
  allAssignedText: {
    color: theme.warning,
    fontStyle: "italic",
  },
  abilityGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "15px",
  },
  abilityCard: {
    border: `2px solid ${theme.border}`,
    borderRadius: "8px",
    padding: "12px",
    textAlign: "center",
    position: "relative",
    minHeight: "120px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    backgroundColor: theme.surface,
  },
  abilityName: {
    fontWeight: "bold",
    fontSize: "12px",
    color: theme.textSecondary,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    marginBottom: "8px",
  },
  abilityModifier: {
    fontSize: "28px",
    fontWeight: "bold",
    color: theme.text,
    margin: "8px 0",
  },
  abilityModifierEmpty: {
    fontSize: "24px",
    fontWeight: "bold",
    color: theme.border,
    margin: "8px 0",
  },
  abilityScoreContainer: {
    position: "relative",
  },
  abilityScore: {
    width: "36px",
    height: "36px",
    borderRadius: "50%",
    backgroundColor: theme.success,
    color: "white",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "bold",
    fontSize: "16px",
    margin: "0 auto",
  },
  trashButton: {
    position: "absolute",
    top: "-6px",
    right: "-6px",
    width: "20px",
    height: "20px",
    padding: "2px",
    backgroundColor: theme.error,
    color: "white",
    border: "none",
    borderRadius: "50%",
    cursor: "pointer",
    fontSize: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  assignSelect: {
    width: "100%",
    padding: "6px",
    borderRadius: "4px",
    border: `2px solid ${theme.border}`,
    fontSize: "12px",
    backgroundColor: theme.surface,
    color: theme.text,
  },
  featOption: {
    display: "flex",
    alignItems: "center",
    marginBottom: "8px",
    cursor: "pointer",
  },
  featText: {
    fontSize: "14px",
    color: theme.text,
  },
  saveButton: {
    width: "100%",
    padding: "12px",
    color: "white",
    border: "none",
    borderRadius: "6px",
    fontSize: "16px",
    fontWeight: "bold",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
  },
  emptyCharacters: {
    textAlign: "center",
    padding: "40px",
    color: theme.textSecondary,
    fontStyle: "italic",
  },
  charactersContainer: {
    maxHeight: "600px",
    overflowY: "auto",
  },
  characterCard: {
    backgroundColor: theme.cardBackground,
    border: `2px solid ${theme.border}`,
    borderRadius: "8px",
    padding: "15px",
    marginBottom: "15px",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.05)",
  },
  characterHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "10px",
  },
  characterName: {
    margin: "0 0 5px 0",
    color: theme.text,
  },
  characterDetails: {
    fontSize: "14px",
    color: theme.textSecondary,
  },
  characterActions: {
    display: "flex",
    gap: "5px",
  },
  actionButton: {
    padding: "6px",
    color: "white",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
  },
  heritage: {
    fontSize: "12px",
    color: theme.success,
    fontWeight: "bold",
  },
  feats: {
    fontSize: "12px",
    color: theme.primary,
    marginTop: "5px",
  },
  skills: {
    fontSize: "12px",
    color: theme.accent,
    marginTop: "5px",
  },
  featFilterContainer: {
    marginBottom: "20px",
    position: "relative",
  },
  featFilterInput: {
    width: "100%",
    padding: "12px 50px 12px 16px",
    borderRadius: "10px",
    border: `3px solid ${theme.warning}`,
    fontSize: "16px",
    backgroundColor: theme.surface,
    marginBottom: "10px",
    fontFamily: "'Cinzel', serif",
    boxShadow: `inset 0 2px 6px ${theme.warning}40, 0 2px 4px rgba(0,0,0,0.1)`,
    transition: "all 0.3s ease",
    color: theme.text,
  },
  featFilterClearButton: {
    position: "absolute",
    right: "15px",
    top: "50%",
    transform: "translateY(-50%)",
    width: "24px",
    height: "24px",
    borderRadius: "50%",
    border: `2px solid ${theme.warning}`,
    backgroundColor: theme.surface,
    color: theme.warning,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "14px",
    fontWeight: "bold",
    transition: "all 0.3s ease",
    boxShadow: "0 2px 4px rgba(0,0,0,0.2)",
    zIndex: 1,
  },
  featFilterClearButtonHover: {
    backgroundColor: theme.surface,
    transform: "translateY(-50%) scale(1.1)",
    boxShadow: "0 3px 6px rgba(0,0,0,0.3)",
  },
  featFilterInputFocus: {
    outline: "none",
    borderColor: theme.primary,
    boxShadow: `inset 0 2px 6px ${theme.primary}40, 0 0 0 3px ${theme.primary}40`,
  },
  featFilterResults: {
    fontSize: "13px",
    color: theme.warning,
    fontStyle: "italic",
    marginBottom: "10px",
    fontFamily: "'Cinzel', serif",
  },
  featsContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    maxHeight: "450px",
    overflowY: "auto",
    padding: "20px",
    borderRadius: "15px",
    border: `3px solid ${theme.border}`,
    boxShadow: `inset 0 2px 6px ${theme.warning}20`,
    backgroundColor: theme.background,
  },
  featCard: {
    background: theme.cardBackground,
    borderRadius: "15px",
    padding: "18px",
    transition: "all 0.3s ease",
    boxShadow:
      "0 6px 12px rgba(0,0,0,0.15), inset 0 1px 0 rgba(255,255,255,0.8)",
    border: `2px solid ${theme.border}`,
    position: "relative",
  },
  featCardSelected: {
    background: theme.success + "20",
    borderRadius: "15px",
    padding: "18px",
    transition: "all 0.3s ease",
    boxShadow:
      "0 6px 12px rgba(0,0,0,0.15), inset 0 1px 0 rgba(255,255,255,0.8)",
    border: `2px solid ${theme.success}`,
    position: "relative",
  },
  featHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "10px",
  },
  featLabelClickable: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    cursor: "pointer",
    flex: 1,
    userSelect: "none",
  },
  featCheckbox: {
    width: "20px",
    height: "20px",
    appearance: "none",
    border: `2px solid ${theme.warning}`,
    borderRadius: "4px",
    backgroundColor: theme.surface,
    cursor: "pointer",
    position: "relative",
    transition: "all 0.3s ease",
    boxShadow: `inset 0 1px 3px ${theme.warning}40`,
  },
  featCheckboxCheckmark: {
    content: "✓",
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    color: "white",
    fontSize: "14px",
    fontWeight: "bold",
  },
  featName: {
    fontSize: "18px",
    fontWeight: "600",
    fontFamily: "'Cinzel', serif",
    color: theme.text,
    textShadow: "1px 1px 2px rgba(0,0,0,0.1)",
    transition: "color 0.3s ease",
  },
  featNameSelected: {
    fontSize: "18px",
    fontWeight: "600",
    fontFamily: "'Cinzel', serif",
    color: theme.success,
    textShadow: "1px 1px 2px rgba(0,0,0,0.1)",
    transition: "color 0.3s ease",
  },
  featPreview: {
    fontSize: "14px",
    color: theme.textSecondary,
    lineHeight: "1.5",
    marginBottom: "10px",
    fontStyle: "italic",
    fontFamily: "'Times New Roman', serif",
    transition: "color 0.3s ease",
  },
  featPreviewSelected: {
    fontSize: "14px",
    color: theme.success,
    lineHeight: "1.5",
    marginBottom: "10px",
    fontStyle: "italic",
    fontFamily: "'Times New Roman', serif",
    transition: "color 0.3s ease",
  },
  featDescription: {
    fontSize: "14px",
    color: theme.text,
    lineHeight: "1.6",
    padding: "16px",
    background: theme.background,
    borderRadius: "10px",
    marginTop: "12px",
    border: `2px solid ${theme.border}`,
    fontFamily: "'Times New Roman', serif",
    boxShadow: "inset 0 2px 4px rgba(0,0,0,0.05)",
  },
  featDescriptionSelected: {
    fontSize: "14px",
    color: theme.text,
    lineHeight: "1.6",
    padding: "16px",
    background: theme.success + "20",
    borderRadius: "10px",
    marginTop: "12px",
    border: `2px solid ${theme.success}`,
    fontFamily: "'Times New Roman', serif",
    boxShadow: `inset 0 2px 4px ${theme.success}20`,
  },
  expandButton: {
    background: theme.warning,
    border: `2px solid ${theme.warning}`,
    borderRadius: "8px",
    width: "32px",
    height: "32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontSize: "16px",
    fontWeight: "bold",
    color: "white",
    transition: "all 0.3s ease",
    boxShadow: "0 3px 6px rgba(0,0,0,0.2)",
  },
  expandButtonHover: {
    background: theme.primary,
    transform: "translateY(-1px)",
    boxShadow: "0 4px 8px rgba(0,0,0,0.25)",
  },
  noFeatsFound: {
    textAlign: "center",
    padding: "40px 20px",
    color: theme.warning,
    fontStyle: "italic",
    background: theme.warning + "20",
    borderRadius: "12px",
    border: `2px dashed ${theme.warning}`,
    fontFamily: "'Cinzel', serif",
    fontSize: "16px",
  },
  newCharacterButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 20px",
    backgroundColor: theme.success,
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    width: "100%",
    justifyContent: "center",
    transition: "all 0.2s ease",
  },
  newCharacter: {
    fontSize: "12px",
    color: theme.textSecondary,
    textAlign: "center",
    marginTop: "8px",
    fontStyle: "italic",
  },

  userAvatarContainer: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginTop: "8px",
    fontSize: "14px",
    color: theme.textSecondary,
  },
  userAvatar: {
    width: "24px",
    height: "24px",
    borderRadius: "50%",
    border: `2px solid ${theme.primary}`,
  },
  welcomeText: {
    color: theme.text,
  },
  authContainer: {
    textAlign: "center",
    padding: "40px",
    backgroundColor: theme.warning + "20",
    border: `1px solid ${theme.warning}`,
    borderRadius: "8px",
    margin: "20px",
  },
  authHeader: {
    color: theme.warning,
    marginBottom: "16px",
  },
  authText: {
    color: theme.warning,
  },
  errorContainer: {
    backgroundColor: theme.error + "20",
    border: `1px solid ${theme.error}`,
    color: theme.error,
    padding: "12px",
    borderRadius: "8px",
    margin: "16px 0",
    fontSize: "14px",
  },
  tabContainer: {
    display: "flex",
    borderBottom: `2px solid ${theme.border}`,
    backgroundColor: theme.background,
    borderRadius: "8px 8px 0 0",
    overflow: "hidden",
  },
  tab: {
    flex: 1,
    padding: "16px 24px",
    cursor: "pointer",
    backgroundColor: theme.background,
    border: "none",
    fontSize: "16px",
    fontWeight: "600",
    color: theme.textSecondary,
    transition: "all 0.2s ease",
    borderBottom: "3px solid transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
  },
  activeTab: {
    backgroundColor: theme.surface,
    color: theme.primary,
    borderBottom: `3px solid ${theme.primary}`,
  },
  tabContent: {
    backgroundColor: theme.surface,
    borderRadius: "0 0 8px 8px",
    padding: "24px",
    minHeight: "600px",
  },
  level1ChoiceContainer: {
    marginBottom: "16px",
  },
  level1ChoiceLabel: {
    display: "flex",
    alignItems: "center",
    cursor: "pointer",
    marginBottom: "8px",
    padding: "12px",
    borderRadius: "8px",
    border: `2px solid ${theme.border}`,
    backgroundColor: theme.surface,
    transition: "all 0.2s ease",
  },
  level1ChoiceLabelSelected: {
    display: "flex",
    alignItems: "center",
    cursor: "pointer",
    marginBottom: "8px",
    padding: "12px",
    borderRadius: "8px",
    border: `2px solid ${theme.success}`,
    backgroundColor: theme.success + "20",
    transition: "all 0.2s ease",
  },
  level1ChoiceRadio: {
    marginRight: "8px",
  },
  level1ChoiceText: {
    fontSize: "14px",
    color: theme.text,
    fontWeight: "normal",
  },
  level1ChoiceTextSelected: {
    fontSize: "14px",
    color: theme.success,
    fontWeight: "bold",
  },
  characterLimitWarning: {
    backgroundColor: theme.error + "20",
    border: `2px solid ${theme.error}`,
    color: theme.error,
    padding: "16px",
    borderRadius: "8px",
    margin: "16px 0",
    fontSize: "14px",
    fontWeight: "bold",
    textAlign: "center",
  },
  characterLimitWarningText: {
    marginTop: "8px",
    fontWeight: "normal",
  },
  saveButtonEnabled: {
    backgroundColor: theme.primary,
  },
  saveButtonDisabled: {
    backgroundColor: theme.textSecondary,
  },
  characterCountWarning: {
    fontSize: "12px",
    color: theme.warning,
    textAlign: "center",
    marginTop: "8px",
    fontStyle: "italic",
  },
  createNewButtonContainer: {
    marginBottom: "20px",
  },
  createNewButton: {
    backgroundColor: theme.success,
    color: "white",
    border: "none",
    padding: "12px 24px",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "600",
    createNewButtonContainer: {
      marginBottom: "20px",
    },
    createNewButton: {
      display: "flex",
      alignItems: "center",
      gap: "8px",
      padding: "12px 24px",
      backgroundColor: theme.success,
      color: "white",
      border: "none",
      borderRadius: "8px",
      fontSize: "14px",
      fontWeight: "600",
      cursor: "pointer",
      transition: "all 0.2s ease",
    },
    createNewButtonText: {
      fontSize: "12px",
      color: theme.textSecondary,
      marginTop: "4px",
      fontStyle: "italic",
    },
    savedCharactersHeader: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: "20px",
    },
    createNewButtonInSaved: {
      backgroundColor: theme.primary,
      color: "white",
      border: "none",
      padding: "12px 24px",
      borderRadius: "8px",
      fontSize: "14px",
      fontWeight: "600",
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      gap: "8px",
      transition: "all 0.2s ease",
    },
    flex: "1",
    minWidth: "80px",
  },
  magicModifierItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    flex: "1",
  },
  magicModifierLabel: {
    marginBottom: "4px",
    color: theme.text,
    display: "block",
    padding: "10px",
    borderRadius: "6px",
    backgroundColor: theme.surface,
    textAlign: "center",
    fontSize: "16px",
    fontWeight: "bold",
  },
  magicModifiersGrid: {
    display: "flex",
    gap: "16px",
    flexWrap: "wrap",
    alignItems: "end",
    justifyContent: "space-between",
  },
  magicModifierInput: {
    width: "60px",
    textAlign: "center",
    fontSize: "16px",
    fontWeight: "bold",
    padding: "10px",
    borderRadius: "6px",
    border: `2px solid ${theme.border}`,
    backgroundColor: theme.surface,
    color: theme.text,
  },
  hpHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "15px",
  },
  hpTitle: {
    display: "block",
    fontWeight: "bold",
    marginBottom: "5px",
    color: theme.text,
    fontSize: "16px",
    margin: 0,
  },
  hpButtonGroup: {
    display: "flex",
    gap: "12px",
    alignItems: "center",
  },
  hpRollButton: {
    display: "flex",
    alignItems: "center",
    gap: "5px",
    padding: "8px 12px",
    backgroundColor: "#EF4444",
    color: "white",
    border: "none",
    borderRadius: "6px",
    fontSize: "14px",
    cursor: "pointer",
    fontWeight: "600",
    transition: "all 0.2s ease",
  },
  hpContent: {
    marginTop: "8px",
  },
  hpRollContainer: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginTop: "8px",
  },
  levelHpGrid: {
    marginBottom: "20px",
    display: "grid",
    gridTemplateColumns: "3fr 1fr 1fr",
    gap: "15px",
    alignItems: "start",
  },
  levelContainer: {
    display: "flex",
    flexDirection: "column",
  },
  hpFieldContainer: {
    display: "flex",
    flexDirection: "column",
  },
  hpControlsContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
    paddingTop: "28px",
  },
  hpControlsInline: {
    display: "flex",
    flexDirection: "row",
    gap: "8px",
    alignItems: "center",
  },
  hpToggleLabel: {
    fontSize: "10px",
    color: theme.textSecondary,
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  hpManualInput: {
    width: "60px",
    padding: "8px",
    borderRadius: "6px",
    border: `2px solid ${theme.border}`,
    fontSize: "16px",
    fontWeight: "bold",
    textAlign: "center",
    backgroundColor: theme.surface,
    color: theme.text,
  },
  hpDisplay: {
    padding: "8px 12px",
    borderRadius: "6px",
    border: `2px solid ${theme.success}`,
    backgroundColor: theme.success + "20",
    fontSize: "16px",
    fontWeight: "bold",
    color: theme.success,
    minWidth: "40px",
    textAlign: "center",
  },
  hpRollDisplay: {
    padding: "8px 12px",
    borderRadius: "6px",
    border: `2px solid ${theme.success}`,
    backgroundColor: theme.success + "20",
    fontSize: "16px",
    fontWeight: "bold",
    color: theme.success,
    minWidth: "40px",
    textAlign: "center",
  },
  hpModeIndicator: {
    fontSize: "11px",
    color: theme.textSecondary,
    fontStyle: "italic",
  },

  hpToggle: {
    position: "relative",
    width: "44px",
    height: "24px",
    borderRadius: "12px",
    cursor: "pointer",
    transition: "background-color 0.2s ease",
    border: "2px solid",
  },
  hpToggleKnob: {
    position: "absolute",
    top: "2px",
    width: "16px",
    height: "16px",
    backgroundColor: "white",
    borderRadius: "50%",
    transition: "left 0.2s ease",
    boxShadow: "0 1px 3px rgba(0,0,0,0.3)",
  },
});
