export const styles = {
  container: {
    padding: "20px",
    maxWidth: "1200px",
    margin: "0 auto",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: "15px",
    marginBottom: "30px",
    borderBottom: "3px solid #8B5CF6",
    paddingBottom: "15px",
  },
  title: {
    margin: 0,
    fontSize: "2.5rem",
    color: "#eee",
    textShadow: "2px 2px 4px rgba(0,0,0,0.1)",
  },
  mainGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "30px",
  },
  panel: {
    backgroundColor: "#F9FAFB",
    padding: "25px",
    borderRadius: "12px",
    border: "2px solid #E5E7EB",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
  },
  sectionHeader: {
    color: "#374151",
    marginBottom: "20px",
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  fieldContainer: {
    marginBottom: "20px",
  },
  label: {
    display: "block",
    fontWeight: "bold",
    marginBottom: "5px",
    color: "#374151",
  },
  input: {
    width: "100%",
    padding: "10px",
    borderRadius: "6px",
    border: "2px solid #D1D5DB",
    fontSize: "16px",
  },
  select: {
    width: "100%",
    padding: "10px",
    borderRadius: "6px",
    border: "2px solid #D1D5DB",
    fontSize: "16px",
  },
  levelHpGrid: {
    marginBottom: "20px",
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "15px",
  },
  hpDisplay: {
    padding: "10px",
    borderRadius: "6px",
    border: "2px solid #10B981",
    backgroundColor: "#ECFDF5",
    fontSize: "16px",
    fontWeight: "bold",
    color: "#059669",
    textAlign: "center",
  },
  hpCalculation: {
    fontSize: "11px",
    color: "#6B7280",
    marginTop: "4px",
    fontStyle: "italic",
    textAlign: "center",
  },
  skillsHeader: {
    color: "#374151",
    marginBottom: "15px",
  },
  skillsPlaceholder: {
    border: "2px solid #FEF3C7",
    borderRadius: "6px",
    padding: "15px",
    backgroundColor: "#FFFBEB",
    textAlign: "center",
    color: "#92400E",
    fontStyle: "italic",
  },
  skillsContainer: {
    border: "2px solid #E5E7EB",
    borderRadius: "6px",
    padding: "15px",
    backgroundColor: "white",
  },
  skillsSubheader: {
    color: "#6B7280",
    fontSize: "14px",
    fontWeight: "bold",
    marginBottom: "12px",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  skillsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "10px",
  },
  skillOptionBase: {
    display: "flex",
    alignItems: "center",
    padding: "8px",
    borderRadius: "4px",
  },
  skillCheckbox: {
    marginRight: "8px",
  },
  skillsComplete: {
    marginTop: "10px",
    padding: "8px",
    backgroundColor: "#ECFDF5",
    borderRadius: "4px",
    border: "1px solid #10B981",
    color: "#059669",
    fontSize: "12px",
    fontWeight: "bold",
    textAlign: "center",
  },
  helpText: {
    fontSize: "12px",
    color: "#6B7280",
    marginTop: "8px",
    fontStyle: "italic",
  },
  abilityScoresHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "15px",
  },
  abilityScoresTitle: {
    color: "#374151",
    margin: 0,
  },
  buttonGroup: {
    display: "flex",
    gap: "8px",
  },
  button: {
    display: "flex",
    alignItems: "center",
    gap: "5px",
    padding: "8px 12px",
    color: "white",
    border: "none",
    borderRadius: "6px",
    fontSize: "14px",
    cursor: "pointer",
  },
  availableStats: {
    marginBottom: "15px",
    padding: "10px",
    backgroundColor: "#FEF3C7",
    borderRadius: "6px",
    border: "2px solid #F59E0B",
  },
  availableStatsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "8px",
  },
  availableStatsLabel: {
    fontWeight: "bold",
    color: "#92400E",
  },
  availableStatsTotal: {
    fontWeight: "bold",
    color: "#92400E",
    fontSize: "16px",
  },
  completeIndicator: {
    color: "#059669",
    marginLeft: "10px",
  },
  statsContainer: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
  },
  statBadge: {
    padding: "4px 8px",
    backgroundColor: "#FBBF24",
    color: "#92400E",
    borderRadius: "4px",
    fontSize: "14px",
    fontWeight: "bold",
  },
  allAssignedText: {
    color: "#92400E",
    fontStyle: "italic",
  },
  abilityGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "15px",
  },
  abilityCard: {
    border: "2px solid #E5E7EB",
    borderRadius: "8px",
    padding: "12px",
    textAlign: "center",
    position: "relative",
    minHeight: "120px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
  },
  abilityName: {
    fontWeight: "bold",
    fontSize: "12px",
    color: "#6B7280",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    marginBottom: "8px",
  },
  abilityModifier: {
    fontSize: "28px",
    fontWeight: "bold",
    color: "#374151",
    margin: "8px 0",
  },
  abilityModifierEmpty: {
    fontSize: "24px",
    fontWeight: "bold",
    color: "#D1D5DB",
    margin: "8px 0",
  },
  abilityScoreContainer: {
    position: "relative",
  },
  abilityScore: {
    width: "36px",
    height: "36px",
    borderRadius: "50%",
    backgroundColor: "#10B981",
    color: "white",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "bold",
    fontSize: "16px",
    margin: "0 auto",
  },
  trashButton: {
    position: "absolute",
    top: "-6px",
    right: "-6px",
    width: "20px",
    height: "20px",
    padding: "2px",
    backgroundColor: "#EF4444",
    color: "white",
    border: "none",
    borderRadius: "50%",
    cursor: "pointer",
    fontSize: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  assignSelect: {
    width: "100%",
    padding: "6px",
    borderRadius: "4px",
    border: "2px solid #D1D5DB",
    fontSize: "12px",
    backgroundColor: "white",
  },
  featOption: {
    display: "flex",
    alignItems: "center",
    marginBottom: "8px",
    cursor: "pointer",
  },
  featText: {
    fontSize: "14px",
  },
  saveButton: {
    width: "100%",
    padding: "12px",
    color: "white",
    border: "none",
    borderRadius: "6px",
    fontSize: "16px",
    fontWeight: "bold",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
  },
  emptyCharacters: {
    textAlign: "center",
    padding: "40px",
    color: "#6B7280",
    fontStyle: "italic",
  },
  charactersContainer: {
    maxHeight: "600px",
    overflowY: "auto",
  },
  characterCard: {
    backgroundColor: "white",
    border: "2px solid #E5E7EB",
    borderRadius: "8px",
    padding: "15px",
    marginBottom: "15px",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.05)",
  },
  characterHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "10px",
  },
  characterName: {
    margin: "0 0 5px 0",
    color: "#1F2937",
  },
  characterDetails: {
    fontSize: "14px",
    color: "#6B7280",
  },
  characterActions: {
    display: "flex",
    gap: "5px",
  },
  actionButton: {
    padding: "6px",
    color: "white",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
  },
  heritage: {
    fontSize: "12px",
    color: "#059669",
    fontWeight: "bold",
  },
  feats: {
    fontSize: "12px",
    color: "#7C3AED",
    marginTop: "5px",
  },
  skills: {
    fontSize: "12px",
    color: "#0891B2",
    marginTop: "5px",
  },
  featFilterContainer: {
    marginBottom: "20px",
    position: "relative",
  },

  featFilterInput: {
    width: "100%",
    padding: "12px 50px 12px 16px",
    borderRadius: "10px",
    border: "3px solid #F59E0B",
    fontSize: "16px",
    backgroundColor: "#F9FAFB",
    marginBottom: "10px",
    fontFamily: "'Cinzel', serif",
    boxShadow:
      "inset 0 2px 6px rgba(245,158,11,0.2), 0 2px 4px rgba(0,0,0,0.1)",
    transition: "all 0.3s ease",
    color: "#92400E",
  },
  featFilterClearButton: {
    position: "absolute",
    right: "15px",
    top: "50%",
    transform: "translateY(-50%)",
    width: "24px",
    height: "24px",
    borderRadius: "50%",
    border: "2px solid #F59E0B",
    backgroundColor: "#F9FAFB",
    color: "#92400E",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "14px",
    fontWeight: "bold",
    transition: "all 0.3s ease",
    boxShadow: "0 2px 4px rgba(0,0,0,0.2)",
    zIndex: 1,
  },
  featFilterClearButtonHover: {
    backgroundColor: "#F9FAFB",
    transform: "translateY(-50%) scale(1.1)",
    boxShadow: "0 3px 6px rgba(0,0,0,0.3)",
  },
  featFilterInputFocus: {
    outline: "none",
    borderColor: "#DAA520",
    boxShadow:
      "inset 0 2px 6px rgba(139,69,19,0.2), 0 0 0 3px rgba(218,165,32,0.3)",
  },
  featFilterResults: {
    fontSize: "13px",
    color: "#92400E",
    fontStyle: "italic",
    marginBottom: "10px",
    fontFamily: "'Cinzel', serif",
  },
  featsContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    maxHeight: "450px",
    overflowY: "auto",
    padding: "20px",

    borderRadius: "15px",
    border: "3px solid #F9FAFB",
    boxShadow: "inset 0 2px 6px rgba(245,158,11,0.1)",
  },
  featCard: {
    background: "#FFFFFF",
    borderRadius: "15px",
    padding: "18px",
    transition: "all 0.3s ease",
    boxShadow:
      "0 6px 12px rgba(0,0,0,0.15), inset 0 1px 0 rgba(255,255,255,0.8)",
    border: "2px solid #F9FAFB",
    position: "relative",
  },
  featCardSelected: {
    background: "#F0FDF4",
    borderRadius: "15px",
    padding: "18px",
    transition: "all 0.3s ease",
    boxShadow:
      "0 6px 12px rgba(0,0,0,0.15), inset 0 1px 0 rgba(255,255,255,0.8)",
    border: "2px solid #10B981",
    position: "relative",
  },
  featHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "10px",
  },
  featLabelClickable: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    cursor: "pointer",
    flex: 1,
    userSelect: "none",
  },
  featCheckbox: {
    width: "20px",
    height: "20px",
    appearance: "none",
    border: "2px solid #F59E0B",
    borderRadius: "4px",
    backgroundColor: "#FFFFFF",
    cursor: "pointer",
    position: "relative",
    transition: "all 0.3s ease",
    boxShadow: "inset 0 1px 3px rgba(245,158,11,0.2)",
  },
  featCheckboxCheckmark: {
    content: "✓",
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    color: "white",
    fontSize: "14px",
    fontWeight: "bold",
  },
  featName: {
    fontSize: "18px",
    fontWeight: "600",
    fontFamily: "'Cinzel', serif",
    color: "#374151",
    textShadow: "1px 1px 2px rgba(0,0,0,0.1)",
    transition: "color 0.3s ease",
  },
  featNameSelected: {
    fontSize: "18px",
    fontWeight: "600",
    fontFamily: "'Cinzel', serif",
    color: "#059669",
    textShadow: "1px 1px 2px rgba(0,0,0,0.1)",
    transition: "color 0.3s ease",
  },
  featPreview: {
    fontSize: "14px",
    color: "#6B7280",
    lineHeight: "1.5",
    marginBottom: "10px",
    fontStyle: "italic",
    fontFamily: "'Times New Roman', serif",
    transition: "color 0.3s ease",
  },
  featPreviewSelected: {
    fontSize: "14px",
    color: "#047857",
    lineHeight: "1.5",
    marginBottom: "10px",
    fontStyle: "italic",
    fontFamily: "'Times New Roman', serif",
    transition: "color 0.3s ease",
  },
  featDescription: {
    fontSize: "14px",
    color: "#374151",
    lineHeight: "1.6",
    padding: "16px",
    background: "#F9FAFB",
    borderRadius: "10px",
    marginTop: "12px",
    border: "2px solid #E5E7EB",
    fontFamily: "'Times New Roman', serif",
    boxShadow: "inset 0 2px 4px rgba(0,0,0,0.05)",
  },
  featDescriptionSelected: {
    fontSize: "14px",
    color: "#374151",
    lineHeight: "1.6",
    padding: "16px",
    background: "#ECFDF5",
    borderRadius: "10px",
    marginTop: "12px",
    border: "2px solid #10B981",
    fontFamily: "'Times New Roman', serif",
    boxShadow: "inset 0 2px 4px rgba(16,185,129,0.1)",
  },
  expandButton: {
    background: "#FBBF24",
    border: "2px solid #F59E0B",
    borderRadius: "8px",
    width: "32px",
    height: "32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontSize: "16px",
    fontWeight: "bold",
    color: "#92400E",
    transition: "all 0.3s ease",
    boxShadow: "0 3px 6px rgba(0,0,0,0.2)",
  },
  expandButtonHover: {
    background: "#FCD34D",
    transform: "translateY(-1px)",
    boxShadow: "0 4px 8px rgba(0,0,0,0.25)",
  },
  noFeatsFound: {
    textAlign: "center",
    padding: "40px 20px",
    color: "#92400E",
    fontStyle: "italic",
    background: "#FEF3C7",
    borderRadius: "12px",
    border: "2px dashed #F59E0B",
    fontFamily: "'Cinzel', serif",
    fontSize: "16px",
  },
};
