export const styles = {
  container: {
    padding: "20px",
    maxWidth: "1200px",
    margin: "0 auto",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: "15px",
    marginBottom: "30px",
    borderBottom: "3px solid #8B5CF6",
    paddingBottom: "15px",
  },
  title: {
    margin: 0,
    fontSize: "2.5rem",
    color: "#eee",
    textShadow: "2px 2px 4px rgba(0,0,0,0.1)",
  },
  mainGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "30px",
  },
  panel: {
    backgroundColor: "#F9FAFB",
    padding: "25px",
    borderRadius: "12px",
    border: "2px solid #E5E7EB",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
  },
  sectionHeader: {
    color: "#374151",
    marginBottom: "20px",
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  fieldContainer: {
    marginBottom: "20px",
  },
  label: {
    display: "block",
    fontWeight: "bold",
    marginBottom: "5px",
    color: "#374151",
  },
  input: {
    width: "100%",
    padding: "10px",
    borderRadius: "6px",
    border: "2px solid #D1D5DB",
    fontSize: "16px",
  },
  select: {
    width: "100%",
    padding: "10px",
    borderRadius: "6px",
    border: "2px solid #D1D5DB",
    fontSize: "16px",
  },
  levelHpGrid: {
    marginBottom: "20px",
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "15px",
  },
  hpDisplay: {
    padding: "10px",
    borderRadius: "6px",
    border: "2px solid #10B981",
    backgroundColor: "#ECFDF5",
    fontSize: "16px",
    fontWeight: "bold",
    color: "#059669",
    textAlign: "center",
  },
  hpCalculation: {
    fontSize: "11px",
    color: "#6B7280",
    marginTop: "4px",
    fontStyle: "italic",
    textAlign: "center",
  },
  skillsHeader: {
    color: "#374151",
    marginBottom: "15px",
  },
  skillsPlaceholder: {
    border: "2px solid #FEF3C7",
    borderRadius: "6px",
    padding: "15px",
    backgroundColor: "#FFFBEB",
    textAlign: "center",
    color: "#92400E",
    fontStyle: "italic",
  },
  skillsContainer: {
    border: "2px solid #E5E7EB",
    borderRadius: "6px",
    padding: "15px",
    backgroundColor: "white",
  },
  skillsSubheader: {
    color: "#6B7280",
    fontSize: "14px",
    fontWeight: "bold",
    marginBottom: "12px",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  skillsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "10px",
  },
  skillOptionBase: {
    display: "flex",
    alignItems: "center",
    padding: "8px",
    borderRadius: "4px",
  },
  skillCheckbox: {
    marginRight: "8px",
  },
  skillsComplete: {
    marginTop: "10px",
    padding: "8px",
    backgroundColor: "#ECFDF5",
    borderRadius: "4px",
    border: "1px solid #10B981",
    color: "#059669",
    fontSize: "12px",
    fontWeight: "bold",
    textAlign: "center",
  },
  helpText: {
    fontSize: "12px",
    color: "#6B7280",
    marginTop: "8px",
    fontStyle: "italic",
  },
  abilityScoresHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "15px",
  },
  abilityScoresTitle: {
    color: "#374151",
    margin: 0,
  },
  buttonGroup: {
    display: "flex",
    gap: "8px",
  },
  button: {
    display: "flex",
    alignItems: "center",
    gap: "5px",
    padding: "8px 12px",
    color: "white",
    border: "none",
    borderRadius: "6px",
    fontSize: "14px",
    cursor: "pointer",
  },
  availableStats: {
    marginBottom: "15px",
    padding: "10px",
    borderRadius: "6px",
    border: "2px solid #FEF3C7",
    backgroundColor: "#FFFBEB",
  },
  availableStatsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "8px",
  },
  availableStatsLabel: {
    fontWeight: "bold",
    border: "2px solid #FEF3C7",
    borderRadius: "6px",
    padding: "15px",
    backgroundColor: "#FFFBEB",
    textAlign: "center",
    color: "#92400E",
    fontStyle: "italic",
  },
  availableStatsTotal: {
    fontWeight: "bold",
    color: "#92400E",
    fontSize: "16px",
  },
  completeIndicator: {
    color: "#059669",
    marginLeft: "10px",
  },
  statsContainer: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
  },
  statBadge: {
    padding: "4px 8px",
    backgroundColor: "#FBBF24",
    color: "#92400E",
    borderRadius: "4px",
    fontSize: "14px",
    fontWeight: "bold",
  },
  allAssignedText: {
    color: "#92400E",
    fontStyle: "italic",
  },
  abilityGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "15px",
  },
  abilityCard: {
    border: "2px solid #E5E7EB",
    borderRadius: "8px",
    padding: "12px",
    textAlign: "center",
    position: "relative",
    minHeight: "120px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
  },
  abilityName: {
    fontWeight: "bold",
    fontSize: "12px",
    color: "#6B7280",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    marginBottom: "8px",
  },
  abilityModifier: {
    fontSize: "28px",
    fontWeight: "bold",
    color: "#374151",
    margin: "8px 0",
  },
  abilityModifierEmpty: {
    fontSize: "24px",
    fontWeight: "bold",
    color: "#D1D5DB",
    margin: "8px 0",
  },
  abilityScoreContainer: {
    position: "relative",
  },
  abilityScore: {
    width: "36px",
    height: "36px",
    borderRadius: "50%",
    backgroundColor: "#10B981",
    color: "white",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "bold",
    fontSize: "16px",
    margin: "0 auto",
  },
  trashButton: {
    position: "absolute",
    top: "-6px",
    right: "-6px",
    width: "20px",
    height: "20px",
    padding: "2px",
    backgroundColor: "#EF4444",
    color: "white",
    border: "none",
    borderRadius: "50%",
    cursor: "pointer",
    fontSize: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  assignSelect: {
    width: "100%",
    padding: "6px",
    borderRadius: "4px",
    border: "2px solid #D1D5DB",
    fontSize: "12px",
    backgroundColor: "white",
  },
  featOption: {
    display: "flex",
    alignItems: "center",
    marginBottom: "8px",
    cursor: "pointer",
  },
  featText: {
    fontSize: "14px",
  },
  saveButton: {
    width: "100%",
    padding: "12px",
    color: "white",
    border: "none",
    borderRadius: "6px",
    fontSize: "16px",
    fontWeight: "bold",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
  },
  emptyCharacters: {
    textAlign: "center",
    padding: "40px",
    color: "#6B7280",
    fontStyle: "italic",
  },
  charactersContainer: {
    maxHeight: "600px",
    overflowY: "auto",
  },
  characterCard: {
    backgroundColor: "white",
    border: "2px solid #E5E7EB",
    borderRadius: "8px",
    padding: "15px",
    marginBottom: "15px",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.05)",
  },
  characterHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "10px",
  },
  characterName: {
    margin: "0 0 5px 0",
    color: "#1F2937",
  },
  characterDetails: {
    fontSize: "14px",
    color: "#6B7280",
  },
  characterActions: {
    display: "flex",
    gap: "5px",
  },
  actionButton: {
    padding: "6px",
    color: "white",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
  },
  heritage: {
    fontSize: "12px",
    color: "#059669",
    fontWeight: "bold",
  },
  feats: {
    fontSize: "12px",
    color: "#7C3AED",
    marginTop: "5px",
  },
  skills: {
    fontSize: "12px",
    color: "#0891B2",
    marginTop: "5px",
  },
  featFilterContainer: {
    marginBottom: "20px",
    position: "relative",
  },
  featFilterInput: {
    width: "100%",
    padding: "12px 50px 12px 16px",
    borderRadius: "10px",
    border: "3px solid #F59E0B",
    fontSize: "16px",
    backgroundColor: "#F9FAFB",
    marginBottom: "10px",
    fontFamily: "'Cinzel', serif",
    boxShadow:
      "inset 0 2px 6px rgba(245,158,11,0.2), 0 2px 4px rgba(0,0,0,0.1)",
    transition: "all 0.3s ease",
    color: "#92400E",
  },
  featFilterClearButton: {
    position: "absolute",
    right: "15px",
    top: "50%",
    transform: "translateY(-50%)",
    width: "24px",
    height: "24px",
    borderRadius: "50%",
    border: "2px solid #F59E0B",
    backgroundColor: "#F9FAFB",
    color: "#92400E",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "14px",
    fontWeight: "bold",
    transition: "all 0.3s ease",
    boxShadow: "0 2px 4px rgba(0,0,0,0.2)",
    zIndex: 1,
  },
  featFilterClearButtonHover: {
    backgroundColor: "#F9FAFB",
    transform: "translateY(-50%) scale(1.1)",
    boxShadow: "0 3px 6px rgba(0,0,0,0.3)",
  },
  featFilterInputFocus: {
    outline: "none",
    borderColor: "#DAA520",
    boxShadow:
      "inset 0 2px 6px rgba(139,69,19,0.2), 0 0 0 3px rgba(218,165,32,0.3)",
  },
  featFilterResults: {
    fontSize: "13px",
    color: "#92400E",
    fontStyle: "italic",
    marginBottom: "10px",
    fontFamily: "'Cinzel', serif",
  },
  featsContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    maxHeight: "450px",
    overflowY: "auto",
    padding: "20px",
    borderRadius: "15px",
    border: "3px solid #F9FAFB",
    boxShadow: "inset 0 2px 6px rgba(245,158,11,0.1)",
  },
  featCard: {
    background: "#FFFFFF",
    borderRadius: "15px",
    padding: "18px",
    transition: "all 0.3s ease",
    boxShadow:
      "0 6px 12px rgba(0,0,0,0.15), inset 0 1px 0 rgba(255,255,255,0.8)",
    border: "2px solid #F9FAFB",
    position: "relative",
  },
  featCardSelected: {
    background: "#F0FDF4",
    borderRadius: "15px",
    padding: "18px",
    transition: "all 0.3s ease",
    boxShadow:
      "0 6px 12px rgba(0,0,0,0.15), inset 0 1px 0 rgba(255,255,255,0.8)",
    border: "2px solid #10B981",
    position: "relative",
  },
  featHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "10px",
  },
  featLabelClickable: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    cursor: "pointer",
    flex: 1,
    userSelect: "none",
  },
  featCheckbox: {
    width: "20px",
    height: "20px",
    appearance: "none",
    border: "2px solid #F59E0B",
    borderRadius: "4px",
    backgroundColor: "#FFFFFF",
    cursor: "pointer",
    position: "relative",
    transition: "all 0.3s ease",
    boxShadow: "inset 0 1px 3px rgba(245,158,11,0.2)",
  },
  featCheckboxCheckmark: {
    content: "✓",
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    color: "white",
    fontSize: "14px",
    fontWeight: "bold",
  },
  featName: {
    fontSize: "18px",
    fontWeight: "600",
    fontFamily: "'Cinzel', serif",
    color: "#374151",
    textShadow: "1px 1px 2px rgba(0,0,0,0.1)",
    transition: "color 0.3s ease",
  },
  featNameSelected: {
    fontSize: "18px",
    fontWeight: "600",
    fontFamily: "'Cinzel', serif",
    color: "#059669",
    textShadow: "1px 1px 2px rgba(0,0,0,0.1)",
    transition: "color 0.3s ease",
  },
  featPreview: {
    fontSize: "14px",
    color: "#6B7280",
    lineHeight: "1.5",
    marginBottom: "10px",
    fontStyle: "italic",
    fontFamily: "'Times New Roman', serif",
    transition: "color 0.3s ease",
  },
  featPreviewSelected: {
    fontSize: "14px",
    color: "#047857",
    lineHeight: "1.5",
    marginBottom: "10px",
    fontStyle: "italic",
    fontFamily: "'Times New Roman', serif",
    transition: "color 0.3s ease",
  },
  featDescription: {
    fontSize: "14px",
    color: "#374151",
    lineHeight: "1.6",
    padding: "16px",
    background: "#F9FAFB",
    borderRadius: "10px",
    marginTop: "12px",
    border: "2px solid #E5E7EB",
    fontFamily: "'Times New Roman', serif",
    boxShadow: "inset 0 2px 4px rgba(0,0,0,0.05)",
  },
  featDescriptionSelected: {
    fontSize: "14px",
    color: "#374151",
    lineHeight: "1.6",
    padding: "16px",
    background: "#ECFDF5",
    borderRadius: "10px",
    marginTop: "12px",
    border: "2px solid #10B981",
    fontFamily: "'Times New Roman', serif",
    boxShadow: "inset 0 2px 4px rgba(16,185,129,0.1)",
  },
  expandButton: {
    background: "#FBBF24",
    border: "2px solid #F59E0B",
    borderRadius: "8px",
    width: "32px",
    height: "32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontSize: "16px",
    fontWeight: "bold",
    color: "#92400E",
    transition: "all 0.3s ease",
    boxShadow: "0 3px 6px rgba(0,0,0,0.2)",
  },
  expandButtonHover: {
    background: "#FCD34D",
    transform: "translateY(-1px)",
    boxShadow: "0 4px 8px rgba(0,0,0,0.25)",
  },
  noFeatsFound: {
    textAlign: "center",
    padding: "40px 20px",
    color: "#92400E",
    fontStyle: "italic",
    background: "#FEF3C7",
    borderRadius: "12px",
    border: "2px dashed #F59E0B",
    fontFamily: "'Cinzel', serif",
    fontSize: "16px",
  },
  newCharacterButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 20px",
    backgroundColor: "#10B981",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    width: "100%",
    justifyContent: "center",
    transition: "all 0.2s ease",
  },
  newCharacter: {
    fontSize: "12px",
    color: "#6B7280",
    textAlign: "center",
    marginTop: "8px",
    fontStyle: "italic",
  },
};

export const createThemedStyles = (theme) => ({
  container: {
    padding: "20px",
    maxWidth: "1200px",
    margin: "0 auto",
    backgroundColor: theme.background,
    minHeight: "100vh",
    transition: "background-color 0.3s ease",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: "15px",
    marginBottom: "30px",
    borderBottom: `3px solid ${theme.primary}`,
    paddingBottom: "15px",
  },
  title: {
    margin: 0,
    fontSize: "2.5rem",
    color: theme.text,
    textShadow: "2px 2px 4px rgba(0,0,0,0.1)",
  },
  mainGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "30px",
  },
  panel: {
    backgroundColor: theme.surface,
    padding: "25px",
    borderRadius: "12px",
    border: `2px solid ${theme.border}`,
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
  },
  sectionHeader: {
    color: theme.text,
    marginBottom: "20px",
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  fieldContainer: {
    marginBottom: "20px",
  },
  label: {
    display: "block",
    fontWeight: "bold",
    marginBottom: "5px",
    color: theme.text,
  },
  input: {
    width: "100%",
    padding: "10px",
    borderRadius: "6px",
    border: `2px solid ${theme.border}`,
    fontSize: "16px",
    backgroundColor: theme.surface,
    color: theme.text,
  },
  select: {
    width: "100%",
    padding: "10px",
    borderRadius: "6px",
    border: `2px solid ${theme.border}`,
    fontSize: "16px",
    backgroundColor: theme.surface,
    color: theme.text,
  },
  levelHpGrid: {
    marginBottom: "20px",
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "15px",
  },
  hpDisplay: {
    padding: "10px",
    borderRadius: "6px",
    border: `2px solid ${theme.success}`,
    backgroundColor: theme.success + "20",
    fontSize: "16px",
    fontWeight: "bold",
    color: theme.success,
    textAlign: "center",
  },
  hpCalculation: {
    fontSize: "11px",
    color: theme.textSecondary,
    marginTop: "4px",
    fontStyle: "italic",
    textAlign: "center",
  },
  skillsHeader: {
    color: theme.text,
    marginBottom: "15px",
  },
  skillsPlaceholder: {
    border: `2px solid ${theme.warning}40`,
    borderRadius: "6px",
    padding: "15px",
    backgroundColor: theme.warning + "20",
    textAlign: "center",
    color: theme.warning,
    fontStyle: "italic",
  },
  skillsContainer: {
    border: `2px solid ${theme.border}`,
    borderRadius: "6px",
    padding: "15px",
    backgroundColor: theme.surface,
  },
  skillsSubheader: {
    color: theme.textSecondary,
    fontSize: "14px",
    fontWeight: "bold",
    marginBottom: "12px",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  skillsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "10px",
  },
  skillOptionBase: {
    display: "flex",
    alignItems: "center",
    padding: "8px",
    borderRadius: "4px",
    color: theme.text,
  },
  skillCheckbox: {
    marginRight: "8px",
    accentColor: theme.primary,
  },
  skillsComplete: {
    marginTop: "10px",
    padding: "8px",
    backgroundColor: theme.success + "20",
    borderRadius: "4px",
    border: `1px solid ${theme.success}`,
    color: theme.success,
    fontSize: "12px",
    fontWeight: "bold",
    textAlign: "center",
  },
  helpText: {
    fontSize: "12px",
    color: theme.textSecondary,
    marginTop: "8px",
    fontStyle: "italic",
  },
  abilityScoresHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "15px",
  },
  abilityScoresTitle: {
    color: theme.text,
    margin: 0,
  },
  buttonGroup: {
    display: "flex",
    gap: "8px",
  },
  button: {
    display: "flex",
    alignItems: "center",
    gap: "5px",
    padding: "8px 12px",
    color: theme.surface,
    backgroundColor: theme.primary,
    border: "none",
    borderRadius: "6px",
    fontSize: "14px",
    cursor: "pointer",
    transition: "background-color 0.2s ease",
  },
  availableStats: {
    marginBottom: "15px",
    padding: "10px",
    borderRadius: "6px",
    border: `2px solid ${theme.warning}40`,
    backgroundColor: theme.warning + "20",
  },
  availableStatsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "8px",
  },
  availableStatsLabel: {
    fontWeight: "bold",
    border: `2px solid ${theme.warning}40`,
    borderRadius: "6px",
    padding: "15px",
    backgroundColor: theme.warning + "20",
    textAlign: "center",
    color: theme.warning,
    fontStyle: "italic",
  },
  availableStatsTotal: {
    fontWeight: "bold",
    color: theme.warning,
    fontSize: "16px",
  },
  completeIndicator: {
    color: theme.success,
    marginLeft: "10px",
  },
  statsContainer: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
  },
  statBadge: {
    padding: "4px 8px",
    backgroundColor: theme.warning + "60",
    color: theme.warning,
    borderRadius: "4px",
    fontSize: "14px",
    fontWeight: "bold",
    border: `1px solid ${theme.warning}`,
  },
  allAssignedText: {
    color: theme.warning,
    fontStyle: "italic",
  },
  abilityGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "15px",
  },
  abilityCard: {
    border: `2px solid ${theme.border}`,
    borderRadius: "8px",
    padding: "12px",
    textAlign: "center",
    position: "relative",
    minHeight: "120px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
  },
  abilityName: {
    fontWeight: "bold",
    fontSize: "12px",
    color: theme.textSecondary,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    marginBottom: "8px",
  },
  abilityModifier: {
    fontSize: "28px",
    fontWeight: "bold",
    color: theme.text,
    margin: "8px 0",
  },
  abilityModifierEmpty: {
    fontSize: "24px",
    fontWeight: "bold",
    color: theme.border,
    margin: "8px 0",
  },
  abilityScoreContainer: {
    position: "relative",
  },
  abilityScore: {
    width: "36px",
    height: "36px",
    borderRadius: "50%",
    backgroundColor: theme.success,
    color: theme.surface,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "bold",
    fontSize: "16px",
    margin: "0 auto",
  },
  trashButton: {
    position: "absolute",
    top: "-6px",
    right: "-6px",
    width: "20px",
    height: "20px",
    padding: "2px",
    backgroundColor: theme.error,
    color: theme.surface,
    border: "none",
    borderRadius: "50%",
    cursor: "pointer",
    fontSize: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  assignSelect: {
    width: "100%",
    padding: "6px",
    borderRadius: "4px",
    border: `2px solid ${theme.border}`,
    fontSize: "12px",
    backgroundColor: theme.surface,
    color: theme.text,
  },
  featOption: {
    display: "flex",
    alignItems: "center",
    marginBottom: "8px",
    cursor: "pointer",
    color: theme.text,
  },
  featText: {
    fontSize: "14px",
    color: theme.text,
  },
  saveButton: {
    width: "100%",
    padding: "12px",
    color: theme.surface,
    backgroundColor: theme.success,
    border: "none",
    borderRadius: "6px",
    fontSize: "16px",
    fontWeight: "bold",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    cursor: "pointer",
    transition: "background-color 0.2s ease",
  },
  emptyCharacters: {
    textAlign: "center",
    padding: "40px",
    color: theme.textSecondary,
    fontStyle: "italic",
  },
  charactersContainer: {
    maxHeight: "600px",
    overflowY: "auto",
  },
  characterCard: {
    backgroundColor: theme.surface,
    border: `2px solid ${theme.border}`,
    borderRadius: "8px",
    padding: "15px",
    marginBottom: "15px",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.05)",
  },
  characterHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "10px",
  },
  characterName: {
    margin: "0 0 5px 0",
    color: theme.text,
  },
  characterDetails: {
    fontSize: "14px",
    color: theme.textSecondary,
  },
  characterActions: {
    display: "flex",
    gap: "5px",
  },
  actionButton: {
    padding: "6px",
    color: theme.surface,
    backgroundColor: theme.primary,
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
  },
  heritage: {
    fontSize: "12px",
    color: theme.success,
    fontWeight: "bold",
  },
  feats: {
    fontSize: "12px",
    color: theme.accent,
    marginTop: "5px",
  },
  skills: {
    fontSize: "12px",
    color: theme.primary,
    marginTop: "5px",
  },
  featFilterContainer: {
    marginBottom: "20px",
    position: "relative",
  },
  featFilterInput: {
    width: "100%",
    padding: "12px 50px 12px 16px",
    borderRadius: "10px",
    border: `3px solid ${theme.warning}`,
    fontSize: "16px",
    backgroundColor: theme.surface,
    marginBottom: "10px",
    fontFamily: "'Cinzel', serif",
    boxShadow: `inset 0 2px 6px ${theme.warning}20, 0 2px 4px rgba(0,0,0,0.1)`,
    transition: "all 0.3s ease",
    color: theme.text,
  },
  featFilterClearButton: {
    position: "absolute",
    right: "15px",
    top: "50%",
    transform: "translateY(-50%)",
    width: "24px",
    height: "24px",
    borderRadius: "50%",
    border: `2px solid ${theme.warning}`,
    backgroundColor: theme.surface,
    color: theme.warning,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "14px",
    fontWeight: "bold",
    transition: "all 0.3s ease",
    boxShadow: "0 2px 4px rgba(0,0,0,0.2)",
    zIndex: 1,
  },
  featFilterClearButtonHover: {
    backgroundColor: theme.background,
    transform: "translateY(-50%) scale(1.1)",
    boxShadow: "0 3px 6px rgba(0,0,0,0.3)",
  },
  featFilterInputFocus: {
    outline: "none",
    borderColor: theme.primary,
    boxShadow: `inset 0 2px 6px ${theme.primary}20, 0 0 0 3px ${theme.primary}30`,
  },
  featFilterResults: {
    fontSize: "13px",
    color: theme.warning,
    fontStyle: "italic",
    marginBottom: "10px",
    fontFamily: "'Cinzel', serif",
  },
  featsContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    maxHeight: "450px",
    overflowY: "auto",
    padding: "20px",
    borderRadius: "15px",
    border: `3px solid ${theme.border}`,
    boxShadow: `inset 0 2px 6px ${theme.warning}10`,
    backgroundColor: theme.background,
  },
  featCard: {
    background: theme.surface,
    borderRadius: "15px",
    padding: "18px",
    transition: "all 0.3s ease",
    boxShadow:
      "0 6px 12px rgba(0,0,0,0.15), inset 0 1px 0 rgba(255,255,255,0.8)",
    border: `2px solid ${theme.border}`,
    position: "relative",
  },
  featCardSelected: {
    background: theme.success + "20",
    borderRadius: "15px",
    padding: "18px",
    transition: "all 0.3s ease",
    boxShadow:
      "0 6px 12px rgba(0,0,0,0.15), inset 0 1px 0 rgba(255,255,255,0.8)",
    border: `2px solid ${theme.success}`,
    position: "relative",
  },
  featHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "10px",
  },
  featLabelClickable: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    cursor: "pointer",
    flex: 1,
    userSelect: "none",
  },
  featCheckbox: {
    width: "20px",
    height: "20px",
    appearance: "none",
    border: `2px solid ${theme.warning}`,
    borderRadius: "4px",
    backgroundColor: theme.surface,
    cursor: "pointer",
    position: "relative",
    transition: "all 0.3s ease",
    boxShadow: `inset 0 1px 3px ${theme.warning}20`,
    accentColor: theme.warning,
  },
  featCheckboxCheckmark: {
    content: "✓",
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    color: theme.surface,
    fontSize: "14px",
    fontWeight: "bold",
  },
  featName: {
    fontSize: "18px",
    fontWeight: "600",
    fontFamily: "'Cinzel', serif",
    color: theme.text,
    textShadow: "1px 1px 2px rgba(0,0,0,0.1)",
    transition: "color 0.3s ease",
  },
  featNameSelected: {
    fontSize: "18px",
    fontWeight: "600",
    fontFamily: "'Cinzel', serif",
    color: theme.success,
    textShadow: "1px 1px 2px rgba(0,0,0,0.1)",
    transition: "color 0.3s ease",
  },
  featPreview: {
    fontSize: "14px",
    color: theme.textSecondary,
    lineHeight: "1.5",
    marginBottom: "10px",
    fontStyle: "italic",
    fontFamily: "'Times New Roman', serif",
    transition: "color 0.3s ease",
  },
  featPreviewSelected: {
    fontSize: "14px",
    color: theme.success,
    lineHeight: "1.5",
    marginBottom: "10px",
    fontStyle: "italic",
    fontFamily: "'Times New Roman', serif",
    transition: "color 0.3s ease",
  },
  featDescription: {
    fontSize: "14px",
    color: theme.text,
    lineHeight: "1.6",
    padding: "16px",
    background: theme.background,
    borderRadius: "10px",
    marginTop: "12px",
    border: `2px solid ${theme.border}`,
    fontFamily: "'Times New Roman', serif",
    boxShadow: "inset 0 2px 4px rgba(0,0,0,0.05)",
  },
  featDescriptionSelected: {
    fontSize: "14px",
    color: theme.text,
    lineHeight: "1.6",
    padding: "16px",
    background: theme.success + "20",
    borderRadius: "10px",
    marginTop: "12px",
    border: `2px solid ${theme.success}`,
    fontFamily: "'Times New Roman', serif",
    boxShadow: `inset 0 2px 4px ${theme.success}10`,
  },
  expandButton: {
    background: theme.warning + "60",
    border: `2px solid ${theme.warning}`,
    borderRadius: "8px",
    width: "32px",
    height: "32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontSize: "16px",
    fontWeight: "bold",
    color: theme.warning,
    transition: "all 0.3s ease",
    boxShadow: "0 3px 6px rgba(0,0,0,0.2)",
  },
  expandButtonHover: {
    background: theme.warning + "80",
    transform: "translateY(-1px)",
    boxShadow: "0 4px 8px rgba(0,0,0,0.25)",
  },
  noFeatsFound: {
    textAlign: "center",
    padding: "40px 20px",
    color: theme.warning,
    fontStyle: "italic",
    background: theme.warning + "20",
    borderRadius: "12px",
    border: `2px dashed ${theme.warning}`,
    fontFamily: "'Cinzel', serif",
    fontSize: "16px",
  },
  newCharacterButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 20px",
    backgroundColor: theme.success,
    color: theme.surface,
    border: "none",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    width: "100%",
    justifyContent: "center",
    transition: "all 0.2s ease",
  },
  newCharacter: {
    fontSize: "12px",
    color: theme.textSecondary,
    textAlign: "center",
    marginTop: "8px",
    fontStyle: "italic",
  },

  authRequired: {
    textAlign: "center",
    padding: "40px",
    backgroundColor: theme.warning + "20",
    border: `1px solid ${theme.warning}`,
    borderRadius: "8px",
    margin: "20px",
  },
  authRequiredTitle: {
    color: theme.warning,
    marginBottom: "16px",
  },
  authRequiredText: {
    color: theme.warning,
  },
  errorDisplay: {
    backgroundColor: theme.error + "20",
    border: `1px solid ${theme.error}40`,
    color: theme.error,
    padding: "12px",
    borderRadius: "8px",
    margin: "16px 0",
    fontSize: "14px",
  },

  userAvatarContainer: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginTop: "8px",
    fontSize: "14px",
    color: theme.textSecondary,
  },
  userAvatar: {
    width: "24px",
    height: "24px",
    borderRadius: "50%",
    border: `2px solid ${theme.primary}`,
  },
  userWelcomeText: {
    color: theme.text,
  },

  headerContainer: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
  },
  headerContent: {
    flex: 1,
  },
  wandIconColor: {
    color: theme.primary,
  },

  characterLimitWarning: {
    backgroundColor: theme.error + "20",
    border: `2px solid ${theme.error}`,
    color: theme.error,
    padding: "16px",
    borderRadius: "8px",
    margin: "16px 0",
    fontSize: "14px",
    fontWeight: "bold",
    textAlign: "center",
  },
  characterLimitSubtext: {
    marginTop: "8px",
    fontWeight: "normal",
  },
  characterCountWarning: {
    fontSize: "12px",
    color: theme.warning,
    textAlign: "center",
    marginTop: "8px",
    fontStyle: "italic",
  },

  featCompleteMessage: {
    backgroundColor: theme.success + "20",
    border: `2px solid ${theme.success}`,
    color: theme.success,
    padding: "12px",
    borderRadius: "8px",
    margin: "12px 0",
    fontSize: "14px",
    fontWeight: "bold",
    textAlign: "center",
  },

  toggleContainer: {
    position: "relative",
    marginTop: "4px",
    width: "44px",
    height: "24px",
    borderRadius: "12px",
    cursor: "pointer",
    transition: "background-color 0.2s ease",
    border: "2px solid",
  },
  toggleActive: {
    backgroundColor: theme.success,
    borderColor: theme.success,
  },
  toggleInactive: {
    backgroundColor: theme.border,
    borderColor: theme.textSecondary,
  },
  toggleSlider: {
    position: "absolute",
    top: "2px",
    width: "16px",
    height: "16px",
    backgroundColor: theme.surface,
    borderRadius: "50%",
    transition: "left 0.2s ease",
    boxShadow: "0 1px 3px rgba(0,0,0,0.3)",
  },
  toggleSliderActive: {
    left: "22px",
  },
  toggleSliderInactive: {
    left: "2px",
  },

  rollStatsButton: {
    backgroundColor: theme.error,
  },

  buttonGroupContainer: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  abilityCardAssigned: {
    backgroundColor: theme.success + "20",
  },
  abilityCardEmpty: {
    backgroundColor: theme.surface,
  },

  manualInput: {
    textAlign: "center",
    fontSize: "18px",
    fontWeight: "bold",
    width: "60px",
    padding: "4px",
    backgroundColor: theme.surface,
    color: theme.text,
    border: `2px solid ${theme.border}`,
    borderRadius: "6px",
  },
  manualInputSmall: {
    textAlign: "center",
    fontSize: "16px",
    width: "80px",
    padding: "4px",
    backgroundColor: theme.surface,
    color: theme.text,
    border: `2px solid ${theme.border}`,
    borderRadius: "6px",
  },

  skillOptionSelected: {
    cursor: "pointer",
    backgroundColor: theme.success + "20",
    border: `2px solid ${theme.success}`,
    opacity: 1,
  },
  skillOptionUnselected: {
    cursor: "pointer",
    backgroundColor: theme.surface,
    border: `2px solid ${theme.border}`,
    opacity: 1,
  },
  skillOptionDisabled: {
    cursor: "not-allowed",
    backgroundColor: theme.surface,
    border: `2px solid ${theme.border}`,
    opacity: 0.5,
  },
  skillTextSelected: {
    fontSize: "14px",
    color: theme.success,
    fontWeight: "bold",
  },
  skillTextUnselected: {
    fontSize: "14px",
    color: theme.text,
    fontWeight: "normal",
  },

  magicModifiersContainer: {
    display: "flex",
    gap: "16px",
    flexWrap: "wrap",
    alignItems: "end",
    justifyContent: "space-between",
  },
  magicModifierField: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    flex: "1",
    minWidth: "80px",
  },
  magicModifierLabel: {
    fontSize: "14px",
    marginBottom: "4px",
    textAlign: "center",
    display: "block",
    fontWeight: "bold",
    color: theme.text,
  },
  magicModifierInput: {
    width: "60px",
    textAlign: "center",
    fontSize: "16px",
    fontWeight: "bold",
    padding: "10px",
    borderRadius: "6px",
    border: `2px solid ${theme.border}`,
    backgroundColor: theme.surface,
    color: theme.text,
  },

  featCheckboxStyled: {
    width: "18px",
    height: "18px",
    marginRight: "8px",
    cursor: "pointer",
    accentColor: theme.primary,
    transform: "scale(1.2)",
  },

  newCharacterButtonHover: {
    backgroundColor: theme.success + "D0",
    transform: "translateY(-1px)",
    boxShadow: `0 4px 12px ${theme.success}30`,
  },

  saveButtonEnabled: {
    backgroundColor: theme.primary,
    cursor: "pointer",
  },
  saveButtonDisabled: {
    backgroundColor: theme.border,
    cursor: "not-allowed",
  },

  featFilterClearButtonHoverThemed: {
    backgroundColor: theme.warning + "80",
    transform: "translateY(-50%) scale(1.1)",
    boxShadow: "0 3px 6px rgba(0,0,0,0.3)",
  },

  featFilterInputFocusThemed: {
    outline: "none",
    borderColor: theme.warning,
    boxShadow: `inset 0 2px 6px ${theme.warning}20, 0 0 0 3px ${theme.warning}30`,
  },
  featFilterInputBlurThemed: {
    borderColor: theme.warning,
    boxShadow: `inset 0 2px 6px ${theme.warning}20, 0 2px 4px rgba(0,0,0,0.1)`,
  },
  hpDisplayEnabled: {
    opacity: 1,
    color: theme.text,
  },

  hpDisplayDisabled: {
    opacity: 0.5,
    color: theme.textSecondary,
  },

  hpHelpText: {
    fontSize: "12px",
    color: theme.textSecondary,
    fontStyle: "italic",
    marginTop: "4px",
  },

  formValidationContainer: {
    backgroundColor: theme.surface,
    border: `1px solid ${theme.border}`,
    borderRadius: "8px",
    padding: "12px",
    marginBottom: "16px",
  },

  formValidationHeader: {
    fontSize: "14px",
    fontWeight: "600",
    color: theme.text,
    marginBottom: "8px",
  },

  formValidationList: {
    fontSize: "12px",
    color: theme.textSecondary,
  },

  formValidationItem: {
    marginBottom: "4px",
  },
});

export default styles;
