export const getInitialCharacterState = () => ({
  name: "",
  house: "",
  houseChoices: {},
  asiChoices: {},
  castingStyle: "",
  initiativeAbility: "dexterity",
  subclass: "",
  innateHeritage: "",
  background: "",
  backgroundSkills: [],
  innateHeritageSkills: [],
  gameSession: "",
  standardFeats: [],
  skillProficiencies: [],
  abilityScores: {
    strength: null,
    dexterity: null,
    constitution: null,
    intelligence: null,
    wisdom: null,
    charisma: null,
  },
  hitPoints: 0,
  level: 1,
  wandType: "",
  magicModifiers: {
    divinations: 0,
    charms: 0,
    transfiguration: 0,
    healing: 0,
    jinxesHexesCurses: 0,
  },
  level1ChoiceType: "",
});

export const gameSessionOptions = [
  "Sunday - Knights",
  "Monday - Haunting",
  "Tuesday - Knights",
  "Wednesday - Haunting",
  "Thursday - Knights",
  "Friday - Knights",
  "Saturday - Haunting",
  "Saturday - Knights",
  "DEVELOPMENT",
];
